* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2021-07-01 Thu 09:00>--<2021-07-01 Thu 10:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* Atelier Emacs (in French): Atelier Emacs Paris
:PROPERTIES:
:LOCATION: https://mobilizon.fr/events/ef8b82a4-f633-4bbd-ad6b-b8ac1031a01d
:END:
<2021-07-01 Thu 10:30>--<2021-07-01 Thu 11:30>

Les rencontres ont lieu sur cette instance de BBB.Tous les détails sur
M-x doctor RETNous gardons parfois des notes des soirées passées sur ce
dépôt.


* EmacsConf 2021 public meeting
:PROPERTIES:
:LOCATION: https://lists.gnu.org/archive/html/emacsconf-discuss/2021-06/msg00001.html
:END:
<2021-07-03 Sat 09:00>--<2021-07-03 Sat 11:00>

https://lists.gnu.org/archive/html/emacsconf-discuss/2021-06/msg00001.html


#+BEGIN_EXAMPLE
    Greetings, fellow Emacsians!Come help us make the next EmacsConf even better!  We'd like to announcean online meeting to prepare for the next conference.  The first meetingwill be on Saturday, July 3, 2021 at 10am EDT (equivalently: 7am PDT,2pm UTC, or 4pm CET), and other meetings may be scheduled as needed.During the meeting, we will give a quick overview of lessons learned,timelines, ideas/plans, and things we need help with in terms of:- diversity and outreach;- accessibility;- technology and infrastructure;- scheduling, including themes and tracks (e.g. talks by/for beginners,  music, multimedia, Org, GTD, gaming, system administration, etc); and- feedback and/or discussion around other aspects of the conference.The meeting will be held on the BigBlueButton instance graciously hostedby Fosshost for us, at:        https://bbb.emacsverse.org/b/ban-7vp-bw0-hdqUsing BigBlueButton requires running JavaScript, though the JavaScriptcode is free/libre software.  If you are unable or unwilling to join theBigBlueButton call, we also plan on live streaming the meeting (detailsto be announced later and added on live.emacsconf.org), and we'll try tokeep an eye on our IRC channel #emacsconf on the Libera.Chat network ifyou'd like to participate via IRC.If you can't make it to the meeting, we would still like to hear fromyou and receive your valuable feedback.  You can share your thoughtswith us about the above topics and/or other related matters by sendingan email to one of the following addresses of your choosing, whereEmacsConf organizers are subscribed and will receive your feedback:- emacsconf-org@gnu.org: publicly archived mailing list, or- emacsconf-org-private@gnu.org: private mailing list, where  only EmacsConf organizers will receive your messages.Looking forward to hearing from and seeing you for the meeting!Amin Bandali,On behalf of the EmacsConf organizers
#+END_EXAMPLE


* EmacsATX: Literate Config, Elfeed, SMS
:PROPERTIES:
:LOCATION: https://www.meetup.com/EmacsATX/events/278683891/
:END:
<2021-07-07 Wed 18:30>--<2021-07-07 Wed 20:30>

EmacsATX Wednesday, July 7 at 6:30 PM About Emacs ATX is a meetup
devoted to exploring the vast and ever expanding universe of the
extensible, customizable, free/libre editor Emacs. We are...
https://www.meetup.com/EmacsATX/events/278683891/


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2021-07-16 Fri 09:00>--<2021-07-16 Fri 10:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* Emacs APAC (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-apac.gitlab.io/
:END:
<2021-07-24 Sat 03:30>--<2021-07-24 Sat 05:30>

We are Emacs enthusiasts who live in the Asia-Pacific (APAC) time-zone.
We meet every fourth Saturday of the month.

** Where
   :PROPERTIES:
   :CUSTOM_ID: where
   :END:

The event is scheduled virtually using Jitsi Meet at 1400 Indian
Standard Time (IST). The meeting URL is posted on Freenode IRC
channels =#emacs=, =#ilugc= and =#emacsconf=, 30 minutes prior to the
meeting, and also on the [[https://www.freelists.org/list/ilugc][ILUGC
mailing list]] on the day of the meetup. If you are not subscribed, you
can also check
the [[https://www.freelists.org/archive/ilugc/][archive]].

Checkout the upcoming
meetings [[https://emacs-apac.gitlab.io/#upcoming][here]].

** Talks
   :PROPERTIES:
   :CUSTOM_ID: talks
   :END:

We usually have free flowing discussions around new Emacs packages /
features discovered, issues faced, experiences, usage tips, resources
for further learning etc. These are related to GNU Emacs and its
variants. Sometimes people also share their screens and give demos of
their Emacs setup and use.

If you would like to give a talk (20 minutes maximum), please send an
email to TODO with the details.

** Frequently Asked Questions
   :PROPERTIES:
   :CUSTOM_ID: frequently-asked-questions
   :END:

- *I'm new to Emacs, can / should I join?*
  Yes! You are always welcome. We have participants from different walks
  of life with varied experiences in Emacs. You can ask your questions
  and the attendees will be able to help, at least point you in the
  right direction.

- *Which language is used for communication?*
  English.

- *I'm not from APAC, can I join?*
  Definitely! If the timing is suitable for you, please join.




* Emacs Berlin (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-berlin.org/
:END:
<2021-07-28 Wed 11:30>--<2021-07-28 Wed 13:30>

[[https://emacs-berlin.org/]] 

New to Emacs? Longtime elisp expert? Just want to know what this is all
about? Come join us!

Location

Room open from 18:30 CET, if there are talks they'll start at 19:00 CET.
The video link will be posted on the day of the meetup to the mailing
list. Check the archive
([[https://mailb.org/pipermail/emacs-berlin/2021/thread.html]]) if you
are not subscribed.

About Emacs Berlin
We are Emacs enthusiasts in Berlin, meeting every last Wednesday of the
month.
The best way to stay posted is through our mailing list. Sign up
([[https://mailb.org/mailman/listinfo/emacs-berlin]]) and meet your
fellow Emacsers, or have a look at the mailing list archives
([[https://mailb.org/pipermail/emacs-berlin/]]) (gmane).
Feel free to send an email introducing yourself after subscribing!
You can also chat with us on irc: #emacs-berlin (connection instructions
([[https://mailb.org/pipermail/emacs-berlin/2020/000583.html]]))
Or on Twitter: @emacsberlin ([[https://twitter.com/emacsberlin]])
And there's a YouTube Channel
([[https://www.youtube.com/channel/UC1O8700SW-wuC4fvDEoGzOw]])  
And
on [[http://meetup.com/Emacs-Berlin-Meetup][meetup.com/Emacs-Berlin-Meetup]]
([[https://www.meetup.com/Emacs-Berlin-Meetup/]])
Non-public contact via email: organizers email
(mailto:[[mailto:emacs-berlin-owner@emacs-berlin.org][emacs-berlin-owner@emacs-berlin.org]])


* EmacsATX: TBD
:PROPERTIES:
:LOCATION: https://www.meetup.com/EmacsATX/events/hkckgsycclbgb/
:END:
<2021-08-04 Wed 18:30>--<2021-08-04 Wed 20:30>

EmacsATX Wednesday, August 4 at 6:30 PM About Emacs ATX is a meetup
devoted to exploring the vast and ever expanding universe of the
extensible, customizable, free/libre editor Emacs. We are...
https://www.meetup.com/EmacsATX/events/hkckgsycclbgb/


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2021-08-05 Thu 09:00>--<2021-08-05 Thu 10:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2021-08-20 Fri 09:00>--<2021-08-20 Fri 10:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* Emacs Berlin (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-berlin.org/
:END:
<2021-08-25 Wed 11:30>--<2021-08-25 Wed 13:30>

[[https://emacs-berlin.org/]] 

New to Emacs? Longtime elisp expert? Just want to know what this is all
about? Come join us!

Location

Room open from 18:30 CET, if there are talks they'll start at 19:00 CET.
The video link will be posted on the day of the meetup to the mailing
list. Check the archive
([[https://mailb.org/pipermail/emacs-berlin/2021/thread.html]]) if you
are not subscribed.

About Emacs Berlin
We are Emacs enthusiasts in Berlin, meeting every last Wednesday of the
month.
The best way to stay posted is through our mailing list. Sign up
([[https://mailb.org/mailman/listinfo/emacs-berlin]]) and meet your
fellow Emacsers, or have a look at the mailing list archives
([[https://mailb.org/pipermail/emacs-berlin/]]) (gmane).
Feel free to send an email introducing yourself after subscribing!
You can also chat with us on irc: #emacs-berlin (connection instructions
([[https://mailb.org/pipermail/emacs-berlin/2020/000583.html]]))
Or on Twitter: @emacsberlin ([[https://twitter.com/emacsberlin]])
And there's a YouTube Channel
([[https://www.youtube.com/channel/UC1O8700SW-wuC4fvDEoGzOw]])  
And
on [[http://meetup.com/Emacs-Berlin-Meetup][meetup.com/Emacs-Berlin-Meetup]]
([[https://www.meetup.com/Emacs-Berlin-Meetup/]])
Non-public contact via email: organizers email
(mailto:[[mailto:emacs-berlin-owner@emacs-berlin.org][emacs-berlin-owner@emacs-berlin.org]])


* Emacs APAC (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-apac.gitlab.io/
:END:
<2021-08-28 Sat 03:30>--<2021-08-28 Sat 05:30>

We are Emacs enthusiasts who live in the Asia-Pacific (APAC) time-zone.
We meet every fourth Saturday of the month.

** Where
   :PROPERTIES:
   :CUSTOM_ID: where
   :END:

The event is scheduled virtually using Jitsi Meet at 1400 Indian
Standard Time (IST). The meeting URL is posted on Freenode IRC
channels =#emacs=, =#ilugc= and =#emacsconf=, 30 minutes prior to the
meeting, and also on the [[https://www.freelists.org/list/ilugc][ILUGC
mailing list]] on the day of the meetup. If you are not subscribed, you
can also check
the [[https://www.freelists.org/archive/ilugc/][archive]].

Checkout the upcoming
meetings [[https://emacs-apac.gitlab.io/#upcoming][here]].

** Talks
   :PROPERTIES:
   :CUSTOM_ID: talks
   :END:

We usually have free flowing discussions around new Emacs packages /
features discovered, issues faced, experiences, usage tips, resources
for further learning etc. These are related to GNU Emacs and its
variants. Sometimes people also share their screens and give demos of
their Emacs setup and use.

If you would like to give a talk (20 minutes maximum), please send an
email to TODO with the details.

** Frequently Asked Questions
   :PROPERTIES:
   :CUSTOM_ID: frequently-asked-questions
   :END:

- *I'm new to Emacs, can / should I join?*
  Yes! You are always welcome. We have participants from different walks
  of life with varied experiences in Emacs. You can ask your questions
  and the attendees will be able to help, at least point you in the
  right direction.

- *Which language is used for communication?*
  English.

- *I'm not from APAC, can I join?*
  Definitely! If the timing is suitable for you, please join.




* EmacsATX: TBD
:PROPERTIES:
:LOCATION: https://www.meetup.com/EmacsATX/events/hkckgsyccmbcb/
:END:
<2021-09-01 Wed 18:30>--<2021-09-01 Wed 20:30>

EmacsATX Wednesday, September 1 at 6:30 PM About Emacs ATX is a meetup
devoted to exploring the vast and ever expanding universe of the
extensible, customizable, free/libre editor Emacs. We are...
https://www.meetup.com/EmacsATX/events/hkckgsyccmbcb/


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2021-09-02 Thu 09:00>--<2021-09-02 Thu 10:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2021-09-17 Fri 09:00>--<2021-09-17 Fri 10:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* Emacs APAC (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-apac.gitlab.io/
:END:
<2021-09-25 Sat 03:30>--<2021-09-25 Sat 05:30>

We are Emacs enthusiasts who live in the Asia-Pacific (APAC) time-zone.
We meet every fourth Saturday of the month.

** Where
   :PROPERTIES:
   :CUSTOM_ID: where
   :END:

The event is scheduled virtually using Jitsi Meet at 1400 Indian
Standard Time (IST). The meeting URL is posted on Freenode IRC
channels =#emacs=, =#ilugc= and =#emacsconf=, 30 minutes prior to the
meeting, and also on the [[https://www.freelists.org/list/ilugc][ILUGC
mailing list]] on the day of the meetup. If you are not subscribed, you
can also check
the [[https://www.freelists.org/archive/ilugc/][archive]].

Checkout the upcoming
meetings [[https://emacs-apac.gitlab.io/#upcoming][here]].

** Talks
   :PROPERTIES:
   :CUSTOM_ID: talks
   :END:

We usually have free flowing discussions around new Emacs packages /
features discovered, issues faced, experiences, usage tips, resources
for further learning etc. These are related to GNU Emacs and its
variants. Sometimes people also share their screens and give demos of
their Emacs setup and use.

If you would like to give a talk (20 minutes maximum), please send an
email to TODO with the details.

** Frequently Asked Questions
   :PROPERTIES:
   :CUSTOM_ID: frequently-asked-questions
   :END:

- *I'm new to Emacs, can / should I join?*
  Yes! You are always welcome. We have participants from different walks
  of life with varied experiences in Emacs. You can ask your questions
  and the attendees will be able to help, at least point you in the
  right direction.

- *Which language is used for communication?*
  English.

- *I'm not from APAC, can I join?*
  Definitely! If the timing is suitable for you, please join.




* Emacs Berlin (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-berlin.org/
:END:
<2021-09-29 Wed 11:30>--<2021-09-29 Wed 13:30>

[[https://emacs-berlin.org/]] 

New to Emacs? Longtime elisp expert? Just want to know what this is all
about? Come join us!

Location

Room open from 18:30 CET, if there are talks they'll start at 19:00 CET.
The video link will be posted on the day of the meetup to the mailing
list. Check the archive
([[https://mailb.org/pipermail/emacs-berlin/2021/thread.html]]) if you
are not subscribed.

About Emacs Berlin
We are Emacs enthusiasts in Berlin, meeting every last Wednesday of the
month.
The best way to stay posted is through our mailing list. Sign up
([[https://mailb.org/mailman/listinfo/emacs-berlin]]) and meet your
fellow Emacsers, or have a look at the mailing list archives
([[https://mailb.org/pipermail/emacs-berlin/]]) (gmane).
Feel free to send an email introducing yourself after subscribing!
You can also chat with us on irc: #emacs-berlin (connection instructions
([[https://mailb.org/pipermail/emacs-berlin/2020/000583.html]]))
Or on Twitter: @emacsberlin ([[https://twitter.com/emacsberlin]])
And there's a YouTube Channel
([[https://www.youtube.com/channel/UC1O8700SW-wuC4fvDEoGzOw]])  
And
on [[http://meetup.com/Emacs-Berlin-Meetup][meetup.com/Emacs-Berlin-Meetup]]
([[https://www.meetup.com/Emacs-Berlin-Meetup/]])
Non-public contact via email: organizers email
(mailto:[[mailto:emacs-berlin-owner@emacs-berlin.org][emacs-berlin-owner@emacs-berlin.org]])


* EmacsATX: TBD
:PROPERTIES:
:LOCATION: https://www.meetup.com/EmacsATX/events/hkckgsyccnbjb/
:END:
<2021-10-06 Wed 18:30>--<2021-10-06 Wed 20:30>

EmacsATX Wednesday, October 6 at 6:30 PM About Emacs ATX is a meetup
devoted to exploring the vast and ever expanding universe of the
extensible, customizable, free/libre editor Emacs. We are...
https://www.meetup.com/EmacsATX/events/hkckgsyccnbjb/


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2021-10-07 Thu 09:00>--<2021-10-07 Thu 10:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2021-10-15 Fri 09:00>--<2021-10-15 Fri 10:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* Emacs APAC (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-apac.gitlab.io/
:END:
<2021-10-23 Sat 03:30>--<2021-10-23 Sat 05:30>

We are Emacs enthusiasts who live in the Asia-Pacific (APAC) time-zone.
We meet every fourth Saturday of the month.

** Where
   :PROPERTIES:
   :CUSTOM_ID: where
   :END:

The event is scheduled virtually using Jitsi Meet at 1400 Indian
Standard Time (IST). The meeting URL is posted on Freenode IRC
channels =#emacs=, =#ilugc= and =#emacsconf=, 30 minutes prior to the
meeting, and also on the [[https://www.freelists.org/list/ilugc][ILUGC
mailing list]] on the day of the meetup. If you are not subscribed, you
can also check
the [[https://www.freelists.org/archive/ilugc/][archive]].

Checkout the upcoming
meetings [[https://emacs-apac.gitlab.io/#upcoming][here]].

** Talks
   :PROPERTIES:
   :CUSTOM_ID: talks
   :END:

We usually have free flowing discussions around new Emacs packages /
features discovered, issues faced, experiences, usage tips, resources
for further learning etc. These are related to GNU Emacs and its
variants. Sometimes people also share their screens and give demos of
their Emacs setup and use.

If you would like to give a talk (20 minutes maximum), please send an
email to TODO with the details.

** Frequently Asked Questions
   :PROPERTIES:
   :CUSTOM_ID: frequently-asked-questions
   :END:

- *I'm new to Emacs, can / should I join?*
  Yes! You are always welcome. We have participants from different walks
  of life with varied experiences in Emacs. You can ask your questions
  and the attendees will be able to help, at least point you in the
  right direction.

- *Which language is used for communication?*
  English.

- *I'm not from APAC, can I join?*
  Definitely! If the timing is suitable for you, please join.




* Emacs Berlin (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-berlin.org/
:END:
<2021-10-27 Wed 11:30>--<2021-10-27 Wed 13:30>

[[https://emacs-berlin.org/]] 

New to Emacs? Longtime elisp expert? Just want to know what this is all
about? Come join us!

Location

Room open from 18:30 CET, if there are talks they'll start at 19:00 CET.
The video link will be posted on the day of the meetup to the mailing
list. Check the archive
([[https://mailb.org/pipermail/emacs-berlin/2021/thread.html]]) if you
are not subscribed.

About Emacs Berlin
We are Emacs enthusiasts in Berlin, meeting every last Wednesday of the
month.
The best way to stay posted is through our mailing list. Sign up
([[https://mailb.org/mailman/listinfo/emacs-berlin]]) and meet your
fellow Emacsers, or have a look at the mailing list archives
([[https://mailb.org/pipermail/emacs-berlin/]]) (gmane).
Feel free to send an email introducing yourself after subscribing!
You can also chat with us on irc: #emacs-berlin (connection instructions
([[https://mailb.org/pipermail/emacs-berlin/2020/000583.html]]))
Or on Twitter: @emacsberlin ([[https://twitter.com/emacsberlin]])
And there's a YouTube Channel
([[https://www.youtube.com/channel/UC1O8700SW-wuC4fvDEoGzOw]])  
And
on [[http://meetup.com/Emacs-Berlin-Meetup][meetup.com/Emacs-Berlin-Meetup]]
([[https://www.meetup.com/Emacs-Berlin-Meetup/]])
Non-public contact via email: organizers email
(mailto:[[mailto:emacs-berlin-owner@emacs-berlin.org][emacs-berlin-owner@emacs-berlin.org]])


* EmacsATX: TBD
:PROPERTIES:
:LOCATION: https://www.meetup.com/EmacsATX/events/hkckgsyccpbfb/
:END:
<2021-11-03 Wed 18:30>--<2021-11-03 Wed 20:30>

EmacsATX Wednesday, November 3 at 6:30 PM About Emacs ATX is a meetup
devoted to exploring the vast and ever expanding universe of the
extensible, customizable, free/libre editor Emacs. We are...
https://www.meetup.com/EmacsATX/events/hkckgsyccpbfb/


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2021-11-04 Thu 10:00>--<2021-11-04 Thu 11:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2021-11-19 Fri 09:00>--<2021-11-19 Fri 10:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* Emacs Berlin (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-berlin.org/
:END:
<2021-11-24 Wed 11:30>--<2021-11-24 Wed 13:30>

[[https://emacs-berlin.org/]] 

New to Emacs? Longtime elisp expert? Just want to know what this is all
about? Come join us!

Location

Room open from 18:30 CET, if there are talks they'll start at 19:00 CET.
The video link will be posted on the day of the meetup to the mailing
list. Check the archive
([[https://mailb.org/pipermail/emacs-berlin/2021/thread.html]]) if you
are not subscribed.

About Emacs Berlin
We are Emacs enthusiasts in Berlin, meeting every last Wednesday of the
month.
The best way to stay posted is through our mailing list. Sign up
([[https://mailb.org/mailman/listinfo/emacs-berlin]]) and meet your
fellow Emacsers, or have a look at the mailing list archives
([[https://mailb.org/pipermail/emacs-berlin/]]) (gmane).
Feel free to send an email introducing yourself after subscribing!
You can also chat with us on irc: #emacs-berlin (connection instructions
([[https://mailb.org/pipermail/emacs-berlin/2020/000583.html]]))
Or on Twitter: @emacsberlin ([[https://twitter.com/emacsberlin]])
And there's a YouTube Channel
([[https://www.youtube.com/channel/UC1O8700SW-wuC4fvDEoGzOw]])  
And
on [[http://meetup.com/Emacs-Berlin-Meetup][meetup.com/Emacs-Berlin-Meetup]]
([[https://www.meetup.com/Emacs-Berlin-Meetup/]])
Non-public contact via email: organizers email
(mailto:[[mailto:emacs-berlin-owner@emacs-berlin.org][emacs-berlin-owner@emacs-berlin.org]])


* Emacs APAC (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-apac.gitlab.io/
:END:
<2021-11-27 Sat 02:30>--<2021-11-27 Sat 04:30>

We are Emacs enthusiasts who live in the Asia-Pacific (APAC) time-zone.
We meet every fourth Saturday of the month.

** Where
   :PROPERTIES:
   :CUSTOM_ID: where
   :END:

The event is scheduled virtually using Jitsi Meet at 1400 Indian
Standard Time (IST). The meeting URL is posted on Freenode IRC
channels =#emacs=, =#ilugc= and =#emacsconf=, 30 minutes prior to the
meeting, and also on the [[https://www.freelists.org/list/ilugc][ILUGC
mailing list]] on the day of the meetup. If you are not subscribed, you
can also check
the [[https://www.freelists.org/archive/ilugc/][archive]].

Checkout the upcoming
meetings [[https://emacs-apac.gitlab.io/#upcoming][here]].

** Talks
   :PROPERTIES:
   :CUSTOM_ID: talks
   :END:

We usually have free flowing discussions around new Emacs packages /
features discovered, issues faced, experiences, usage tips, resources
for further learning etc. These are related to GNU Emacs and its
variants. Sometimes people also share their screens and give demos of
their Emacs setup and use.

If you would like to give a talk (20 minutes maximum), please send an
email to TODO with the details.

** Frequently Asked Questions
   :PROPERTIES:
   :CUSTOM_ID: frequently-asked-questions
   :END:

- *I'm new to Emacs, can / should I join?*
  Yes! You are always welcome. We have participants from different walks
  of life with varied experiences in Emacs. You can ask your questions
  and the attendees will be able to help, at least point you in the
  right direction.

- *Which language is used for communication?*
  English.

- *I'm not from APAC, can I join?*
  Definitely! If the timing is suitable for you, please join.




* EmacsATX: TBD
:PROPERTIES:
:LOCATION: https://www.meetup.com/EmacsATX/events/hkckgsyccqbcb/
:END:
<2021-12-01 Wed 18:30>--<2021-12-01 Wed 20:30>

EmacsATX Wednesday, December 1 at 6:30 PM About Emacs ATX is a meetup
devoted to exploring the vast and ever expanding universe of the
extensible, customizable, free/libre editor Emacs. We are...
https://www.meetup.com/EmacsATX/events/hkckgsyccqbcb/


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2021-12-02 Thu 09:00>--<2021-12-02 Thu 10:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2021-12-17 Fri 09:00>--<2021-12-17 Fri 10:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* Emacs APAC (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-apac.gitlab.io/
:END:
<2021-12-25 Sat 02:30>--<2021-12-25 Sat 04:30>

We are Emacs enthusiasts who live in the Asia-Pacific (APAC) time-zone.
We meet every fourth Saturday of the month.

** Where
   :PROPERTIES:
   :CUSTOM_ID: where
   :END:

The event is scheduled virtually using Jitsi Meet at 1400 Indian
Standard Time (IST). The meeting URL is posted on Freenode IRC
channels =#emacs=, =#ilugc= and =#emacsconf=, 30 minutes prior to the
meeting, and also on the [[https://www.freelists.org/list/ilugc][ILUGC
mailing list]] on the day of the meetup. If you are not subscribed, you
can also check
the [[https://www.freelists.org/archive/ilugc/][archive]].

Checkout the upcoming
meetings [[https://emacs-apac.gitlab.io/#upcoming][here]].

** Talks
   :PROPERTIES:
   :CUSTOM_ID: talks
   :END:

We usually have free flowing discussions around new Emacs packages /
features discovered, issues faced, experiences, usage tips, resources
for further learning etc. These are related to GNU Emacs and its
variants. Sometimes people also share their screens and give demos of
their Emacs setup and use.

If you would like to give a talk (20 minutes maximum), please send an
email to TODO with the details.

** Frequently Asked Questions
   :PROPERTIES:
   :CUSTOM_ID: frequently-asked-questions
   :END:

- *I'm new to Emacs, can / should I join?*
  Yes! You are always welcome. We have participants from different walks
  of life with varied experiences in Emacs. You can ask your questions
  and the attendees will be able to help, at least point you in the
  right direction.

- *Which language is used for communication?*
  English.

- *I'm not from APAC, can I join?*
  Definitely! If the timing is suitable for you, please join.




* Emacs Berlin (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-berlin.org/
:END:
<2021-12-29 Wed 11:30>--<2021-12-29 Wed 13:30>

[[https://emacs-berlin.org/]] 

New to Emacs? Longtime elisp expert? Just want to know what this is all
about? Come join us!

Location

Room open from 18:30 CET, if there are talks they'll start at 19:00 CET.
The video link will be posted on the day of the meetup to the mailing
list. Check the archive
([[https://mailb.org/pipermail/emacs-berlin/2021/thread.html]]) if you
are not subscribed.

About Emacs Berlin
We are Emacs enthusiasts in Berlin, meeting every last Wednesday of the
month.
The best way to stay posted is through our mailing list. Sign up
([[https://mailb.org/mailman/listinfo/emacs-berlin]]) and meet your
fellow Emacsers, or have a look at the mailing list archives
([[https://mailb.org/pipermail/emacs-berlin/]]) (gmane).
Feel free to send an email introducing yourself after subscribing!
You can also chat with us on irc: #emacs-berlin (connection instructions
([[https://mailb.org/pipermail/emacs-berlin/2020/000583.html]]))
Or on Twitter: @emacsberlin ([[https://twitter.com/emacsberlin]])
And there's a YouTube Channel
([[https://www.youtube.com/channel/UC1O8700SW-wuC4fvDEoGzOw]])  
And
on [[http://meetup.com/Emacs-Berlin-Meetup][meetup.com/Emacs-Berlin-Meetup]]
([[https://www.meetup.com/Emacs-Berlin-Meetup/]])
Non-public contact via email: organizers email
(mailto:[[mailto:emacs-berlin-owner@emacs-berlin.org][emacs-berlin-owner@emacs-berlin.org]])


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-01-06 Thu 09:00>--<2022-01-06 Thu 10:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-01-21 Fri 09:00>--<2022-01-21 Fri 10:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* Emacs APAC (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-apac.gitlab.io/
:END:
<2022-01-22 Sat 02:30>--<2022-01-22 Sat 04:30>

We are Emacs enthusiasts who live in the Asia-Pacific (APAC) time-zone.
We meet every fourth Saturday of the month.

** Where
   :PROPERTIES:
   :CUSTOM_ID: where
   :END:

The event is scheduled virtually using Jitsi Meet at 1400 Indian
Standard Time (IST). The meeting URL is posted on Freenode IRC
channels =#emacs=, =#ilugc= and =#emacsconf=, 30 minutes prior to the
meeting, and also on the [[https://www.freelists.org/list/ilugc][ILUGC
mailing list]] on the day of the meetup. If you are not subscribed, you
can also check
the [[https://www.freelists.org/archive/ilugc/][archive]].

Checkout the upcoming
meetings [[https://emacs-apac.gitlab.io/#upcoming][here]].

** Talks
   :PROPERTIES:
   :CUSTOM_ID: talks
   :END:

We usually have free flowing discussions around new Emacs packages /
features discovered, issues faced, experiences, usage tips, resources
for further learning etc. These are related to GNU Emacs and its
variants. Sometimes people also share their screens and give demos of
their Emacs setup and use.

If you would like to give a talk (20 minutes maximum), please send an
email to TODO with the details.

** Frequently Asked Questions
   :PROPERTIES:
   :CUSTOM_ID: frequently-asked-questions
   :END:

- *I'm new to Emacs, can / should I join?*
  Yes! You are always welcome. We have participants from different walks
  of life with varied experiences in Emacs. You can ask your questions
  and the attendees will be able to help, at least point you in the
  right direction.

- *Which language is used for communication?*
  English.

- *I'm not from APAC, can I join?*
  Definitely! If the timing is suitable for you, please join.




* Emacs Berlin (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-berlin.org/
:END:
<2022-01-26 Wed 11:30>--<2022-01-26 Wed 13:30>

[[https://emacs-berlin.org/]] 

New to Emacs? Longtime elisp expert? Just want to know what this is all
about? Come join us!

Location

Room open from 18:30 CET, if there are talks they'll start at 19:00 CET.
The video link will be posted on the day of the meetup to the mailing
list. Check the archive
([[https://mailb.org/pipermail/emacs-berlin/2021/thread.html]]) if you
are not subscribed.

About Emacs Berlin
We are Emacs enthusiasts in Berlin, meeting every last Wednesday of the
month.
The best way to stay posted is through our mailing list. Sign up
([[https://mailb.org/mailman/listinfo/emacs-berlin]]) and meet your
fellow Emacsers, or have a look at the mailing list archives
([[https://mailb.org/pipermail/emacs-berlin/]]) (gmane).
Feel free to send an email introducing yourself after subscribing!
You can also chat with us on irc: #emacs-berlin (connection instructions
([[https://mailb.org/pipermail/emacs-berlin/2020/000583.html]]))
Or on Twitter: @emacsberlin ([[https://twitter.com/emacsberlin]])
And there's a YouTube Channel
([[https://www.youtube.com/channel/UC1O8700SW-wuC4fvDEoGzOw]])  
And
on [[http://meetup.com/Emacs-Berlin-Meetup][meetup.com/Emacs-Berlin-Meetup]]
([[https://www.meetup.com/Emacs-Berlin-Meetup/]])
Non-public contact via email: organizers email
(mailto:[[mailto:emacs-berlin-owner@emacs-berlin.org][emacs-berlin-owner@emacs-berlin.org]])


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-02-03 Thu 09:00>--<2022-02-03 Thu 10:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-02-18 Fri 09:00>--<2022-02-18 Fri 10:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* Emacs Berlin (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-berlin.org/
:END:
<2022-02-23 Wed 11:30>--<2022-02-23 Wed 13:30>

[[https://emacs-berlin.org/]] 

New to Emacs? Longtime elisp expert? Just want to know what this is all
about? Come join us!

Location

Room open from 18:30 CET, if there are talks they'll start at 19:00 CET.
The video link will be posted on the day of the meetup to the mailing
list. Check the archive
([[https://mailb.org/pipermail/emacs-berlin/2021/thread.html]]) if you
are not subscribed.

About Emacs Berlin
We are Emacs enthusiasts in Berlin, meeting every last Wednesday of the
month.
The best way to stay posted is through our mailing list. Sign up
([[https://mailb.org/mailman/listinfo/emacs-berlin]]) and meet your
fellow Emacsers, or have a look at the mailing list archives
([[https://mailb.org/pipermail/emacs-berlin/]]) (gmane).
Feel free to send an email introducing yourself after subscribing!
You can also chat with us on irc: #emacs-berlin (connection instructions
([[https://mailb.org/pipermail/emacs-berlin/2020/000583.html]]))
Or on Twitter: @emacsberlin ([[https://twitter.com/emacsberlin]])
And there's a YouTube Channel
([[https://www.youtube.com/channel/UC1O8700SW-wuC4fvDEoGzOw]])  
And
on [[http://meetup.com/Emacs-Berlin-Meetup][meetup.com/Emacs-Berlin-Meetup]]
([[https://www.meetup.com/Emacs-Berlin-Meetup/]])
Non-public contact via email: organizers email
(mailto:[[mailto:emacs-berlin-owner@emacs-berlin.org][emacs-berlin-owner@emacs-berlin.org]])


* Emacs APAC (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-apac.gitlab.io/
:END:
<2022-02-26 Sat 02:30>--<2022-02-26 Sat 04:30>

We are Emacs enthusiasts who live in the Asia-Pacific (APAC) time-zone.
We meet every fourth Saturday of the month.

** Where
   :PROPERTIES:
   :CUSTOM_ID: where
   :END:

The event is scheduled virtually using Jitsi Meet at 1400 Indian
Standard Time (IST). The meeting URL is posted on Freenode IRC
channels =#emacs=, =#ilugc= and =#emacsconf=, 30 minutes prior to the
meeting, and also on the [[https://www.freelists.org/list/ilugc][ILUGC
mailing list]] on the day of the meetup. If you are not subscribed, you
can also check
the [[https://www.freelists.org/archive/ilugc/][archive]].

Checkout the upcoming
meetings [[https://emacs-apac.gitlab.io/#upcoming][here]].

** Talks
   :PROPERTIES:
   :CUSTOM_ID: talks
   :END:

We usually have free flowing discussions around new Emacs packages /
features discovered, issues faced, experiences, usage tips, resources
for further learning etc. These are related to GNU Emacs and its
variants. Sometimes people also share their screens and give demos of
their Emacs setup and use.

If you would like to give a talk (20 minutes maximum), please send an
email to TODO with the details.

** Frequently Asked Questions
   :PROPERTIES:
   :CUSTOM_ID: frequently-asked-questions
   :END:

- *I'm new to Emacs, can / should I join?*
  Yes! You are always welcome. We have participants from different walks
  of life with varied experiences in Emacs. You can ask your questions
  and the attendees will be able to help, at least point you in the
  right direction.

- *Which language is used for communication?*
  English.

- *I'm not from APAC, can I join?*
  Definitely! If the timing is suitable for you, please join.




* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-03-03 Thu 09:00>--<2022-03-03 Thu 10:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-03-18 Fri 10:00>--<2022-03-18 Fri 11:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* Emacs APAC (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-apac.gitlab.io/
:END:
<2022-03-26 Sat 03:30>--<2022-03-26 Sat 05:30>

We are Emacs enthusiasts who live in the Asia-Pacific (APAC) time-zone.
We meet every fourth Saturday of the month.

** Where
   :PROPERTIES:
   :CUSTOM_ID: where
   :END:

The event is scheduled virtually using Jitsi Meet at 1400 Indian
Standard Time (IST). The meeting URL is posted on Freenode IRC
channels =#emacs=, =#ilugc= and =#emacsconf=, 30 minutes prior to the
meeting, and also on the [[https://www.freelists.org/list/ilugc][ILUGC
mailing list]] on the day of the meetup. If you are not subscribed, you
can also check
the [[https://www.freelists.org/archive/ilugc/][archive]].

Checkout the upcoming
meetings [[https://emacs-apac.gitlab.io/#upcoming][here]].

** Talks
   :PROPERTIES:
   :CUSTOM_ID: talks
   :END:

We usually have free flowing discussions around new Emacs packages /
features discovered, issues faced, experiences, usage tips, resources
for further learning etc. These are related to GNU Emacs and its
variants. Sometimes people also share their screens and give demos of
their Emacs setup and use.

If you would like to give a talk (20 minutes maximum), please send an
email to TODO with the details.

** Frequently Asked Questions
   :PROPERTIES:
   :CUSTOM_ID: frequently-asked-questions
   :END:

- *I'm new to Emacs, can / should I join?*
  Yes! You are always welcome. We have participants from different walks
  of life with varied experiences in Emacs. You can ask your questions
  and the attendees will be able to help, at least point you in the
  right direction.

- *Which language is used for communication?*
  English.

- *I'm not from APAC, can I join?*
  Definitely! If the timing is suitable for you, please join.




* Emacs Berlin (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-berlin.org/
:END:
<2022-03-30 Wed 11:30>--<2022-03-30 Wed 13:30>

[[https://emacs-berlin.org/]] 

New to Emacs? Longtime elisp expert? Just want to know what this is all
about? Come join us!

Location

Room open from 18:30 CET, if there are talks they'll start at 19:00 CET.
The video link will be posted on the day of the meetup to the mailing
list. Check the archive
([[https://mailb.org/pipermail/emacs-berlin/2021/thread.html]]) if you
are not subscribed.

About Emacs Berlin
We are Emacs enthusiasts in Berlin, meeting every last Wednesday of the
month.
The best way to stay posted is through our mailing list. Sign up
([[https://mailb.org/mailman/listinfo/emacs-berlin]]) and meet your
fellow Emacsers, or have a look at the mailing list archives
([[https://mailb.org/pipermail/emacs-berlin/]]) (gmane).
Feel free to send an email introducing yourself after subscribing!
You can also chat with us on irc: #emacs-berlin (connection instructions
([[https://mailb.org/pipermail/emacs-berlin/2020/000583.html]]))
Or on Twitter: @emacsberlin ([[https://twitter.com/emacsberlin]])
And there's a YouTube Channel
([[https://www.youtube.com/channel/UC1O8700SW-wuC4fvDEoGzOw]])  
And
on [[http://meetup.com/Emacs-Berlin-Meetup][meetup.com/Emacs-Berlin-Meetup]]
([[https://www.meetup.com/Emacs-Berlin-Meetup/]])
Non-public contact via email: organizers email
(mailto:[[mailto:emacs-berlin-owner@emacs-berlin.org][emacs-berlin-owner@emacs-berlin.org]])


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-04-07 Thu 09:00>--<2022-04-07 Thu 10:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-04-15 Fri 09:00>--<2022-04-15 Fri 10:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* Emacs APAC (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-apac.gitlab.io/
:END:
<2022-04-23 Sat 03:30>--<2022-04-23 Sat 05:30>

We are Emacs enthusiasts who live in the Asia-Pacific (APAC) time-zone.
We meet every fourth Saturday of the month.

** Where
   :PROPERTIES:
   :CUSTOM_ID: where
   :END:

The event is scheduled virtually using Jitsi Meet at 1400 Indian
Standard Time (IST). The meeting URL is posted on Freenode IRC
channels =#emacs=, =#ilugc= and =#emacsconf=, 30 minutes prior to the
meeting, and also on the [[https://www.freelists.org/list/ilugc][ILUGC
mailing list]] on the day of the meetup. If you are not subscribed, you
can also check
the [[https://www.freelists.org/archive/ilugc/][archive]].

Checkout the upcoming
meetings [[https://emacs-apac.gitlab.io/#upcoming][here]].

** Talks
   :PROPERTIES:
   :CUSTOM_ID: talks
   :END:

We usually have free flowing discussions around new Emacs packages /
features discovered, issues faced, experiences, usage tips, resources
for further learning etc. These are related to GNU Emacs and its
variants. Sometimes people also share their screens and give demos of
their Emacs setup and use.

If you would like to give a talk (20 minutes maximum), please send an
email to TODO with the details.

** Frequently Asked Questions
   :PROPERTIES:
   :CUSTOM_ID: frequently-asked-questions
   :END:

- *I'm new to Emacs, can / should I join?*
  Yes! You are always welcome. We have participants from different walks
  of life with varied experiences in Emacs. You can ask your questions
  and the attendees will be able to help, at least point you in the
  right direction.

- *Which language is used for communication?*
  English.

- *I'm not from APAC, can I join?*
  Definitely! If the timing is suitable for you, please join.




* Emacs Berlin (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-berlin.org/
:END:
<2022-04-27 Wed 11:30>--<2022-04-27 Wed 13:30>

[[https://emacs-berlin.org/]] 

New to Emacs? Longtime elisp expert? Just want to know what this is all
about? Come join us!

Location

Room open from 18:30 CET, if there are talks they'll start at 19:00 CET.
The video link will be posted on the day of the meetup to the mailing
list. Check the archive
([[https://mailb.org/pipermail/emacs-berlin/2021/thread.html]]) if you
are not subscribed.

About Emacs Berlin
We are Emacs enthusiasts in Berlin, meeting every last Wednesday of the
month.
The best way to stay posted is through our mailing list. Sign up
([[https://mailb.org/mailman/listinfo/emacs-berlin]]) and meet your
fellow Emacsers, or have a look at the mailing list archives
([[https://mailb.org/pipermail/emacs-berlin/]]) (gmane).
Feel free to send an email introducing yourself after subscribing!
You can also chat with us on irc: #emacs-berlin (connection instructions
([[https://mailb.org/pipermail/emacs-berlin/2020/000583.html]]))
Or on Twitter: @emacsberlin ([[https://twitter.com/emacsberlin]])
And there's a YouTube Channel
([[https://www.youtube.com/channel/UC1O8700SW-wuC4fvDEoGzOw]])  
And
on [[http://meetup.com/Emacs-Berlin-Meetup][meetup.com/Emacs-Berlin-Meetup]]
([[https://www.meetup.com/Emacs-Berlin-Meetup/]])
Non-public contact via email: organizers email
(mailto:[[mailto:emacs-berlin-owner@emacs-berlin.org][emacs-berlin-owner@emacs-berlin.org]])


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-05-05 Thu 09:00>--<2022-05-05 Thu 10:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-05-20 Fri 09:00>--<2022-05-20 Fri 10:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* Emacs Berlin (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-berlin.org/
:END:
<2022-05-25 Wed 11:30>--<2022-05-25 Wed 13:30>

[[https://emacs-berlin.org/]] 

New to Emacs? Longtime elisp expert? Just want to know what this is all
about? Come join us!

Location

Room open from 18:30 CET, if there are talks they'll start at 19:00 CET.
The video link will be posted on the day of the meetup to the mailing
list. Check the archive
([[https://mailb.org/pipermail/emacs-berlin/2021/thread.html]]) if you
are not subscribed.

About Emacs Berlin
We are Emacs enthusiasts in Berlin, meeting every last Wednesday of the
month.
The best way to stay posted is through our mailing list. Sign up
([[https://mailb.org/mailman/listinfo/emacs-berlin]]) and meet your
fellow Emacsers, or have a look at the mailing list archives
([[https://mailb.org/pipermail/emacs-berlin/]]) (gmane).
Feel free to send an email introducing yourself after subscribing!
You can also chat with us on irc: #emacs-berlin (connection instructions
([[https://mailb.org/pipermail/emacs-berlin/2020/000583.html]]))
Or on Twitter: @emacsberlin ([[https://twitter.com/emacsberlin]])
And there's a YouTube Channel
([[https://www.youtube.com/channel/UC1O8700SW-wuC4fvDEoGzOw]])  
And
on [[http://meetup.com/Emacs-Berlin-Meetup][meetup.com/Emacs-Berlin-Meetup]]
([[https://www.meetup.com/Emacs-Berlin-Meetup/]])
Non-public contact via email: organizers email
(mailto:[[mailto:emacs-berlin-owner@emacs-berlin.org][emacs-berlin-owner@emacs-berlin.org]])


* Emacs APAC (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-apac.gitlab.io/
:END:
<2022-05-28 Sat 03:30>--<2022-05-28 Sat 05:30>

We are Emacs enthusiasts who live in the Asia-Pacific (APAC) time-zone.
We meet every fourth Saturday of the month.

** Where
   :PROPERTIES:
   :CUSTOM_ID: where
   :END:

The event is scheduled virtually using Jitsi Meet at 1400 Indian
Standard Time (IST). The meeting URL is posted on Freenode IRC
channels =#emacs=, =#ilugc= and =#emacsconf=, 30 minutes prior to the
meeting, and also on the [[https://www.freelists.org/list/ilugc][ILUGC
mailing list]] on the day of the meetup. If you are not subscribed, you
can also check
the [[https://www.freelists.org/archive/ilugc/][archive]].

Checkout the upcoming
meetings [[https://emacs-apac.gitlab.io/#upcoming][here]].

** Talks
   :PROPERTIES:
   :CUSTOM_ID: talks
   :END:

We usually have free flowing discussions around new Emacs packages /
features discovered, issues faced, experiences, usage tips, resources
for further learning etc. These are related to GNU Emacs and its
variants. Sometimes people also share their screens and give demos of
their Emacs setup and use.

If you would like to give a talk (20 minutes maximum), please send an
email to TODO with the details.

** Frequently Asked Questions
   :PROPERTIES:
   :CUSTOM_ID: frequently-asked-questions
   :END:

- *I'm new to Emacs, can / should I join?*
  Yes! You are always welcome. We have participants from different walks
  of life with varied experiences in Emacs. You can ask your questions
  and the attendees will be able to help, at least point you in the
  right direction.

- *Which language is used for communication?*
  English.

- *I'm not from APAC, can I join?*
  Definitely! If the timing is suitable for you, please join.




* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-06-02 Thu 09:00>--<2022-06-02 Thu 10:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-06-17 Fri 09:00>--<2022-06-17 Fri 10:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* Emacs APAC (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-apac.gitlab.io/
:END:
<2022-06-25 Sat 03:30>--<2022-06-25 Sat 05:30>

We are Emacs enthusiasts who live in the Asia-Pacific (APAC) time-zone.
We meet every fourth Saturday of the month.

** Where
   :PROPERTIES:
   :CUSTOM_ID: where
   :END:

The event is scheduled virtually using Jitsi Meet at 1400 Indian
Standard Time (IST). The meeting URL is posted on Freenode IRC
channels =#emacs=, =#ilugc= and =#emacsconf=, 30 minutes prior to the
meeting, and also on the [[https://www.freelists.org/list/ilugc][ILUGC
mailing list]] on the day of the meetup. If you are not subscribed, you
can also check
the [[https://www.freelists.org/archive/ilugc/][archive]].

Checkout the upcoming
meetings [[https://emacs-apac.gitlab.io/#upcoming][here]].

** Talks
   :PROPERTIES:
   :CUSTOM_ID: talks
   :END:

We usually have free flowing discussions around new Emacs packages /
features discovered, issues faced, experiences, usage tips, resources
for further learning etc. These are related to GNU Emacs and its
variants. Sometimes people also share their screens and give demos of
their Emacs setup and use.

If you would like to give a talk (20 minutes maximum), please send an
email to TODO with the details.

** Frequently Asked Questions
   :PROPERTIES:
   :CUSTOM_ID: frequently-asked-questions
   :END:

- *I'm new to Emacs, can / should I join?*
  Yes! You are always welcome. We have participants from different walks
  of life with varied experiences in Emacs. You can ask your questions
  and the attendees will be able to help, at least point you in the
  right direction.

- *Which language is used for communication?*
  English.

- *I'm not from APAC, can I join?*
  Definitely! If the timing is suitable for you, please join.




* Emacs Berlin (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-berlin.org/
:END:
<2022-06-29 Wed 11:30>--<2022-06-29 Wed 13:30>

[[https://emacs-berlin.org/]] 

New to Emacs? Longtime elisp expert? Just want to know what this is all
about? Come join us!

Location

Room open from 18:30 CET, if there are talks they'll start at 19:00 CET.
The video link will be posted on the day of the meetup to the mailing
list. Check the archive
([[https://mailb.org/pipermail/emacs-berlin/2021/thread.html]]) if you
are not subscribed.

About Emacs Berlin
We are Emacs enthusiasts in Berlin, meeting every last Wednesday of the
month.
The best way to stay posted is through our mailing list. Sign up
([[https://mailb.org/mailman/listinfo/emacs-berlin]]) and meet your
fellow Emacsers, or have a look at the mailing list archives
([[https://mailb.org/pipermail/emacs-berlin/]]) (gmane).
Feel free to send an email introducing yourself after subscribing!
You can also chat with us on irc: #emacs-berlin (connection instructions
([[https://mailb.org/pipermail/emacs-berlin/2020/000583.html]]))
Or on Twitter: @emacsberlin ([[https://twitter.com/emacsberlin]])
And there's a YouTube Channel
([[https://www.youtube.com/channel/UC1O8700SW-wuC4fvDEoGzOw]])  
And
on [[http://meetup.com/Emacs-Berlin-Meetup][meetup.com/Emacs-Berlin-Meetup]]
([[https://www.meetup.com/Emacs-Berlin-Meetup/]])
Non-public contact via email: organizers email
(mailto:[[mailto:emacs-berlin-owner@emacs-berlin.org][emacs-berlin-owner@emacs-berlin.org]])


