* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2021-04-01 Thu 14:00>--<2021-04-01 Thu 15:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* Emacs Paris (virtual)
:PROPERTIES:
:LOCATION: https://www.emacs-doctor.com/emacs-paris-user-group/
:END:
<2021-04-06 Tue 15:30>--<2021-04-06 Tue 17:00>

[[https://www.emacs-doctor.com/emacs-paris-user-group/]] 


Nous sommes quelques utilisateurs
de [[https://www.gnu.org/software/emacs/][GNU Emacs]] à nous réunir
à *Paris* et à *Montpellier* pour apprendre les uns des autres : c'est
ouvert aux non-emacsiens, aux débutants, aux utilisateurs avancés et aux
vimistes !

** Liste de discussion et forum
   :PROPERTIES:
   :CUSTOM_ID: liste-de-discussion-et-forum
   :END:

Vous pouvez vous inscrire
sur [[https://emacs-doctor.com/lists/listinfo/ateliers-paris][la liste
de discussion]].

Nous avons aussi un [[https://emacs-doctor.com/forum/][forum]],
n'hésitez pas à échanger.

** Prochaines rencontres
   :PROPERTIES:
   :CUSTOM_ID: prochaines-rencontres
   :END:

- Paris : mardi 8 décembre 2020 de 17h30 à 19h en visio
- Paris : jeudi 7 janvier 2021 de 17h30 à 19h en visio
- Paris : mardi 2 février 2021 de 17h30 à 19h en visio
- Paris : jeudi 4 mars 2021 de 17h30 à 19h en visio
- Paris : mardi 6 avril 2021 de 17h30 à 19h en visio
- Paris : jeudi 6 mai 2021 de 17h30 à 19h en visio
- Paris : mardi 1 juin 2021 de 17h30 à 19h en visio
- Montpellier : à définir



** Comment je m'inscris à un atelier ?
   :PROPERTIES:
   :CUSTOM_ID: comment-je-minscris-à-un-atelier
   :END:

*** Pour Paris
    :PROPERTIES:
    :CUSTOM_ID: pour-paris
    :END:

Nous faisons des rencontres en ligne. Il y a parfois des rencontres
physiques chez [[http://inno3.fr/][inno3.fr]] au 137 Boulevard de
Magenta 75010 Paris
([[http://www.openstreetmap.org/#map=16/48.8818/2.3514][plan]]) de 19h à
22h.

Si vous venez pour la première fois à un atelier IRL, envoyez un mot
à =bzg@bzg.fr=. Pour la visio, vous pouvez simplement débarquer.

*** Pour Montpellier
    :PROPERTIES:
    :CUSTOM_ID: pour-montpellier
    :END:

Envoyez un petit mot à =emacsem-owner@movoscope.org= et vous serez
inscrit.

** Rencontres passées
   :PROPERTIES:
   :CUSTOM_ID: rencontres-passées
   :END:

Nous gardons parfois des notes des soirées passées
sur [[https://gitlab.com/bzg2/emacsparis/blob/master/README.org][ce
dépôt]].




* Emacs Org mode features you may not know
:PROPERTIES:
:LOCATION: https://pretalx.linuxtage.at/glt21/talk/ZKEXNW/
:END:
<2021-04-10 Sat 15:00>--<2021-04-10 Sat 15:40>

[[https://pretalx.linuxtage.at/glt21/talk/ZKEXNW/]]
Chat: www.oftc.net #glt21
[[https://karl-voit.at/2021/04/10/GLT21-emacs-org-features/]]
[[https://www.reddit.com/r/emacs/comments/mif3sb/glt21conferencetalk_emacs_org_mode_features_you/]]

Emacs Org mode is huge and might overwhelm some people. Therefore,
helpful features often gets lost in this large amount of documentation.
In this talk, hand-selected tricks are demonstrated that may help the
average Org mode user in her daily life.

--------------

Bastien Guerry
wrote [[https://bzg.fr/en/some-emacs-org-mode-features-you-may-not-know.html/][this
article where he shows nice but rather unknown Org features]]. His
article inspired this talk which is about a selection of those features
and much more here and there. It also covers some general Emacs
features.

For this talk, you should have a minimum level of experience with
GNU/Emacs and Org mode. If not, it might provide some inspiration and
motivation to start with GNU/Emacs. However the talk highlights only
some features and tricks here and there, not providing a general
overview.

You can find the show-notes of the talk, links to external sources and
the [[https://en.wikipedia.org/wiki/Colophon_(publishing)][colophon]] on [[https://karl-voit.at/2021/04/10/GLT21-emacs-org-features/][this
web page]].

Please do send a short
feedback [[https://pretalx.linuxtage.at/glt21/talk/ZKEXNW/feedback/][here]] after
the talk.




* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2021-04-15 Thu 14:00>--<2021-04-15 Thu 15:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* Emacs APAC (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-apac.gitlab.io/
:END:
<2021-04-24 Sat 08:30>--<2021-04-24 Sat 10:30>

We are Emacs enthusiasts who live in the Asia-Pacific (APAC) time-zone.
We meet every fourth Saturday of the month.

** Where
   :PROPERTIES:
   :CUSTOM_ID: where
   :END:

The event is scheduled virtually using Jitsi Meet at 1400 Indian
Standard Time (IST). The meeting URL is posted on Freenode IRC
channels =#emacs=, =#ilugc= and =#emacsconf=, 30 minutes prior to the
meeting, and also on the [[https://www.freelists.org/list/ilugc][ILUGC
mailing list]] on the day of the meetup. If you are not subscribed, you
can also check
the [[https://www.freelists.org/archive/ilugc/][archive]].

Checkout the upcoming
meetings [[https://emacs-apac.gitlab.io/#upcoming][here]].

** Talks
   :PROPERTIES:
   :CUSTOM_ID: talks
   :END:

We usually have free flowing discussions around new Emacs packages /
features discovered, issues faced, experiences, usage tips, resources
for further learning etc. These are related to GNU Emacs and its
variants. Sometimes people also share their screens and give demos of
their Emacs setup and use.

If you would like to give a talk (20 minutes maximum), please send an
email to TODO with the details.

** Frequently Asked Questions
   :PROPERTIES:
   :CUSTOM_ID: frequently-asked-questions
   :END:

- *I'm new to Emacs, can / should I join?*
  Yes! You are always welcome. We have participants from different walks
  of life with varied experiences in Emacs. You can ask your questions
  and the attendees will be able to help, at least point you in the
  right direction.

- *Which language is used for communication?*
  English.

- *I'm not from APAC, can I join?*
  Definitely! If the timing is suitable for you, please join.




* Emacs Berlin (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-berlin.org/
:END:
<2021-04-28 Wed 16:30>--<2021-04-28 Wed 18:30>

[[https://emacs-berlin.org/]] 

New to Emacs? Longtime elisp expert? Just want to know what this is all
about? Come join us!

Location

Room open from 18:30 CET, if there are talks they'll start at 19:00 CET.
The video link will be posted on the day of the meetup to the mailing
list. Check the archive
([[https://mailb.org/pipermail/emacs-berlin/2021/thread.html]]) if you
are not subscribed.

About Emacs Berlin
We are Emacs enthusiasts in Berlin, meeting every last Wednesday of the
month.
The best way to stay posted is through our mailing list. Sign up
([[https://mailb.org/mailman/listinfo/emacs-berlin]]) and meet your
fellow Emacsers, or have a look at the mailing list archives
([[https://mailb.org/pipermail/emacs-berlin/]]) (gmane).
Feel free to send an email introducing yourself after subscribing!
You can also chat with us on irc: #emacs-berlin (connection instructions
([[https://mailb.org/pipermail/emacs-berlin/2020/000583.html]]))
Or on Twitter: @emacsberlin ([[https://twitter.com/emacsberlin]])
And there's a YouTube Channel
([[https://www.youtube.com/channel/UC1O8700SW-wuC4fvDEoGzOw]])  
And
on [[http://meetup.com/Emacs-Berlin-Meetup][meetup.com/Emacs-Berlin-Meetup]]
([[https://www.meetup.com/Emacs-Berlin-Meetup/]])
Non-public contact via email: organizers email
(mailto:[[mailto:emacs-berlin-owner@emacs-berlin.org][emacs-berlin-owner@emacs-berlin.org]])


* Frankfurt: Emacs FFM Meetup! April 2021
:PROPERTIES:
:LOCATION: https://www.meetup.com/emacs-ffm/events/277606530/
:END:
<2021-04-28 Wed 17:00>--<2021-04-28 Wed 19:00>

Emacs FFM Wednesday, April 28 at 7:00 PM This time, let us try Discord
as our video conference platform. You can join the Discord chat **right
now** and say hi! No need to wait until the next...
https://www.meetup.com/emacs-ffm/events/277606530/


* EmacsSF: Emacs Lisp: Foundational Utility Packages
:PROPERTIES:
:LOCATION: https://www.meetup.com/Emacs-SF/events/277722919/
:END:
<2021-04-29 Thu 17:00>--<2021-04-29 Thu 19:00>

Emacs SF Thursday, April 29 at 10:00 AM Kicking off a series of meetups
on deeper elisp topics with a discussion on commonly-used Emacs utility
libraries targeted at coders. We'll cover at l...
https://www.meetup.com/Emacs-SF/events/277722919/


* EmacsNYC: Monthly Online Meetup - Lightning Talks
:PROPERTIES:
:LOCATION: https://www.meetup.com/New-York-Emacs-Meetup/events/277390026/
:END:
<2021-05-03 Mon 23:00>--<2021-05-04 Tue 01:00>

New York Emacs Meetup Monday, May 3 at 7:00 PM Join us online:
https://meet.jit.si/EmacsNYCAnd join us using your favorite IRC client
at #emacsnyc or use https://webchat.freenode.net. This month we...
https://www.meetup.com/New-York-Emacs-Meetup/events/277390026/


* EmacsATX: TBD
:PROPERTIES:
:LOCATION: https://www.meetup.com/EmacsATX/events/hkckgsycchbhb/
:END:
<2021-05-05 Wed 23:30>--<2021-05-06 Thu 01:30>

EmacsATX Wednesday, May 5 at 6:30 PM About Emacs ATX is a meetup devoted
to exploring the vast and ever expanding universe of the extensible,
customizable, free/libre editor Emacs. We are...
https://www.meetup.com/EmacsATX/events/hkckgsycchbhb/


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2021-05-06 Thu 14:00>--<2021-05-06 Thu 15:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* Emacs Paris (virtual)
:PROPERTIES:
:LOCATION: https://www.emacs-doctor.com/emacs-paris-user-group/
:END:
<2021-05-06 Thu 15:30>--<2021-05-06 Thu 17:00>

[[https://www.emacs-doctor.com/emacs-paris-user-group/]] 


Nous sommes quelques utilisateurs
de [[https://www.gnu.org/software/emacs/][GNU Emacs]] à nous réunir
à *Paris* et à *Montpellier* pour apprendre les uns des autres : c'est
ouvert aux non-emacsiens, aux débutants, aux utilisateurs avancés et aux
vimistes !

** Liste de discussion et forum
   :PROPERTIES:
   :CUSTOM_ID: liste-de-discussion-et-forum
   :END:

Vous pouvez vous inscrire
sur [[https://emacs-doctor.com/lists/listinfo/ateliers-paris][la liste
de discussion]].

Nous avons aussi un [[https://emacs-doctor.com/forum/][forum]],
n'hésitez pas à échanger.

** Prochaines rencontres
   :PROPERTIES:
   :CUSTOM_ID: prochaines-rencontres
   :END:

- Paris : mardi 8 décembre 2020 de 17h30 à 19h en visio
- Paris : jeudi 7 janvier 2021 de 17h30 à 19h en visio
- Paris : mardi 2 février 2021 de 17h30 à 19h en visio
- Paris : jeudi 4 mars 2021 de 17h30 à 19h en visio
- Paris : mardi 6 avril 2021 de 17h30 à 19h en visio
- Paris : jeudi 6 mai 2021 de 17h30 à 19h en visio
- Paris : mardi 1 juin 2021 de 17h30 à 19h en visio
- Montpellier : à définir



** Comment je m'inscris à un atelier ?
   :PROPERTIES:
   :CUSTOM_ID: comment-je-minscris-à-un-atelier
   :END:

*** Pour Paris
    :PROPERTIES:
    :CUSTOM_ID: pour-paris
    :END:

Nous faisons des rencontres en ligne. Il y a parfois des rencontres
physiques chez [[http://inno3.fr/][inno3.fr]] au 137 Boulevard de
Magenta 75010 Paris
([[http://www.openstreetmap.org/#map=16/48.8818/2.3514][plan]]) de 19h à
22h.

Si vous venez pour la première fois à un atelier IRL, envoyez un mot
à =bzg@bzg.fr=. Pour la visio, vous pouvez simplement débarquer.

*** Pour Montpellier
    :PROPERTIES:
    :CUSTOM_ID: pour-montpellier
    :END:

Envoyez un petit mot à =emacsem-owner@movoscope.org= et vous serez
inscrit.

** Rencontres passées
   :PROPERTIES:
   :CUSTOM_ID: rencontres-passées
   :END:

Nous gardons parfois des notes des soirées passées
sur [[https://gitlab.com/bzg2/emacsparis/blob/master/README.org][ce
dépôt]].




* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2021-05-20 Thu 14:00>--<2021-05-20 Thu 15:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* Emacs APAC (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-apac.gitlab.io/
:END:
<2021-05-22 Sat 08:30>--<2021-05-22 Sat 10:30>

We are Emacs enthusiasts who live in the Asia-Pacific (APAC) time-zone.
We meet every fourth Saturday of the month.

** Where
   :PROPERTIES:
   :CUSTOM_ID: where
   :END:

The event is scheduled virtually using Jitsi Meet at 1400 Indian
Standard Time (IST). The meeting URL is posted on Freenode IRC
channels =#emacs=, =#ilugc= and =#emacsconf=, 30 minutes prior to the
meeting, and also on the [[https://www.freelists.org/list/ilugc][ILUGC
mailing list]] on the day of the meetup. If you are not subscribed, you
can also check
the [[https://www.freelists.org/archive/ilugc/][archive]].

Checkout the upcoming
meetings [[https://emacs-apac.gitlab.io/#upcoming][here]].

** Talks
   :PROPERTIES:
   :CUSTOM_ID: talks
   :END:

We usually have free flowing discussions around new Emacs packages /
features discovered, issues faced, experiences, usage tips, resources
for further learning etc. These are related to GNU Emacs and its
variants. Sometimes people also share their screens and give demos of
their Emacs setup and use.

If you would like to give a talk (20 minutes maximum), please send an
email to TODO with the details.

** Frequently Asked Questions
   :PROPERTIES:
   :CUSTOM_ID: frequently-asked-questions
   :END:

- *I'm new to Emacs, can / should I join?*
  Yes! You are always welcome. We have participants from different walks
  of life with varied experiences in Emacs. You can ask your questions
  and the attendees will be able to help, at least point you in the
  right direction.

- *Which language is used for communication?*
  English.

- *I'm not from APAC, can I join?*
  Definitely! If the timing is suitable for you, please join.




* Singapore: Emacs & Never Code Alone SG
:PROPERTIES:
:LOCATION: https://www.meetup.com/Emacs-SG/events/268260076/
:END:
<2021-05-26 Wed 11:00>--<2021-05-26 Wed 14:00>

Emacs SG Wednesday, May 26 at 7:00 PM There hasn't been much activity
here for quite a while but hopefully we can bring some Nix along to the
Never Code Alone SG event when Covid allows is...
https://www.meetup.com/Emacs-SG/events/268260076/


* Emacs Berlin (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-berlin.org/
:END:
<2021-05-26 Wed 16:30>--<2021-05-26 Wed 18:30>

[[https://emacs-berlin.org/]] 

New to Emacs? Longtime elisp expert? Just want to know what this is all
about? Come join us!

Location

Room open from 18:30 CET, if there are talks they'll start at 19:00 CET.
The video link will be posted on the day of the meetup to the mailing
list. Check the archive
([[https://mailb.org/pipermail/emacs-berlin/2021/thread.html]]) if you
are not subscribed.

About Emacs Berlin
We are Emacs enthusiasts in Berlin, meeting every last Wednesday of the
month.
The best way to stay posted is through our mailing list. Sign up
([[https://mailb.org/mailman/listinfo/emacs-berlin]]) and meet your
fellow Emacsers, or have a look at the mailing list archives
([[https://mailb.org/pipermail/emacs-berlin/]]) (gmane).
Feel free to send an email introducing yourself after subscribing!
You can also chat with us on irc: #emacs-berlin (connection instructions
([[https://mailb.org/pipermail/emacs-berlin/2020/000583.html]]))
Or on Twitter: @emacsberlin ([[https://twitter.com/emacsberlin]])
And there's a YouTube Channel
([[https://www.youtube.com/channel/UC1O8700SW-wuC4fvDEoGzOw]])  
And
on [[http://meetup.com/Emacs-Berlin-Meetup][meetup.com/Emacs-Berlin-Meetup]]
([[https://www.meetup.com/Emacs-Berlin-Meetup/]])
Non-public contact via email: organizers email
(mailto:[[mailto:emacs-berlin-owner@emacs-berlin.org][emacs-berlin-owner@emacs-berlin.org]])


* Emacs Paris (virtual)
:PROPERTIES:
:LOCATION: https://www.emacs-doctor.com/emacs-paris-user-group/
:END:
<2021-06-01 Tue 15:30>--<2021-06-01 Tue 17:00>

[[https://www.emacs-doctor.com/emacs-paris-user-group/]] 


Nous sommes quelques utilisateurs
de [[https://www.gnu.org/software/emacs/][GNU Emacs]] à nous réunir
à *Paris* et à *Montpellier* pour apprendre les uns des autres : c'est
ouvert aux non-emacsiens, aux débutants, aux utilisateurs avancés et aux
vimistes !

** Liste de discussion et forum
   :PROPERTIES:
   :CUSTOM_ID: liste-de-discussion-et-forum
   :END:

Vous pouvez vous inscrire
sur [[https://emacs-doctor.com/lists/listinfo/ateliers-paris][la liste
de discussion]].

Nous avons aussi un [[https://emacs-doctor.com/forum/][forum]],
n'hésitez pas à échanger.

** Prochaines rencontres
   :PROPERTIES:
   :CUSTOM_ID: prochaines-rencontres
   :END:

- Paris : mardi 8 décembre 2020 de 17h30 à 19h en visio
- Paris : jeudi 7 janvier 2021 de 17h30 à 19h en visio
- Paris : mardi 2 février 2021 de 17h30 à 19h en visio
- Paris : jeudi 4 mars 2021 de 17h30 à 19h en visio
- Paris : mardi 6 avril 2021 de 17h30 à 19h en visio
- Paris : jeudi 6 mai 2021 de 17h30 à 19h en visio
- Paris : mardi 1 juin 2021 de 17h30 à 19h en visio
- Montpellier : à définir



** Comment je m'inscris à un atelier ?
   :PROPERTIES:
   :CUSTOM_ID: comment-je-minscris-à-un-atelier
   :END:

*** Pour Paris
    :PROPERTIES:
    :CUSTOM_ID: pour-paris
    :END:

Nous faisons des rencontres en ligne. Il y a parfois des rencontres
physiques chez [[http://inno3.fr/][inno3.fr]] au 137 Boulevard de
Magenta 75010 Paris
([[http://www.openstreetmap.org/#map=16/48.8818/2.3514][plan]]) de 19h à
22h.

Si vous venez pour la première fois à un atelier IRL, envoyez un mot
à =bzg@bzg.fr=. Pour la visio, vous pouvez simplement débarquer.

*** Pour Montpellier
    :PROPERTIES:
    :CUSTOM_ID: pour-montpellier
    :END:

Envoyez un petit mot à =emacsem-owner@movoscope.org= et vous serez
inscrit.

** Rencontres passées
   :PROPERTIES:
   :CUSTOM_ID: rencontres-passées
   :END:

Nous gardons parfois des notes des soirées passées
sur [[https://gitlab.com/bzg2/emacsparis/blob/master/README.org][ce
dépôt]].




* EmacsATX: TBD
:PROPERTIES:
:LOCATION: https://www.meetup.com/EmacsATX/events/hkckgsyccjbdb/
:END:
<2021-06-02 Wed 23:30>--<2021-06-03 Thu 01:30>

EmacsATX Wednesday, June 2 at 6:30 PM About Emacs ATX is a meetup
devoted to exploring the vast and ever expanding universe of the
extensible, customizable, free/libre editor Emacs. We are...
https://www.meetup.com/EmacsATX/events/hkckgsyccjbdb/


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2021-06-03 Thu 14:00>--<2021-06-03 Thu 15:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2021-06-17 Thu 14:00>--<2021-06-17 Thu 15:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* Emacs APAC (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-apac.gitlab.io/
:END:
<2021-06-26 Sat 08:30>--<2021-06-26 Sat 10:30>

We are Emacs enthusiasts who live in the Asia-Pacific (APAC) time-zone.
We meet every fourth Saturday of the month.

** Where
   :PROPERTIES:
   :CUSTOM_ID: where
   :END:

The event is scheduled virtually using Jitsi Meet at 1400 Indian
Standard Time (IST). The meeting URL is posted on Freenode IRC
channels =#emacs=, =#ilugc= and =#emacsconf=, 30 minutes prior to the
meeting, and also on the [[https://www.freelists.org/list/ilugc][ILUGC
mailing list]] on the day of the meetup. If you are not subscribed, you
can also check
the [[https://www.freelists.org/archive/ilugc/][archive]].

Checkout the upcoming
meetings [[https://emacs-apac.gitlab.io/#upcoming][here]].

** Talks
   :PROPERTIES:
   :CUSTOM_ID: talks
   :END:

We usually have free flowing discussions around new Emacs packages /
features discovered, issues faced, experiences, usage tips, resources
for further learning etc. These are related to GNU Emacs and its
variants. Sometimes people also share their screens and give demos of
their Emacs setup and use.

If you would like to give a talk (20 minutes maximum), please send an
email to TODO with the details.

** Frequently Asked Questions
   :PROPERTIES:
   :CUSTOM_ID: frequently-asked-questions
   :END:

- *I'm new to Emacs, can / should I join?*
  Yes! You are always welcome. We have participants from different walks
  of life with varied experiences in Emacs. You can ask your questions
  and the attendees will be able to help, at least point you in the
  right direction.

- *Which language is used for communication?*
  English.

- *I'm not from APAC, can I join?*
  Definitely! If the timing is suitable for you, please join.




* Emacs Berlin (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-berlin.org/
:END:
<2021-06-30 Wed 16:30>--<2021-06-30 Wed 18:30>

[[https://emacs-berlin.org/]] 

New to Emacs? Longtime elisp expert? Just want to know what this is all
about? Come join us!

Location

Room open from 18:30 CET, if there are talks they'll start at 19:00 CET.
The video link will be posted on the day of the meetup to the mailing
list. Check the archive
([[https://mailb.org/pipermail/emacs-berlin/2021/thread.html]]) if you
are not subscribed.

About Emacs Berlin
We are Emacs enthusiasts in Berlin, meeting every last Wednesday of the
month.
The best way to stay posted is through our mailing list. Sign up
([[https://mailb.org/mailman/listinfo/emacs-berlin]]) and meet your
fellow Emacsers, or have a look at the mailing list archives
([[https://mailb.org/pipermail/emacs-berlin/]]) (gmane).
Feel free to send an email introducing yourself after subscribing!
You can also chat with us on irc: #emacs-berlin (connection instructions
([[https://mailb.org/pipermail/emacs-berlin/2020/000583.html]]))
Or on Twitter: @emacsberlin ([[https://twitter.com/emacsberlin]])
And there's a YouTube Channel
([[https://www.youtube.com/channel/UC1O8700SW-wuC4fvDEoGzOw]])  
And
on [[http://meetup.com/Emacs-Berlin-Meetup][meetup.com/Emacs-Berlin-Meetup]]
([[https://www.meetup.com/Emacs-Berlin-Meetup/]])
Non-public contact via email: organizers email
(mailto:[[mailto:emacs-berlin-owner@emacs-berlin.org][emacs-berlin-owner@emacs-berlin.org]])


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2021-07-01 Thu 14:00>--<2021-07-01 Thu 15:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* EmacsATX: TBD
:PROPERTIES:
:LOCATION: https://www.meetup.com/EmacsATX/events/hkckgsycckbkb/
:END:
<2021-07-07 Wed 23:30>--<2021-07-08 Thu 01:30>

EmacsATX Wednesday, July 7 at 6:30 PM About Emacs ATX is a meetup
devoted to exploring the vast and ever expanding universe of the
extensible, customizable, free/libre editor Emacs. We are...
https://www.meetup.com/EmacsATX/events/hkckgsycckbkb/


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2021-07-15 Thu 14:00>--<2021-07-15 Thu 15:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* Emacs APAC (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-apac.gitlab.io/
:END:
<2021-07-24 Sat 08:30>--<2021-07-24 Sat 10:30>

We are Emacs enthusiasts who live in the Asia-Pacific (APAC) time-zone.
We meet every fourth Saturday of the month.

** Where
   :PROPERTIES:
   :CUSTOM_ID: where
   :END:

The event is scheduled virtually using Jitsi Meet at 1400 Indian
Standard Time (IST). The meeting URL is posted on Freenode IRC
channels =#emacs=, =#ilugc= and =#emacsconf=, 30 minutes prior to the
meeting, and also on the [[https://www.freelists.org/list/ilugc][ILUGC
mailing list]] on the day of the meetup. If you are not subscribed, you
can also check
the [[https://www.freelists.org/archive/ilugc/][archive]].

Checkout the upcoming
meetings [[https://emacs-apac.gitlab.io/#upcoming][here]].

** Talks
   :PROPERTIES:
   :CUSTOM_ID: talks
   :END:

We usually have free flowing discussions around new Emacs packages /
features discovered, issues faced, experiences, usage tips, resources
for further learning etc. These are related to GNU Emacs and its
variants. Sometimes people also share their screens and give demos of
their Emacs setup and use.

If you would like to give a talk (20 minutes maximum), please send an
email to TODO with the details.

** Frequently Asked Questions
   :PROPERTIES:
   :CUSTOM_ID: frequently-asked-questions
   :END:

- *I'm new to Emacs, can / should I join?*
  Yes! You are always welcome. We have participants from different walks
  of life with varied experiences in Emacs. You can ask your questions
  and the attendees will be able to help, at least point you in the
  right direction.

- *Which language is used for communication?*
  English.

- *I'm not from APAC, can I join?*
  Definitely! If the timing is suitable for you, please join.




* Emacs Berlin (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-berlin.org/
:END:
<2021-07-28 Wed 16:30>--<2021-07-28 Wed 18:30>

[[https://emacs-berlin.org/]] 

New to Emacs? Longtime elisp expert? Just want to know what this is all
about? Come join us!

Location

Room open from 18:30 CET, if there are talks they'll start at 19:00 CET.
The video link will be posted on the day of the meetup to the mailing
list. Check the archive
([[https://mailb.org/pipermail/emacs-berlin/2021/thread.html]]) if you
are not subscribed.

About Emacs Berlin
We are Emacs enthusiasts in Berlin, meeting every last Wednesday of the
month.
The best way to stay posted is through our mailing list. Sign up
([[https://mailb.org/mailman/listinfo/emacs-berlin]]) and meet your
fellow Emacsers, or have a look at the mailing list archives
([[https://mailb.org/pipermail/emacs-berlin/]]) (gmane).
Feel free to send an email introducing yourself after subscribing!
You can also chat with us on irc: #emacs-berlin (connection instructions
([[https://mailb.org/pipermail/emacs-berlin/2020/000583.html]]))
Or on Twitter: @emacsberlin ([[https://twitter.com/emacsberlin]])
And there's a YouTube Channel
([[https://www.youtube.com/channel/UC1O8700SW-wuC4fvDEoGzOw]])  
And
on [[http://meetup.com/Emacs-Berlin-Meetup][meetup.com/Emacs-Berlin-Meetup]]
([[https://www.meetup.com/Emacs-Berlin-Meetup/]])
Non-public contact via email: organizers email
(mailto:[[mailto:emacs-berlin-owner@emacs-berlin.org][emacs-berlin-owner@emacs-berlin.org]])


* EmacsATX: TBD
:PROPERTIES:
:LOCATION: https://www.meetup.com/EmacsATX/events/hkckgsycclbgb/
:END:
<2021-08-04 Wed 23:30>--<2021-08-05 Thu 01:30>

EmacsATX Wednesday, August 4 at 6:30 PM About Emacs ATX is a meetup
devoted to exploring the vast and ever expanding universe of the
extensible, customizable, free/libre editor Emacs. We are...
https://www.meetup.com/EmacsATX/events/hkckgsycclbgb/


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2021-08-05 Thu 14:00>--<2021-08-05 Thu 15:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2021-08-19 Thu 14:00>--<2021-08-19 Thu 15:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* Emacs Berlin (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-berlin.org/
:END:
<2021-08-25 Wed 16:30>--<2021-08-25 Wed 18:30>

[[https://emacs-berlin.org/]] 

New to Emacs? Longtime elisp expert? Just want to know what this is all
about? Come join us!

Location

Room open from 18:30 CET, if there are talks they'll start at 19:00 CET.
The video link will be posted on the day of the meetup to the mailing
list. Check the archive
([[https://mailb.org/pipermail/emacs-berlin/2021/thread.html]]) if you
are not subscribed.

About Emacs Berlin
We are Emacs enthusiasts in Berlin, meeting every last Wednesday of the
month.
The best way to stay posted is through our mailing list. Sign up
([[https://mailb.org/mailman/listinfo/emacs-berlin]]) and meet your
fellow Emacsers, or have a look at the mailing list archives
([[https://mailb.org/pipermail/emacs-berlin/]]) (gmane).
Feel free to send an email introducing yourself after subscribing!
You can also chat with us on irc: #emacs-berlin (connection instructions
([[https://mailb.org/pipermail/emacs-berlin/2020/000583.html]]))
Or on Twitter: @emacsberlin ([[https://twitter.com/emacsberlin]])
And there's a YouTube Channel
([[https://www.youtube.com/channel/UC1O8700SW-wuC4fvDEoGzOw]])  
And
on [[http://meetup.com/Emacs-Berlin-Meetup][meetup.com/Emacs-Berlin-Meetup]]
([[https://www.meetup.com/Emacs-Berlin-Meetup/]])
Non-public contact via email: organizers email
(mailto:[[mailto:emacs-berlin-owner@emacs-berlin.org][emacs-berlin-owner@emacs-berlin.org]])


* Emacs APAC (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-apac.gitlab.io/
:END:
<2021-08-28 Sat 08:30>--<2021-08-28 Sat 10:30>

We are Emacs enthusiasts who live in the Asia-Pacific (APAC) time-zone.
We meet every fourth Saturday of the month.

** Where
   :PROPERTIES:
   :CUSTOM_ID: where
   :END:

The event is scheduled virtually using Jitsi Meet at 1400 Indian
Standard Time (IST). The meeting URL is posted on Freenode IRC
channels =#emacs=, =#ilugc= and =#emacsconf=, 30 minutes prior to the
meeting, and also on the [[https://www.freelists.org/list/ilugc][ILUGC
mailing list]] on the day of the meetup. If you are not subscribed, you
can also check
the [[https://www.freelists.org/archive/ilugc/][archive]].

Checkout the upcoming
meetings [[https://emacs-apac.gitlab.io/#upcoming][here]].

** Talks
   :PROPERTIES:
   :CUSTOM_ID: talks
   :END:

We usually have free flowing discussions around new Emacs packages /
features discovered, issues faced, experiences, usage tips, resources
for further learning etc. These are related to GNU Emacs and its
variants. Sometimes people also share their screens and give demos of
their Emacs setup and use.

If you would like to give a talk (20 minutes maximum), please send an
email to TODO with the details.

** Frequently Asked Questions
   :PROPERTIES:
   :CUSTOM_ID: frequently-asked-questions
   :END:

- *I'm new to Emacs, can / should I join?*
  Yes! You are always welcome. We have participants from different walks
  of life with varied experiences in Emacs. You can ask your questions
  and the attendees will be able to help, at least point you in the
  right direction.

- *Which language is used for communication?*
  English.

- *I'm not from APAC, can I join?*
  Definitely! If the timing is suitable for you, please join.




* EmacsATX: TBD
:PROPERTIES:
:LOCATION: https://www.meetup.com/EmacsATX/events/hkckgsyccmbcb/
:END:
<2021-09-01 Wed 23:30>--<2021-09-02 Thu 01:30>

EmacsATX Wednesday, September 1 at 6:30 PM About Emacs ATX is a meetup
devoted to exploring the vast and ever expanding universe of the
extensible, customizable, free/libre editor Emacs. We are...
https://www.meetup.com/EmacsATX/events/hkckgsyccmbcb/


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2021-09-02 Thu 14:00>--<2021-09-02 Thu 15:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2021-09-16 Thu 14:00>--<2021-09-16 Thu 15:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* Emacs APAC (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-apac.gitlab.io/
:END:
<2021-09-25 Sat 08:30>--<2021-09-25 Sat 10:30>

We are Emacs enthusiasts who live in the Asia-Pacific (APAC) time-zone.
We meet every fourth Saturday of the month.

** Where
   :PROPERTIES:
   :CUSTOM_ID: where
   :END:

The event is scheduled virtually using Jitsi Meet at 1400 Indian
Standard Time (IST). The meeting URL is posted on Freenode IRC
channels =#emacs=, =#ilugc= and =#emacsconf=, 30 minutes prior to the
meeting, and also on the [[https://www.freelists.org/list/ilugc][ILUGC
mailing list]] on the day of the meetup. If you are not subscribed, you
can also check
the [[https://www.freelists.org/archive/ilugc/][archive]].

Checkout the upcoming
meetings [[https://emacs-apac.gitlab.io/#upcoming][here]].

** Talks
   :PROPERTIES:
   :CUSTOM_ID: talks
   :END:

We usually have free flowing discussions around new Emacs packages /
features discovered, issues faced, experiences, usage tips, resources
for further learning etc. These are related to GNU Emacs and its
variants. Sometimes people also share their screens and give demos of
their Emacs setup and use.

If you would like to give a talk (20 minutes maximum), please send an
email to TODO with the details.

** Frequently Asked Questions
   :PROPERTIES:
   :CUSTOM_ID: frequently-asked-questions
   :END:

- *I'm new to Emacs, can / should I join?*
  Yes! You are always welcome. We have participants from different walks
  of life with varied experiences in Emacs. You can ask your questions
  and the attendees will be able to help, at least point you in the
  right direction.

- *Which language is used for communication?*
  English.

- *I'm not from APAC, can I join?*
  Definitely! If the timing is suitable for you, please join.




* Emacs Berlin (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-berlin.org/
:END:
<2021-09-29 Wed 16:30>--<2021-09-29 Wed 18:30>

[[https://emacs-berlin.org/]] 

New to Emacs? Longtime elisp expert? Just want to know what this is all
about? Come join us!

Location

Room open from 18:30 CET, if there are talks they'll start at 19:00 CET.
The video link will be posted on the day of the meetup to the mailing
list. Check the archive
([[https://mailb.org/pipermail/emacs-berlin/2021/thread.html]]) if you
are not subscribed.

About Emacs Berlin
We are Emacs enthusiasts in Berlin, meeting every last Wednesday of the
month.
The best way to stay posted is through our mailing list. Sign up
([[https://mailb.org/mailman/listinfo/emacs-berlin]]) and meet your
fellow Emacsers, or have a look at the mailing list archives
([[https://mailb.org/pipermail/emacs-berlin/]]) (gmane).
Feel free to send an email introducing yourself after subscribing!
You can also chat with us on irc: #emacs-berlin (connection instructions
([[https://mailb.org/pipermail/emacs-berlin/2020/000583.html]]))
Or on Twitter: @emacsberlin ([[https://twitter.com/emacsberlin]])
And there's a YouTube Channel
([[https://www.youtube.com/channel/UC1O8700SW-wuC4fvDEoGzOw]])  
And
on [[http://meetup.com/Emacs-Berlin-Meetup][meetup.com/Emacs-Berlin-Meetup]]
([[https://www.meetup.com/Emacs-Berlin-Meetup/]])
Non-public contact via email: organizers email
(mailto:[[mailto:emacs-berlin-owner@emacs-berlin.org][emacs-berlin-owner@emacs-berlin.org]])


* EmacsATX: TBD
:PROPERTIES:
:LOCATION: https://www.meetup.com/EmacsATX/events/hkckgsyccnbjb/
:END:
<2021-10-06 Wed 23:30>--<2021-10-07 Thu 01:30>

EmacsATX Wednesday, October 6 at 6:30 PM About Emacs ATX is a meetup
devoted to exploring the vast and ever expanding universe of the
extensible, customizable, free/libre editor Emacs. We are...
https://www.meetup.com/EmacsATX/events/hkckgsyccnbjb/


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2021-10-07 Thu 14:00>--<2021-10-07 Thu 15:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2021-10-21 Thu 14:00>--<2021-10-21 Thu 15:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* Emacs APAC (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-apac.gitlab.io/
:END:
<2021-10-23 Sat 08:30>--<2021-10-23 Sat 10:30>

We are Emacs enthusiasts who live in the Asia-Pacific (APAC) time-zone.
We meet every fourth Saturday of the month.

** Where
   :PROPERTIES:
   :CUSTOM_ID: where
   :END:

The event is scheduled virtually using Jitsi Meet at 1400 Indian
Standard Time (IST). The meeting URL is posted on Freenode IRC
channels =#emacs=, =#ilugc= and =#emacsconf=, 30 minutes prior to the
meeting, and also on the [[https://www.freelists.org/list/ilugc][ILUGC
mailing list]] on the day of the meetup. If you are not subscribed, you
can also check
the [[https://www.freelists.org/archive/ilugc/][archive]].

Checkout the upcoming
meetings [[https://emacs-apac.gitlab.io/#upcoming][here]].

** Talks
   :PROPERTIES:
   :CUSTOM_ID: talks
   :END:

We usually have free flowing discussions around new Emacs packages /
features discovered, issues faced, experiences, usage tips, resources
for further learning etc. These are related to GNU Emacs and its
variants. Sometimes people also share their screens and give demos of
their Emacs setup and use.

If you would like to give a talk (20 minutes maximum), please send an
email to TODO with the details.

** Frequently Asked Questions
   :PROPERTIES:
   :CUSTOM_ID: frequently-asked-questions
   :END:

- *I'm new to Emacs, can / should I join?*
  Yes! You are always welcome. We have participants from different walks
  of life with varied experiences in Emacs. You can ask your questions
  and the attendees will be able to help, at least point you in the
  right direction.

- *Which language is used for communication?*
  English.

- *I'm not from APAC, can I join?*
  Definitely! If the timing is suitable for you, please join.




* Emacs Berlin (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-berlin.org/
:END:
<2021-10-27 Wed 16:30>--<2021-10-27 Wed 18:30>

[[https://emacs-berlin.org/]] 

New to Emacs? Longtime elisp expert? Just want to know what this is all
about? Come join us!

Location

Room open from 18:30 CET, if there are talks they'll start at 19:00 CET.
The video link will be posted on the day of the meetup to the mailing
list. Check the archive
([[https://mailb.org/pipermail/emacs-berlin/2021/thread.html]]) if you
are not subscribed.

About Emacs Berlin
We are Emacs enthusiasts in Berlin, meeting every last Wednesday of the
month.
The best way to stay posted is through our mailing list. Sign up
([[https://mailb.org/mailman/listinfo/emacs-berlin]]) and meet your
fellow Emacsers, or have a look at the mailing list archives
([[https://mailb.org/pipermail/emacs-berlin/]]) (gmane).
Feel free to send an email introducing yourself after subscribing!
You can also chat with us on irc: #emacs-berlin (connection instructions
([[https://mailb.org/pipermail/emacs-berlin/2020/000583.html]]))
Or on Twitter: @emacsberlin ([[https://twitter.com/emacsberlin]])
And there's a YouTube Channel
([[https://www.youtube.com/channel/UC1O8700SW-wuC4fvDEoGzOw]])  
And
on [[http://meetup.com/Emacs-Berlin-Meetup][meetup.com/Emacs-Berlin-Meetup]]
([[https://www.meetup.com/Emacs-Berlin-Meetup/]])
Non-public contact via email: organizers email
(mailto:[[mailto:emacs-berlin-owner@emacs-berlin.org][emacs-berlin-owner@emacs-berlin.org]])


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2021-11-04 Thu 15:00>--<2021-11-04 Thu 16:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2021-11-18 Thu 15:00>--<2021-11-18 Thu 16:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* Emacs Berlin (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-berlin.org/
:END:
<2021-11-24 Wed 17:30>--<2021-11-24 Wed 19:30>

[[https://emacs-berlin.org/]] 

New to Emacs? Longtime elisp expert? Just want to know what this is all
about? Come join us!

Location

Room open from 18:30 CET, if there are talks they'll start at 19:00 CET.
The video link will be posted on the day of the meetup to the mailing
list. Check the archive
([[https://mailb.org/pipermail/emacs-berlin/2021/thread.html]]) if you
are not subscribed.

About Emacs Berlin
We are Emacs enthusiasts in Berlin, meeting every last Wednesday of the
month.
The best way to stay posted is through our mailing list. Sign up
([[https://mailb.org/mailman/listinfo/emacs-berlin]]) and meet your
fellow Emacsers, or have a look at the mailing list archives
([[https://mailb.org/pipermail/emacs-berlin/]]) (gmane).
Feel free to send an email introducing yourself after subscribing!
You can also chat with us on irc: #emacs-berlin (connection instructions
([[https://mailb.org/pipermail/emacs-berlin/2020/000583.html]]))
Or on Twitter: @emacsberlin ([[https://twitter.com/emacsberlin]])
And there's a YouTube Channel
([[https://www.youtube.com/channel/UC1O8700SW-wuC4fvDEoGzOw]])  
And
on [[http://meetup.com/Emacs-Berlin-Meetup][meetup.com/Emacs-Berlin-Meetup]]
([[https://www.meetup.com/Emacs-Berlin-Meetup/]])
Non-public contact via email: organizers email
(mailto:[[mailto:emacs-berlin-owner@emacs-berlin.org][emacs-berlin-owner@emacs-berlin.org]])


* Emacs APAC (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-apac.gitlab.io/
:END:
<2021-11-27 Sat 08:30>--<2021-11-27 Sat 10:30>

We are Emacs enthusiasts who live in the Asia-Pacific (APAC) time-zone.
We meet every fourth Saturday of the month.

** Where
   :PROPERTIES:
   :CUSTOM_ID: where
   :END:

The event is scheduled virtually using Jitsi Meet at 1400 Indian
Standard Time (IST). The meeting URL is posted on Freenode IRC
channels =#emacs=, =#ilugc= and =#emacsconf=, 30 minutes prior to the
meeting, and also on the [[https://www.freelists.org/list/ilugc][ILUGC
mailing list]] on the day of the meetup. If you are not subscribed, you
can also check
the [[https://www.freelists.org/archive/ilugc/][archive]].

Checkout the upcoming
meetings [[https://emacs-apac.gitlab.io/#upcoming][here]].

** Talks
   :PROPERTIES:
   :CUSTOM_ID: talks
   :END:

We usually have free flowing discussions around new Emacs packages /
features discovered, issues faced, experiences, usage tips, resources
for further learning etc. These are related to GNU Emacs and its
variants. Sometimes people also share their screens and give demos of
their Emacs setup and use.

If you would like to give a talk (20 minutes maximum), please send an
email to TODO with the details.

** Frequently Asked Questions
   :PROPERTIES:
   :CUSTOM_ID: frequently-asked-questions
   :END:

- *I'm new to Emacs, can / should I join?*
  Yes! You are always welcome. We have participants from different walks
  of life with varied experiences in Emacs. You can ask your questions
  and the attendees will be able to help, at least point you in the
  right direction.

- *Which language is used for communication?*
  English.

- *I'm not from APAC, can I join?*
  Definitely! If the timing is suitable for you, please join.




* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2021-12-02 Thu 15:00>--<2021-12-02 Thu 16:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2021-12-16 Thu 15:00>--<2021-12-16 Thu 16:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* Emacs APAC (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-apac.gitlab.io/
:END:
<2021-12-25 Sat 08:30>--<2021-12-25 Sat 10:30>

We are Emacs enthusiasts who live in the Asia-Pacific (APAC) time-zone.
We meet every fourth Saturday of the month.

** Where
   :PROPERTIES:
   :CUSTOM_ID: where
   :END:

The event is scheduled virtually using Jitsi Meet at 1400 Indian
Standard Time (IST). The meeting URL is posted on Freenode IRC
channels =#emacs=, =#ilugc= and =#emacsconf=, 30 minutes prior to the
meeting, and also on the [[https://www.freelists.org/list/ilugc][ILUGC
mailing list]] on the day of the meetup. If you are not subscribed, you
can also check
the [[https://www.freelists.org/archive/ilugc/][archive]].

Checkout the upcoming
meetings [[https://emacs-apac.gitlab.io/#upcoming][here]].

** Talks
   :PROPERTIES:
   :CUSTOM_ID: talks
   :END:

We usually have free flowing discussions around new Emacs packages /
features discovered, issues faced, experiences, usage tips, resources
for further learning etc. These are related to GNU Emacs and its
variants. Sometimes people also share their screens and give demos of
their Emacs setup and use.

If you would like to give a talk (20 minutes maximum), please send an
email to TODO with the details.

** Frequently Asked Questions
   :PROPERTIES:
   :CUSTOM_ID: frequently-asked-questions
   :END:

- *I'm new to Emacs, can / should I join?*
  Yes! You are always welcome. We have participants from different walks
  of life with varied experiences in Emacs. You can ask your questions
  and the attendees will be able to help, at least point you in the
  right direction.

- *Which language is used for communication?*
  English.

- *I'm not from APAC, can I join?*
  Definitely! If the timing is suitable for you, please join.




* Emacs Berlin (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-berlin.org/
:END:
<2021-12-29 Wed 17:30>--<2021-12-29 Wed 19:30>

[[https://emacs-berlin.org/]] 

New to Emacs? Longtime elisp expert? Just want to know what this is all
about? Come join us!

Location

Room open from 18:30 CET, if there are talks they'll start at 19:00 CET.
The video link will be posted on the day of the meetup to the mailing
list. Check the archive
([[https://mailb.org/pipermail/emacs-berlin/2021/thread.html]]) if you
are not subscribed.

About Emacs Berlin
We are Emacs enthusiasts in Berlin, meeting every last Wednesday of the
month.
The best way to stay posted is through our mailing list. Sign up
([[https://mailb.org/mailman/listinfo/emacs-berlin]]) and meet your
fellow Emacsers, or have a look at the mailing list archives
([[https://mailb.org/pipermail/emacs-berlin/]]) (gmane).
Feel free to send an email introducing yourself after subscribing!
You can also chat with us on irc: #emacs-berlin (connection instructions
([[https://mailb.org/pipermail/emacs-berlin/2020/000583.html]]))
Or on Twitter: @emacsberlin ([[https://twitter.com/emacsberlin]])
And there's a YouTube Channel
([[https://www.youtube.com/channel/UC1O8700SW-wuC4fvDEoGzOw]])  
And
on [[http://meetup.com/Emacs-Berlin-Meetup][meetup.com/Emacs-Berlin-Meetup]]
([[https://www.meetup.com/Emacs-Berlin-Meetup/]])
Non-public contact via email: organizers email
(mailto:[[mailto:emacs-berlin-owner@emacs-berlin.org][emacs-berlin-owner@emacs-berlin.org]])


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-01-06 Thu 15:00>--<2022-01-06 Thu 16:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-01-20 Thu 15:00>--<2022-01-20 Thu 16:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* Emacs APAC (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-apac.gitlab.io/
:END:
<2022-01-22 Sat 08:30>--<2022-01-22 Sat 10:30>

We are Emacs enthusiasts who live in the Asia-Pacific (APAC) time-zone.
We meet every fourth Saturday of the month.

** Where
   :PROPERTIES:
   :CUSTOM_ID: where
   :END:

The event is scheduled virtually using Jitsi Meet at 1400 Indian
Standard Time (IST). The meeting URL is posted on Freenode IRC
channels =#emacs=, =#ilugc= and =#emacsconf=, 30 minutes prior to the
meeting, and also on the [[https://www.freelists.org/list/ilugc][ILUGC
mailing list]] on the day of the meetup. If you are not subscribed, you
can also check
the [[https://www.freelists.org/archive/ilugc/][archive]].

Checkout the upcoming
meetings [[https://emacs-apac.gitlab.io/#upcoming][here]].

** Talks
   :PROPERTIES:
   :CUSTOM_ID: talks
   :END:

We usually have free flowing discussions around new Emacs packages /
features discovered, issues faced, experiences, usage tips, resources
for further learning etc. These are related to GNU Emacs and its
variants. Sometimes people also share their screens and give demos of
their Emacs setup and use.

If you would like to give a talk (20 minutes maximum), please send an
email to TODO with the details.

** Frequently Asked Questions
   :PROPERTIES:
   :CUSTOM_ID: frequently-asked-questions
   :END:

- *I'm new to Emacs, can / should I join?*
  Yes! You are always welcome. We have participants from different walks
  of life with varied experiences in Emacs. You can ask your questions
  and the attendees will be able to help, at least point you in the
  right direction.

- *Which language is used for communication?*
  English.

- *I'm not from APAC, can I join?*
  Definitely! If the timing is suitable for you, please join.




* Emacs Berlin (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-berlin.org/
:END:
<2022-01-26 Wed 17:30>--<2022-01-26 Wed 19:30>

[[https://emacs-berlin.org/]] 

New to Emacs? Longtime elisp expert? Just want to know what this is all
about? Come join us!

Location

Room open from 18:30 CET, if there are talks they'll start at 19:00 CET.
The video link will be posted on the day of the meetup to the mailing
list. Check the archive
([[https://mailb.org/pipermail/emacs-berlin/2021/thread.html]]) if you
are not subscribed.

About Emacs Berlin
We are Emacs enthusiasts in Berlin, meeting every last Wednesday of the
month.
The best way to stay posted is through our mailing list. Sign up
([[https://mailb.org/mailman/listinfo/emacs-berlin]]) and meet your
fellow Emacsers, or have a look at the mailing list archives
([[https://mailb.org/pipermail/emacs-berlin/]]) (gmane).
Feel free to send an email introducing yourself after subscribing!
You can also chat with us on irc: #emacs-berlin (connection instructions
([[https://mailb.org/pipermail/emacs-berlin/2020/000583.html]]))
Or on Twitter: @emacsberlin ([[https://twitter.com/emacsberlin]])
And there's a YouTube Channel
([[https://www.youtube.com/channel/UC1O8700SW-wuC4fvDEoGzOw]])  
And
on [[http://meetup.com/Emacs-Berlin-Meetup][meetup.com/Emacs-Berlin-Meetup]]
([[https://www.meetup.com/Emacs-Berlin-Meetup/]])
Non-public contact via email: organizers email
(mailto:[[mailto:emacs-berlin-owner@emacs-berlin.org][emacs-berlin-owner@emacs-berlin.org]])


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-02-03 Thu 15:00>--<2022-02-03 Thu 16:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-02-17 Thu 15:00>--<2022-02-17 Thu 16:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* Emacs Berlin (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-berlin.org/
:END:
<2022-02-23 Wed 17:30>--<2022-02-23 Wed 19:30>

[[https://emacs-berlin.org/]] 

New to Emacs? Longtime elisp expert? Just want to know what this is all
about? Come join us!

Location

Room open from 18:30 CET, if there are talks they'll start at 19:00 CET.
The video link will be posted on the day of the meetup to the mailing
list. Check the archive
([[https://mailb.org/pipermail/emacs-berlin/2021/thread.html]]) if you
are not subscribed.

About Emacs Berlin
We are Emacs enthusiasts in Berlin, meeting every last Wednesday of the
month.
The best way to stay posted is through our mailing list. Sign up
([[https://mailb.org/mailman/listinfo/emacs-berlin]]) and meet your
fellow Emacsers, or have a look at the mailing list archives
([[https://mailb.org/pipermail/emacs-berlin/]]) (gmane).
Feel free to send an email introducing yourself after subscribing!
You can also chat with us on irc: #emacs-berlin (connection instructions
([[https://mailb.org/pipermail/emacs-berlin/2020/000583.html]]))
Or on Twitter: @emacsberlin ([[https://twitter.com/emacsberlin]])
And there's a YouTube Channel
([[https://www.youtube.com/channel/UC1O8700SW-wuC4fvDEoGzOw]])  
And
on [[http://meetup.com/Emacs-Berlin-Meetup][meetup.com/Emacs-Berlin-Meetup]]
([[https://www.meetup.com/Emacs-Berlin-Meetup/]])
Non-public contact via email: organizers email
(mailto:[[mailto:emacs-berlin-owner@emacs-berlin.org][emacs-berlin-owner@emacs-berlin.org]])


* Emacs APAC (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-apac.gitlab.io/
:END:
<2022-02-26 Sat 08:30>--<2022-02-26 Sat 10:30>

We are Emacs enthusiasts who live in the Asia-Pacific (APAC) time-zone.
We meet every fourth Saturday of the month.

** Where
   :PROPERTIES:
   :CUSTOM_ID: where
   :END:

The event is scheduled virtually using Jitsi Meet at 1400 Indian
Standard Time (IST). The meeting URL is posted on Freenode IRC
channels =#emacs=, =#ilugc= and =#emacsconf=, 30 minutes prior to the
meeting, and also on the [[https://www.freelists.org/list/ilugc][ILUGC
mailing list]] on the day of the meetup. If you are not subscribed, you
can also check
the [[https://www.freelists.org/archive/ilugc/][archive]].

Checkout the upcoming
meetings [[https://emacs-apac.gitlab.io/#upcoming][here]].

** Talks
   :PROPERTIES:
   :CUSTOM_ID: talks
   :END:

We usually have free flowing discussions around new Emacs packages /
features discovered, issues faced, experiences, usage tips, resources
for further learning etc. These are related to GNU Emacs and its
variants. Sometimes people also share their screens and give demos of
their Emacs setup and use.

If you would like to give a talk (20 minutes maximum), please send an
email to TODO with the details.

** Frequently Asked Questions
   :PROPERTIES:
   :CUSTOM_ID: frequently-asked-questions
   :END:

- *I'm new to Emacs, can / should I join?*
  Yes! You are always welcome. We have participants from different walks
  of life with varied experiences in Emacs. You can ask your questions
  and the attendees will be able to help, at least point you in the
  right direction.

- *Which language is used for communication?*
  English.

- *I'm not from APAC, can I join?*
  Definitely! If the timing is suitable for you, please join.




* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-03-03 Thu 15:00>--<2022-03-03 Thu 16:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-03-17 Thu 15:00>--<2022-03-17 Thu 16:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* Emacs APAC (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-apac.gitlab.io/
:END:
<2022-03-26 Sat 08:30>--<2022-03-26 Sat 10:30>

We are Emacs enthusiasts who live in the Asia-Pacific (APAC) time-zone.
We meet every fourth Saturday of the month.

** Where
   :PROPERTIES:
   :CUSTOM_ID: where
   :END:

The event is scheduled virtually using Jitsi Meet at 1400 Indian
Standard Time (IST). The meeting URL is posted on Freenode IRC
channels =#emacs=, =#ilugc= and =#emacsconf=, 30 minutes prior to the
meeting, and also on the [[https://www.freelists.org/list/ilugc][ILUGC
mailing list]] on the day of the meetup. If you are not subscribed, you
can also check
the [[https://www.freelists.org/archive/ilugc/][archive]].

Checkout the upcoming
meetings [[https://emacs-apac.gitlab.io/#upcoming][here]].

** Talks
   :PROPERTIES:
   :CUSTOM_ID: talks
   :END:

We usually have free flowing discussions around new Emacs packages /
features discovered, issues faced, experiences, usage tips, resources
for further learning etc. These are related to GNU Emacs and its
variants. Sometimes people also share their screens and give demos of
their Emacs setup and use.

If you would like to give a talk (20 minutes maximum), please send an
email to TODO with the details.

** Frequently Asked Questions
   :PROPERTIES:
   :CUSTOM_ID: frequently-asked-questions
   :END:

- *I'm new to Emacs, can / should I join?*
  Yes! You are always welcome. We have participants from different walks
  of life with varied experiences in Emacs. You can ask your questions
  and the attendees will be able to help, at least point you in the
  right direction.

- *Which language is used for communication?*
  English.

- *I'm not from APAC, can I join?*
  Definitely! If the timing is suitable for you, please join.




* Emacs Berlin (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-berlin.org/
:END:
<2022-03-30 Wed 16:30>--<2022-03-30 Wed 18:30>

[[https://emacs-berlin.org/]] 

New to Emacs? Longtime elisp expert? Just want to know what this is all
about? Come join us!

Location

Room open from 18:30 CET, if there are talks they'll start at 19:00 CET.
The video link will be posted on the day of the meetup to the mailing
list. Check the archive
([[https://mailb.org/pipermail/emacs-berlin/2021/thread.html]]) if you
are not subscribed.

About Emacs Berlin
We are Emacs enthusiasts in Berlin, meeting every last Wednesday of the
month.
The best way to stay posted is through our mailing list. Sign up
([[https://mailb.org/mailman/listinfo/emacs-berlin]]) and meet your
fellow Emacsers, or have a look at the mailing list archives
([[https://mailb.org/pipermail/emacs-berlin/]]) (gmane).
Feel free to send an email introducing yourself after subscribing!
You can also chat with us on irc: #emacs-berlin (connection instructions
([[https://mailb.org/pipermail/emacs-berlin/2020/000583.html]]))
Or on Twitter: @emacsberlin ([[https://twitter.com/emacsberlin]])
And there's a YouTube Channel
([[https://www.youtube.com/channel/UC1O8700SW-wuC4fvDEoGzOw]])  
And
on [[http://meetup.com/Emacs-Berlin-Meetup][meetup.com/Emacs-Berlin-Meetup]]
([[https://www.meetup.com/Emacs-Berlin-Meetup/]])
Non-public contact via email: organizers email
(mailto:[[mailto:emacs-berlin-owner@emacs-berlin.org][emacs-berlin-owner@emacs-berlin.org]])


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-04-07 Thu 14:00>--<2022-04-07 Thu 15:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* M-x Research (virtual, contact them for passcode)
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-04-21 Thu 14:00>--<2022-04-21 Thu 15:00>

[[https://m-x-research.github.io/]] - See "Contact Us" section below for
password

* The Community
  :PROPERTIES:
  :CUSTOM_ID: the-community
  :END:

M-x Research is a community of Researchers and Research Software
Engineers, first conceived in the UK Research Software Engineering
Society Slack channels.

We meet virtually every 1st and 3rd Thursday of every month to dicuss
and share Emacs experiences, tips, tricks and tools useful for
researchers and research software engineers.

* Environment
  :PROPERTIES:
  :CUSTOM_ID: environment
  :END:

We strive to be welcoming and inclusive and to recognise the diversity
of backgrounds and experience in the Emacs world. Newcomers and veterans
are all welcome. Ultimately we are all learners.

* Events
  :PROPERTIES:
  :CUSTOM_ID: events
  :END:

Join our meetups on Zoom by following [[https://bit.ly/mxresearch]] @
3pm (UK time)

Get in touch (details below) to request a password.

Add the shared
calendar [[https://calendar.google.com/calendar?cid=bzB0aWFkbGpwNWRxN2xrYjUxbW52bnJoMDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][on
google calendar]] or as
an [[https://calendar.google.com/calendar/ical/o0tiadljp5dq7lkb51mnvnrh04%40group.calendar.google.com/public/basic.ics][iCal
link]].

* Contact Us
  :PROPERTIES:
  :CUSTOM_ID: contact-us
  :END:

To speak at an event or propose a topic, get in touch on the #emacs
channel of UKRSE Slack, or
email [[mailto:mark.dawson@swansea.ac.uk][mark.dawson@swansea.ac.uk]]


* Emacs APAC (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-apac.gitlab.io/
:END:
<2022-04-23 Sat 08:30>--<2022-04-23 Sat 10:30>

We are Emacs enthusiasts who live in the Asia-Pacific (APAC) time-zone.
We meet every fourth Saturday of the month.

** Where
   :PROPERTIES:
   :CUSTOM_ID: where
   :END:

The event is scheduled virtually using Jitsi Meet at 1400 Indian
Standard Time (IST). The meeting URL is posted on Freenode IRC
channels =#emacs=, =#ilugc= and =#emacsconf=, 30 minutes prior to the
meeting, and also on the [[https://www.freelists.org/list/ilugc][ILUGC
mailing list]] on the day of the meetup. If you are not subscribed, you
can also check
the [[https://www.freelists.org/archive/ilugc/][archive]].

Checkout the upcoming
meetings [[https://emacs-apac.gitlab.io/#upcoming][here]].

** Talks
   :PROPERTIES:
   :CUSTOM_ID: talks
   :END:

We usually have free flowing discussions around new Emacs packages /
features discovered, issues faced, experiences, usage tips, resources
for further learning etc. These are related to GNU Emacs and its
variants. Sometimes people also share their screens and give demos of
their Emacs setup and use.

If you would like to give a talk (20 minutes maximum), please send an
email to TODO with the details.

** Frequently Asked Questions
   :PROPERTIES:
   :CUSTOM_ID: frequently-asked-questions
   :END:

- *I'm new to Emacs, can / should I join?*
  Yes! You are always welcome. We have participants from different walks
  of life with varied experiences in Emacs. You can ask your questions
  and the attendees will be able to help, at least point you in the
  right direction.

- *Which language is used for communication?*
  English.

- *I'm not from APAC, can I join?*
  Definitely! If the timing is suitable for you, please join.




