* Emacs Paris (virtual, in French)
:PROPERTIES:
:LOCATION: https://www.emacs-doctor.com/emacs-paris-user-group/
:END:
<2021-11-04 Thu 09:30>--<2021-11-04 Thu 11:00>

[[https://www.emacs-doctor.com/emacs-paris-user-group/]] 


Nous sommes quelques utilisateurs
de [[https://www.gnu.org/software/emacs/][GNU Emacs]] à nous réunir
à *Paris* et à *Montpellier* pour apprendre les uns des autres : c'est
ouvert aux non-emacsiens, aux débutants, aux utilisateurs avancés et aux
vimistes !

** Liste de discussion et forum
   :PROPERTIES:
   :CUSTOM_ID: liste-de-discussion-et-forum
   :END:

Vous pouvez vous inscrire
sur [[https://emacs-doctor.com/lists/listinfo/ateliers-paris][la liste
de discussion]].

Nous avons aussi un [[https://emacs-doctor.com/forum/][forum]],
n'hésitez pas à échanger.

** Comment je m'inscris à un atelier ?
   :PROPERTIES:
   :CUSTOM_ID: comment-je-minscris-à-un-atelier
   :END:

*** Pour Paris
    :PROPERTIES:
    :CUSTOM_ID: pour-paris
    :END:

Nous faisons des rencontres en ligne. Il y a parfois des rencontres
physiques chez [[http://inno3.fr/][inno3.fr]] au 137 Boulevard de
Magenta 75010 Paris
([[http://www.openstreetmap.org/#map=16/48.8818/2.3514][plan]]) de 19h à
22h.

Si vous venez pour la première fois à un atelier IRL, envoyez un mot
à =bzg@bzg.fr=. Pour la visio, vous pouvez simplement débarquer.

*** Pour Montpellier
    :PROPERTIES:
    :CUSTOM_ID: pour-montpellier
    :END:

Envoyez un petit mot à =emacsem-owner@movoscope.org= et vous serez
inscrit.

** Rencontres passées
   :PROPERTIES:
   :CUSTOM_ID: rencontres-passées
   :END:

Nous gardons parfois des notes des soirées passées
sur [[https://gitlab.com/bzg2/emacsparis/blob/master/README.org][ce
dépôt]].


* M-x Research (contact them for password): Cancelled: M-x Research
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2021-11-05 Fri 08:00>--<2021-11-05 Fri 09:00>




* M-x Research (contact them for password): TBA
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2021-11-19 Fri 07:00>--<2021-11-19 Fri 08:00>




* Emacs Berlin (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-berlin.org/
:END:
<2021-11-24 Wed 09:30>--<2021-11-24 Wed 11:30>

[[https://emacs-berlin.org/]] 

New to Emacs? Longtime elisp expert? Just want to know what this is all
about? Come join us!

Location

Room open from 18:30 CET, if there are talks they'll start at 19:00 CET.
The video link will be posted on the day of the meetup to the mailing
list. Check the archive
([[https://mailb.org/pipermail/emacs-berlin/2021/thread.html]]) if you
are not subscribed.

About Emacs Berlin
We are Emacs enthusiasts in Berlin, meeting every last Wednesday of the
month.
The best way to stay posted is through our mailing list. Sign up
([[https://mailb.org/mailman/listinfo/emacs-berlin]]) and meet your
fellow Emacsers, or have a look at the mailing list archives
([[https://mailb.org/pipermail/emacs-berlin/]]) (gmane).
Feel free to send an email introducing yourself after subscribing!
You can also chat with us on irc: #emacs-berlin (connection instructions
([[https://mailb.org/pipermail/emacs-berlin/2020/000583.html]]))
Or on Twitter: @emacsberlin ([[https://twitter.com/emacsberlin]])
And there's a YouTube Channel
([[https://www.youtube.com/channel/UC1O8700SW-wuC4fvDEoGzOw]])  
And
on [[http://meetup.com/Emacs-Berlin-Meetup][meetup.com/Emacs-Berlin-Meetup]]
([[https://www.meetup.com/Emacs-Berlin-Meetup/]])
Non-public contact via email: organizers email
(mailto:[[mailto:emacs-berlin-owner@emacs-berlin.org][emacs-berlin-owner@emacs-berlin.org]])


* Emacs APAC (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-apac.gitlab.io/
:END:
<2021-11-27 Sat 00:30>--<2021-11-27 Sat 02:30>

We are Emacs enthusiasts who live in the Asia-Pacific (APAC) time-zone.
We meet every fourth Saturday of the month.

** Where
   :PROPERTIES:
   :CUSTOM_ID: where
   :END:

The event is scheduled virtually using Jitsi Meet at 1400 Indian
Standard Time (IST). The meeting URL is posted on Freenode IRC
channels =#emacs=, =#ilugc= and =#emacsconf=, 30 minutes prior to the
meeting, and also on the [[https://www.freelists.org/list/ilugc][ILUGC
mailing list]] on the day of the meetup. If you are not subscribed, you
can also check
the [[https://www.freelists.org/archive/ilugc/][archive]].

Checkout the upcoming
meetings [[https://emacs-apac.gitlab.io/#upcoming][here]].

** Talks
   :PROPERTIES:
   :CUSTOM_ID: talks
   :END:

We usually have free flowing discussions around new Emacs packages /
features discovered, issues faced, experiences, usage tips, resources
for further learning etc. These are related to GNU Emacs and its
variants. Sometimes people also share their screens and give demos of
their Emacs setup and use.

If you would like to give a talk (20 minutes maximum), please send an
email to TODO with the details.

** Frequently Asked Questions
   :PROPERTIES:
   :CUSTOM_ID: frequently-asked-questions
   :END:

- *I'm new to Emacs, can / should I join?*
  Yes! You are always welcome. We have participants from different walks
  of life with varied experiences in Emacs. You can ask your questions
  and the attendees will be able to help, at least point you in the
  right direction.

- *Which language is used for communication?*
  English.

- *I'm not from APAC, can I join?*
  Definitely! If the timing is suitable for you, please join.




* EmacsATX: TBD
:PROPERTIES:
:LOCATION: https://www.meetup.com/EmacsATX/events/281742622/
:END:
<2021-12-01 Wed 16:30>--<2021-12-01 Wed 18:30>

EmacsATX Wednesday, December 1 at 6:30 PM About Emacs ATX is a meetup
devoted to exploring the vast and ever expanding universe of the
extensible, customizable, free/libre editor Emacs. We are...
https://www.meetup.com/EmacsATX/events/281742622/


* M-x Research (contact them for password): TBA
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2021-12-03 Fri 07:00>--<2021-12-03 Fri 08:00>




* EmacsNYC: Discussion: Is VSCode Better?
:PROPERTIES:
:LOCATION: https://www.meetup.com/New-York-Emacs-Meetup/events/281810145/
:END:
<2021-12-06 Mon 16:00>--<2021-12-06 Mon 18:00>

New York Emacs Meetup Monday, December 6 at 7:00 PM Emacs and Vi are old
news! The new game in town VSCode. It's taking everyone by storm! Stand
down Sublime Text! Did anyone even use Atom? Good bye, Py...
https://www.meetup.com/New-York-Emacs-Meetup/events/281810145/


* Emacs Paris (virtual, in French)
:PROPERTIES:
:LOCATION: https://www.emacs-doctor.com/emacs-paris-user-group/
:END:
<2021-12-07 Tue 08:30>--<2021-12-07 Tue 10:00>

[[https://www.emacs-doctor.com/emacs-paris-user-group/]] 


Nous sommes quelques utilisateurs
de [[https://www.gnu.org/software/emacs/][GNU Emacs]] à nous réunir
à *Paris* et à *Montpellier* pour apprendre les uns des autres : c'est
ouvert aux non-emacsiens, aux débutants, aux utilisateurs avancés et aux
vimistes !

** Liste de discussion et forum
   :PROPERTIES:
   :CUSTOM_ID: liste-de-discussion-et-forum
   :END:

Vous pouvez vous inscrire
sur [[https://emacs-doctor.com/lists/listinfo/ateliers-paris][la liste
de discussion]].

Nous avons aussi un [[https://emacs-doctor.com/forum/][forum]],
n'hésitez pas à échanger.

** Comment je m'inscris à un atelier ?
   :PROPERTIES:
   :CUSTOM_ID: comment-je-minscris-à-un-atelier
   :END:

*** Pour Paris
    :PROPERTIES:
    :CUSTOM_ID: pour-paris
    :END:

Nous faisons des rencontres en ligne. Il y a parfois des rencontres
physiques chez [[http://inno3.fr/][inno3.fr]] au 137 Boulevard de
Magenta 75010 Paris
([[http://www.openstreetmap.org/#map=16/48.8818/2.3514][plan]]) de 19h à
22h.

Si vous venez pour la première fois à un atelier IRL, envoyez un mot
à =bzg@bzg.fr=. Pour la visio, vous pouvez simplement débarquer.

*** Pour Montpellier
    :PROPERTIES:
    :CUSTOM_ID: pour-montpellier
    :END:

Envoyez un petit mot à =emacsem-owner@movoscope.org= et vous serez
inscrit.

** Rencontres passées
   :PROPERTIES:
   :CUSTOM_ID: rencontres-passées
   :END:

Nous gardons parfois des notes des soirées passées
sur [[https://gitlab.com/bzg2/emacsparis/blob/master/README.org][ce
dépôt]].


* M-x Research (contact them for password): TBA
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2021-12-17 Fri 07:00>--<2021-12-17 Fri 08:00>




* Emacs APAC (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-apac.gitlab.io/
:END:
<2021-12-25 Sat 00:30>--<2021-12-25 Sat 02:30>

We are Emacs enthusiasts who live in the Asia-Pacific (APAC) time-zone.
We meet every fourth Saturday of the month.

** Where
   :PROPERTIES:
   :CUSTOM_ID: where
   :END:

The event is scheduled virtually using Jitsi Meet at 1400 Indian
Standard Time (IST). The meeting URL is posted on Freenode IRC
channels =#emacs=, =#ilugc= and =#emacsconf=, 30 minutes prior to the
meeting, and also on the [[https://www.freelists.org/list/ilugc][ILUGC
mailing list]] on the day of the meetup. If you are not subscribed, you
can also check
the [[https://www.freelists.org/archive/ilugc/][archive]].

Checkout the upcoming
meetings [[https://emacs-apac.gitlab.io/#upcoming][here]].

** Talks
   :PROPERTIES:
   :CUSTOM_ID: talks
   :END:

We usually have free flowing discussions around new Emacs packages /
features discovered, issues faced, experiences, usage tips, resources
for further learning etc. These are related to GNU Emacs and its
variants. Sometimes people also share their screens and give demos of
their Emacs setup and use.

If you would like to give a talk (20 minutes maximum), please send an
email to TODO with the details.

** Frequently Asked Questions
   :PROPERTIES:
   :CUSTOM_ID: frequently-asked-questions
   :END:

- *I'm new to Emacs, can / should I join?*
  Yes! You are always welcome. We have participants from different walks
  of life with varied experiences in Emacs. You can ask your questions
  and the attendees will be able to help, at least point you in the
  right direction.

- *Which language is used for communication?*
  English.

- *I'm not from APAC, can I join?*
  Definitely! If the timing is suitable for you, please join.




* Emacs Berlin (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-berlin.org/
:END:
<2021-12-29 Wed 09:30>--<2021-12-29 Wed 11:30>

[[https://emacs-berlin.org/]] 

New to Emacs? Longtime elisp expert? Just want to know what this is all
about? Come join us!

Location

Room open from 18:30 CET, if there are talks they'll start at 19:00 CET.
The video link will be posted on the day of the meetup to the mailing
list. Check the archive
([[https://mailb.org/pipermail/emacs-berlin/2021/thread.html]]) if you
are not subscribed.

About Emacs Berlin
We are Emacs enthusiasts in Berlin, meeting every last Wednesday of the
month.
The best way to stay posted is through our mailing list. Sign up
([[https://mailb.org/mailman/listinfo/emacs-berlin]]) and meet your
fellow Emacsers, or have a look at the mailing list archives
([[https://mailb.org/pipermail/emacs-berlin/]]) (gmane).
Feel free to send an email introducing yourself after subscribing!
You can also chat with us on irc: #emacs-berlin (connection instructions
([[https://mailb.org/pipermail/emacs-berlin/2020/000583.html]]))
Or on Twitter: @emacsberlin ([[https://twitter.com/emacsberlin]])
And there's a YouTube Channel
([[https://www.youtube.com/channel/UC1O8700SW-wuC4fvDEoGzOw]])  
And
on [[http://meetup.com/Emacs-Berlin-Meetup][meetup.com/Emacs-Berlin-Meetup]]
([[https://www.meetup.com/Emacs-Berlin-Meetup/]])
Non-public contact via email: organizers email
(mailto:[[mailto:emacs-berlin-owner@emacs-berlin.org][emacs-berlin-owner@emacs-berlin.org]])


* EmacsATX: TBD
:PROPERTIES:
:LOCATION: https://www.meetup.com/EmacsATX/events/hkckgsydccbhb/
:END:
<2022-01-05 Wed 16:30>--<2022-01-05 Wed 18:30>

EmacsATX Wednesday, January 5 at 6:30 PM About Emacs ATX is a meetup
devoted to exploring the vast and ever expanding universe of the
extensible, customizable, free/libre editor Emacs. We are...
https://www.meetup.com/EmacsATX/events/hkckgsydccbhb/


* Emacs Paris (virtual, in French)
:PROPERTIES:
:LOCATION: https://www.emacs-doctor.com/emacs-paris-user-group/
:END:
<2022-01-06 Thu 08:30>--<2022-01-06 Thu 10:00>

[[https://www.emacs-doctor.com/emacs-paris-user-group/]] 


Nous sommes quelques utilisateurs
de [[https://www.gnu.org/software/emacs/][GNU Emacs]] à nous réunir
à *Paris* et à *Montpellier* pour apprendre les uns des autres : c'est
ouvert aux non-emacsiens, aux débutants, aux utilisateurs avancés et aux
vimistes !

** Liste de discussion et forum
   :PROPERTIES:
   :CUSTOM_ID: liste-de-discussion-et-forum
   :END:

Vous pouvez vous inscrire
sur [[https://emacs-doctor.com/lists/listinfo/ateliers-paris][la liste
de discussion]].

Nous avons aussi un [[https://emacs-doctor.com/forum/][forum]],
n'hésitez pas à échanger.

** Comment je m'inscris à un atelier ?
   :PROPERTIES:
   :CUSTOM_ID: comment-je-minscris-à-un-atelier
   :END:

*** Pour Paris
    :PROPERTIES:
    :CUSTOM_ID: pour-paris
    :END:

Nous faisons des rencontres en ligne. Il y a parfois des rencontres
physiques chez [[http://inno3.fr/][inno3.fr]] au 137 Boulevard de
Magenta 75010 Paris
([[http://www.openstreetmap.org/#map=16/48.8818/2.3514][plan]]) de 19h à
22h.

Si vous venez pour la première fois à un atelier IRL, envoyez un mot
à =bzg@bzg.fr=. Pour la visio, vous pouvez simplement débarquer.

*** Pour Montpellier
    :PROPERTIES:
    :CUSTOM_ID: pour-montpellier
    :END:

Envoyez un petit mot à =emacsem-owner@movoscope.org= et vous serez
inscrit.

** Rencontres passées
   :PROPERTIES:
   :CUSTOM_ID: rencontres-passées
   :END:

Nous gardons parfois des notes des soirées passées
sur [[https://gitlab.com/bzg2/emacsparis/blob/master/README.org][ce
dépôt]].


* M-x Research (contact them for password): TBA
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-01-07 Fri 07:00>--<2022-01-07 Fri 08:00>




* M-x Research (contact them for password): TBA
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-01-21 Fri 07:00>--<2022-01-21 Fri 08:00>




* Emacs APAC (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-apac.gitlab.io/
:END:
<2022-01-22 Sat 00:30>--<2022-01-22 Sat 02:30>

We are Emacs enthusiasts who live in the Asia-Pacific (APAC) time-zone.
We meet every fourth Saturday of the month.

** Where
   :PROPERTIES:
   :CUSTOM_ID: where
   :END:

The event is scheduled virtually using Jitsi Meet at 1400 Indian
Standard Time (IST). The meeting URL is posted on Freenode IRC
channels =#emacs=, =#ilugc= and =#emacsconf=, 30 minutes prior to the
meeting, and also on the [[https://www.freelists.org/list/ilugc][ILUGC
mailing list]] on the day of the meetup. If you are not subscribed, you
can also check
the [[https://www.freelists.org/archive/ilugc/][archive]].

Checkout the upcoming
meetings [[https://emacs-apac.gitlab.io/#upcoming][here]].

** Talks
   :PROPERTIES:
   :CUSTOM_ID: talks
   :END:

We usually have free flowing discussions around new Emacs packages /
features discovered, issues faced, experiences, usage tips, resources
for further learning etc. These are related to GNU Emacs and its
variants. Sometimes people also share their screens and give demos of
their Emacs setup and use.

If you would like to give a talk (20 minutes maximum), please send an
email to TODO with the details.

** Frequently Asked Questions
   :PROPERTIES:
   :CUSTOM_ID: frequently-asked-questions
   :END:

- *I'm new to Emacs, can / should I join?*
  Yes! You are always welcome. We have participants from different walks
  of life with varied experiences in Emacs. You can ask your questions
  and the attendees will be able to help, at least point you in the
  right direction.

- *Which language is used for communication?*
  English.

- *I'm not from APAC, can I join?*
  Definitely! If the timing is suitable for you, please join.




* Emacs Berlin (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-berlin.org/
:END:
<2022-01-26 Wed 09:30>--<2022-01-26 Wed 11:30>

[[https://emacs-berlin.org/]] 

New to Emacs? Longtime elisp expert? Just want to know what this is all
about? Come join us!

Location

Room open from 18:30 CET, if there are talks they'll start at 19:00 CET.
The video link will be posted on the day of the meetup to the mailing
list. Check the archive
([[https://mailb.org/pipermail/emacs-berlin/2021/thread.html]]) if you
are not subscribed.

About Emacs Berlin
We are Emacs enthusiasts in Berlin, meeting every last Wednesday of the
month.
The best way to stay posted is through our mailing list. Sign up
([[https://mailb.org/mailman/listinfo/emacs-berlin]]) and meet your
fellow Emacsers, or have a look at the mailing list archives
([[https://mailb.org/pipermail/emacs-berlin/]]) (gmane).
Feel free to send an email introducing yourself after subscribing!
You can also chat with us on irc: #emacs-berlin (connection instructions
([[https://mailb.org/pipermail/emacs-berlin/2020/000583.html]]))
Or on Twitter: @emacsberlin ([[https://twitter.com/emacsberlin]])
And there's a YouTube Channel
([[https://www.youtube.com/channel/UC1O8700SW-wuC4fvDEoGzOw]])  
And
on [[http://meetup.com/Emacs-Berlin-Meetup][meetup.com/Emacs-Berlin-Meetup]]
([[https://www.meetup.com/Emacs-Berlin-Meetup/]])
Non-public contact via email: organizers email
(mailto:[[mailto:emacs-berlin-owner@emacs-berlin.org][emacs-berlin-owner@emacs-berlin.org]])


* Emacs Paris (virtual, in French)
:PROPERTIES:
:LOCATION: https://www.emacs-doctor.com/emacs-paris-user-group/
:END:
<2022-02-01 Tue 08:30>--<2022-02-01 Tue 10:00>

[[https://www.emacs-doctor.com/emacs-paris-user-group/]] 


Nous sommes quelques utilisateurs
de [[https://www.gnu.org/software/emacs/][GNU Emacs]] à nous réunir
à *Paris* et à *Montpellier* pour apprendre les uns des autres : c'est
ouvert aux non-emacsiens, aux débutants, aux utilisateurs avancés et aux
vimistes !

** Liste de discussion et forum
   :PROPERTIES:
   :CUSTOM_ID: liste-de-discussion-et-forum
   :END:

Vous pouvez vous inscrire
sur [[https://emacs-doctor.com/lists/listinfo/ateliers-paris][la liste
de discussion]].

Nous avons aussi un [[https://emacs-doctor.com/forum/][forum]],
n'hésitez pas à échanger.

** Comment je m'inscris à un atelier ?
   :PROPERTIES:
   :CUSTOM_ID: comment-je-minscris-à-un-atelier
   :END:

*** Pour Paris
    :PROPERTIES:
    :CUSTOM_ID: pour-paris
    :END:

Nous faisons des rencontres en ligne. Il y a parfois des rencontres
physiques chez [[http://inno3.fr/][inno3.fr]] au 137 Boulevard de
Magenta 75010 Paris
([[http://www.openstreetmap.org/#map=16/48.8818/2.3514][plan]]) de 19h à
22h.

Si vous venez pour la première fois à un atelier IRL, envoyez un mot
à =bzg@bzg.fr=. Pour la visio, vous pouvez simplement débarquer.

*** Pour Montpellier
    :PROPERTIES:
    :CUSTOM_ID: pour-montpellier
    :END:

Envoyez un petit mot à =emacsem-owner@movoscope.org= et vous serez
inscrit.

** Rencontres passées
   :PROPERTIES:
   :CUSTOM_ID: rencontres-passées
   :END:

Nous gardons parfois des notes des soirées passées
sur [[https://gitlab.com/bzg2/emacsparis/blob/master/README.org][ce
dépôt]].


* EmacsATX: TBD
:PROPERTIES:
:LOCATION: https://www.meetup.com/EmacsATX/events/hkckgsydcdbdb/
:END:
<2022-02-02 Wed 16:30>--<2022-02-02 Wed 18:30>

EmacsATX Wednesday, February 2 at 6:30 PM About Emacs ATX is a meetup
devoted to exploring the vast and ever expanding universe of the
extensible, customizable, free/libre editor Emacs. We are...
https://www.meetup.com/EmacsATX/events/hkckgsydcdbdb/


* M-x Research (contact them for password): TBA
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-02-04 Fri 07:00>--<2022-02-04 Fri 08:00>




* M-x Research (contact them for password): TBA
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-02-18 Fri 07:00>--<2022-02-18 Fri 08:00>




* Emacs Berlin (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-berlin.org/
:END:
<2022-02-23 Wed 09:30>--<2022-02-23 Wed 11:30>

[[https://emacs-berlin.org/]] 

New to Emacs? Longtime elisp expert? Just want to know what this is all
about? Come join us!

Location

Room open from 18:30 CET, if there are talks they'll start at 19:00 CET.
The video link will be posted on the day of the meetup to the mailing
list. Check the archive
([[https://mailb.org/pipermail/emacs-berlin/2021/thread.html]]) if you
are not subscribed.

About Emacs Berlin
We are Emacs enthusiasts in Berlin, meeting every last Wednesday of the
month.
The best way to stay posted is through our mailing list. Sign up
([[https://mailb.org/mailman/listinfo/emacs-berlin]]) and meet your
fellow Emacsers, or have a look at the mailing list archives
([[https://mailb.org/pipermail/emacs-berlin/]]) (gmane).
Feel free to send an email introducing yourself after subscribing!
You can also chat with us on irc: #emacs-berlin (connection instructions
([[https://mailb.org/pipermail/emacs-berlin/2020/000583.html]]))
Or on Twitter: @emacsberlin ([[https://twitter.com/emacsberlin]])
And there's a YouTube Channel
([[https://www.youtube.com/channel/UC1O8700SW-wuC4fvDEoGzOw]])  
And
on [[http://meetup.com/Emacs-Berlin-Meetup][meetup.com/Emacs-Berlin-Meetup]]
([[https://www.meetup.com/Emacs-Berlin-Meetup/]])
Non-public contact via email: organizers email
(mailto:[[mailto:emacs-berlin-owner@emacs-berlin.org][emacs-berlin-owner@emacs-berlin.org]])


* Emacs APAC (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-apac.gitlab.io/
:END:
<2022-02-26 Sat 00:30>--<2022-02-26 Sat 02:30>

We are Emacs enthusiasts who live in the Asia-Pacific (APAC) time-zone.
We meet every fourth Saturday of the month.

** Where
   :PROPERTIES:
   :CUSTOM_ID: where
   :END:

The event is scheduled virtually using Jitsi Meet at 1400 Indian
Standard Time (IST). The meeting URL is posted on Freenode IRC
channels =#emacs=, =#ilugc= and =#emacsconf=, 30 minutes prior to the
meeting, and also on the [[https://www.freelists.org/list/ilugc][ILUGC
mailing list]] on the day of the meetup. If you are not subscribed, you
can also check
the [[https://www.freelists.org/archive/ilugc/][archive]].

Checkout the upcoming
meetings [[https://emacs-apac.gitlab.io/#upcoming][here]].

** Talks
   :PROPERTIES:
   :CUSTOM_ID: talks
   :END:

We usually have free flowing discussions around new Emacs packages /
features discovered, issues faced, experiences, usage tips, resources
for further learning etc. These are related to GNU Emacs and its
variants. Sometimes people also share their screens and give demos of
their Emacs setup and use.

If you would like to give a talk (20 minutes maximum), please send an
email to TODO with the details.

** Frequently Asked Questions
   :PROPERTIES:
   :CUSTOM_ID: frequently-asked-questions
   :END:

- *I'm new to Emacs, can / should I join?*
  Yes! You are always welcome. We have participants from different walks
  of life with varied experiences in Emacs. You can ask your questions
  and the attendees will be able to help, at least point you in the
  right direction.

- *Which language is used for communication?*
  English.

- *I'm not from APAC, can I join?*
  Definitely! If the timing is suitable for you, please join.




* EmacsATX: TBD
:PROPERTIES:
:LOCATION: https://www.meetup.com/EmacsATX/events/hkckgsydcfbdb/
:END:
<2022-03-02 Wed 16:30>--<2022-03-02 Wed 18:30>

EmacsATX Wednesday, March 2 at 6:30 PM About Emacs ATX is a meetup
devoted to exploring the vast and ever expanding universe of the
extensible, customizable, free/libre editor Emacs. We are...
https://www.meetup.com/EmacsATX/events/hkckgsydcfbdb/


* Emacs Paris (virtual, in French)
:PROPERTIES:
:LOCATION: https://www.emacs-doctor.com/emacs-paris-user-group/
:END:
<2022-03-03 Thu 08:30>--<2022-03-03 Thu 10:00>

[[https://www.emacs-doctor.com/emacs-paris-user-group/]] 


Nous sommes quelques utilisateurs
de [[https://www.gnu.org/software/emacs/][GNU Emacs]] à nous réunir
à *Paris* et à *Montpellier* pour apprendre les uns des autres : c'est
ouvert aux non-emacsiens, aux débutants, aux utilisateurs avancés et aux
vimistes !

** Liste de discussion et forum
   :PROPERTIES:
   :CUSTOM_ID: liste-de-discussion-et-forum
   :END:

Vous pouvez vous inscrire
sur [[https://emacs-doctor.com/lists/listinfo/ateliers-paris][la liste
de discussion]].

Nous avons aussi un [[https://emacs-doctor.com/forum/][forum]],
n'hésitez pas à échanger.

** Comment je m'inscris à un atelier ?
   :PROPERTIES:
   :CUSTOM_ID: comment-je-minscris-à-un-atelier
   :END:

*** Pour Paris
    :PROPERTIES:
    :CUSTOM_ID: pour-paris
    :END:

Nous faisons des rencontres en ligne. Il y a parfois des rencontres
physiques chez [[http://inno3.fr/][inno3.fr]] au 137 Boulevard de
Magenta 75010 Paris
([[http://www.openstreetmap.org/#map=16/48.8818/2.3514][plan]]) de 19h à
22h.

Si vous venez pour la première fois à un atelier IRL, envoyez un mot
à =bzg@bzg.fr=. Pour la visio, vous pouvez simplement débarquer.

*** Pour Montpellier
    :PROPERTIES:
    :CUSTOM_ID: pour-montpellier
    :END:

Envoyez un petit mot à =emacsem-owner@movoscope.org= et vous serez
inscrit.

** Rencontres passées
   :PROPERTIES:
   :CUSTOM_ID: rencontres-passées
   :END:

Nous gardons parfois des notes des soirées passées
sur [[https://gitlab.com/bzg2/emacsparis/blob/master/README.org][ce
dépôt]].


* M-x Research (contact them for password): TBA
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-03-04 Fri 07:00>--<2022-03-04 Fri 08:00>




* M-x Research (contact them for password): TBA
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-03-18 Fri 08:00>--<2022-03-18 Fri 09:00>




* Emacs APAC (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-apac.gitlab.io/
:END:
<2022-03-26 Sat 01:30>--<2022-03-26 Sat 03:30>

We are Emacs enthusiasts who live in the Asia-Pacific (APAC) time-zone.
We meet every fourth Saturday of the month.

** Where
   :PROPERTIES:
   :CUSTOM_ID: where
   :END:

The event is scheduled virtually using Jitsi Meet at 1400 Indian
Standard Time (IST). The meeting URL is posted on Freenode IRC
channels =#emacs=, =#ilugc= and =#emacsconf=, 30 minutes prior to the
meeting, and also on the [[https://www.freelists.org/list/ilugc][ILUGC
mailing list]] on the day of the meetup. If you are not subscribed, you
can also check
the [[https://www.freelists.org/archive/ilugc/][archive]].

Checkout the upcoming
meetings [[https://emacs-apac.gitlab.io/#upcoming][here]].

** Talks
   :PROPERTIES:
   :CUSTOM_ID: talks
   :END:

We usually have free flowing discussions around new Emacs packages /
features discovered, issues faced, experiences, usage tips, resources
for further learning etc. These are related to GNU Emacs and its
variants. Sometimes people also share their screens and give demos of
their Emacs setup and use.

If you would like to give a talk (20 minutes maximum), please send an
email to TODO with the details.

** Frequently Asked Questions
   :PROPERTIES:
   :CUSTOM_ID: frequently-asked-questions
   :END:

- *I'm new to Emacs, can / should I join?*
  Yes! You are always welcome. We have participants from different walks
  of life with varied experiences in Emacs. You can ask your questions
  and the attendees will be able to help, at least point you in the
  right direction.

- *Which language is used for communication?*
  English.

- *I'm not from APAC, can I join?*
  Definitely! If the timing is suitable for you, please join.




* Emacs Berlin (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-berlin.org/
:END:
<2022-03-30 Wed 09:30>--<2022-03-30 Wed 11:30>

[[https://emacs-berlin.org/]] 

New to Emacs? Longtime elisp expert? Just want to know what this is all
about? Come join us!

Location

Room open from 18:30 CET, if there are talks they'll start at 19:00 CET.
The video link will be posted on the day of the meetup to the mailing
list. Check the archive
([[https://mailb.org/pipermail/emacs-berlin/2021/thread.html]]) if you
are not subscribed.

About Emacs Berlin
We are Emacs enthusiasts in Berlin, meeting every last Wednesday of the
month.
The best way to stay posted is through our mailing list. Sign up
([[https://mailb.org/mailman/listinfo/emacs-berlin]]) and meet your
fellow Emacsers, or have a look at the mailing list archives
([[https://mailb.org/pipermail/emacs-berlin/]]) (gmane).
Feel free to send an email introducing yourself after subscribing!
You can also chat with us on irc: #emacs-berlin (connection instructions
([[https://mailb.org/pipermail/emacs-berlin/2020/000583.html]]))
Or on Twitter: @emacsberlin ([[https://twitter.com/emacsberlin]])
And there's a YouTube Channel
([[https://www.youtube.com/channel/UC1O8700SW-wuC4fvDEoGzOw]])  
And
on [[http://meetup.com/Emacs-Berlin-Meetup][meetup.com/Emacs-Berlin-Meetup]]
([[https://www.meetup.com/Emacs-Berlin-Meetup/]])
Non-public contact via email: organizers email
(mailto:[[mailto:emacs-berlin-owner@emacs-berlin.org][emacs-berlin-owner@emacs-berlin.org]])


* M-x Research (contact them for password): TBA
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-04-01 Fri 07:00>--<2022-04-01 Fri 08:00>




* Emacs Paris (virtual, in French)
:PROPERTIES:
:LOCATION: https://www.emacs-doctor.com/emacs-paris-user-group/
:END:
<2022-04-05 Tue 08:30>--<2022-04-05 Tue 10:00>

[[https://www.emacs-doctor.com/emacs-paris-user-group/]] 


Nous sommes quelques utilisateurs
de [[https://www.gnu.org/software/emacs/][GNU Emacs]] à nous réunir
à *Paris* et à *Montpellier* pour apprendre les uns des autres : c'est
ouvert aux non-emacsiens, aux débutants, aux utilisateurs avancés et aux
vimistes !

** Liste de discussion et forum
   :PROPERTIES:
   :CUSTOM_ID: liste-de-discussion-et-forum
   :END:

Vous pouvez vous inscrire
sur [[https://emacs-doctor.com/lists/listinfo/ateliers-paris][la liste
de discussion]].

Nous avons aussi un [[https://emacs-doctor.com/forum/][forum]],
n'hésitez pas à échanger.

** Comment je m'inscris à un atelier ?
   :PROPERTIES:
   :CUSTOM_ID: comment-je-minscris-à-un-atelier
   :END:

*** Pour Paris
    :PROPERTIES:
    :CUSTOM_ID: pour-paris
    :END:

Nous faisons des rencontres en ligne. Il y a parfois des rencontres
physiques chez [[http://inno3.fr/][inno3.fr]] au 137 Boulevard de
Magenta 75010 Paris
([[http://www.openstreetmap.org/#map=16/48.8818/2.3514][plan]]) de 19h à
22h.

Si vous venez pour la première fois à un atelier IRL, envoyez un mot
à =bzg@bzg.fr=. Pour la visio, vous pouvez simplement débarquer.

*** Pour Montpellier
    :PROPERTIES:
    :CUSTOM_ID: pour-montpellier
    :END:

Envoyez un petit mot à =emacsem-owner@movoscope.org= et vous serez
inscrit.

** Rencontres passées
   :PROPERTIES:
   :CUSTOM_ID: rencontres-passées
   :END:

Nous gardons parfois des notes des soirées passées
sur [[https://gitlab.com/bzg2/emacsparis/blob/master/README.org][ce
dépôt]].


* EmacsATX: TBD
:PROPERTIES:
:LOCATION: https://www.meetup.com/EmacsATX/events/hkckgsydcgbjb/
:END:
<2022-04-06 Wed 16:30>--<2022-04-06 Wed 18:30>

EmacsATX Wednesday, April 6 at 6:30 PM About Emacs ATX is a meetup
devoted to exploring the vast and ever expanding universe of the
extensible, customizable, free/libre editor Emacs. We are...
https://www.meetup.com/EmacsATX/events/hkckgsydcgbjb/


* M-x Research (contact them for password): TBA
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-04-15 Fri 07:00>--<2022-04-15 Fri 08:00>




* Emacs APAC (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-apac.gitlab.io/
:END:
<2022-04-23 Sat 01:30>--<2022-04-23 Sat 03:30>

We are Emacs enthusiasts who live in the Asia-Pacific (APAC) time-zone.
We meet every fourth Saturday of the month.

** Where
   :PROPERTIES:
   :CUSTOM_ID: where
   :END:

The event is scheduled virtually using Jitsi Meet at 1400 Indian
Standard Time (IST). The meeting URL is posted on Freenode IRC
channels =#emacs=, =#ilugc= and =#emacsconf=, 30 minutes prior to the
meeting, and also on the [[https://www.freelists.org/list/ilugc][ILUGC
mailing list]] on the day of the meetup. If you are not subscribed, you
can also check
the [[https://www.freelists.org/archive/ilugc/][archive]].

Checkout the upcoming
meetings [[https://emacs-apac.gitlab.io/#upcoming][here]].

** Talks
   :PROPERTIES:
   :CUSTOM_ID: talks
   :END:

We usually have free flowing discussions around new Emacs packages /
features discovered, issues faced, experiences, usage tips, resources
for further learning etc. These are related to GNU Emacs and its
variants. Sometimes people also share their screens and give demos of
their Emacs setup and use.

If you would like to give a talk (20 minutes maximum), please send an
email to TODO with the details.

** Frequently Asked Questions
   :PROPERTIES:
   :CUSTOM_ID: frequently-asked-questions
   :END:

- *I'm new to Emacs, can / should I join?*
  Yes! You are always welcome. We have participants from different walks
  of life with varied experiences in Emacs. You can ask your questions
  and the attendees will be able to help, at least point you in the
  right direction.

- *Which language is used for communication?*
  English.

- *I'm not from APAC, can I join?*
  Definitely! If the timing is suitable for you, please join.




* Emacs Berlin (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-berlin.org/
:END:
<2022-04-27 Wed 09:30>--<2022-04-27 Wed 11:30>

[[https://emacs-berlin.org/]] 

New to Emacs? Longtime elisp expert? Just want to know what this is all
about? Come join us!

Location

Room open from 18:30 CET, if there are talks they'll start at 19:00 CET.
The video link will be posted on the day of the meetup to the mailing
list. Check the archive
([[https://mailb.org/pipermail/emacs-berlin/2021/thread.html]]) if you
are not subscribed.

About Emacs Berlin
We are Emacs enthusiasts in Berlin, meeting every last Wednesday of the
month.
The best way to stay posted is through our mailing list. Sign up
([[https://mailb.org/mailman/listinfo/emacs-berlin]]) and meet your
fellow Emacsers, or have a look at the mailing list archives
([[https://mailb.org/pipermail/emacs-berlin/]]) (gmane).
Feel free to send an email introducing yourself after subscribing!
You can also chat with us on irc: #emacs-berlin (connection instructions
([[https://mailb.org/pipermail/emacs-berlin/2020/000583.html]]))
Or on Twitter: @emacsberlin ([[https://twitter.com/emacsberlin]])
And there's a YouTube Channel
([[https://www.youtube.com/channel/UC1O8700SW-wuC4fvDEoGzOw]])  
And
on [[http://meetup.com/Emacs-Berlin-Meetup][meetup.com/Emacs-Berlin-Meetup]]
([[https://www.meetup.com/Emacs-Berlin-Meetup/]])
Non-public contact via email: organizers email
(mailto:[[mailto:emacs-berlin-owner@emacs-berlin.org][emacs-berlin-owner@emacs-berlin.org]])


* EmacsATX: TBD
:PROPERTIES:
:LOCATION: https://www.meetup.com/EmacsATX/events/hkckgsydchbgb/
:END:
<2022-05-04 Wed 16:30>--<2022-05-04 Wed 18:30>

EmacsATX Wednesday, May 4 at 6:30 PM About Emacs ATX is a meetup devoted
to exploring the vast and ever expanding universe of the extensible,
customizable, free/libre editor Emacs. We are...
https://www.meetup.com/EmacsATX/events/hkckgsydchbgb/


* Emacs Paris (virtual, in French)
:PROPERTIES:
:LOCATION: https://www.emacs-doctor.com/emacs-paris-user-group/
:END:
<2022-05-05 Thu 08:30>--<2022-05-05 Thu 10:00>

[[https://www.emacs-doctor.com/emacs-paris-user-group/]] 


Nous sommes quelques utilisateurs
de [[https://www.gnu.org/software/emacs/][GNU Emacs]] à nous réunir
à *Paris* et à *Montpellier* pour apprendre les uns des autres : c'est
ouvert aux non-emacsiens, aux débutants, aux utilisateurs avancés et aux
vimistes !

** Liste de discussion et forum
   :PROPERTIES:
   :CUSTOM_ID: liste-de-discussion-et-forum
   :END:

Vous pouvez vous inscrire
sur [[https://emacs-doctor.com/lists/listinfo/ateliers-paris][la liste
de discussion]].

Nous avons aussi un [[https://emacs-doctor.com/forum/][forum]],
n'hésitez pas à échanger.

** Comment je m'inscris à un atelier ?
   :PROPERTIES:
   :CUSTOM_ID: comment-je-minscris-à-un-atelier
   :END:

*** Pour Paris
    :PROPERTIES:
    :CUSTOM_ID: pour-paris
    :END:

Nous faisons des rencontres en ligne. Il y a parfois des rencontres
physiques chez [[http://inno3.fr/][inno3.fr]] au 137 Boulevard de
Magenta 75010 Paris
([[http://www.openstreetmap.org/#map=16/48.8818/2.3514][plan]]) de 19h à
22h.

Si vous venez pour la première fois à un atelier IRL, envoyez un mot
à =bzg@bzg.fr=. Pour la visio, vous pouvez simplement débarquer.

*** Pour Montpellier
    :PROPERTIES:
    :CUSTOM_ID: pour-montpellier
    :END:

Envoyez un petit mot à =emacsem-owner@movoscope.org= et vous serez
inscrit.

** Rencontres passées
   :PROPERTIES:
   :CUSTOM_ID: rencontres-passées
   :END:

Nous gardons parfois des notes des soirées passées
sur [[https://gitlab.com/bzg2/emacsparis/blob/master/README.org][ce
dépôt]].


* M-x Research (contact them for password): TBA
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-05-06 Fri 07:00>--<2022-05-06 Fri 08:00>




* M-x Research (contact them for password): TBA
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-05-20 Fri 07:00>--<2022-05-20 Fri 08:00>




* Emacs Berlin (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-berlin.org/
:END:
<2022-05-25 Wed 09:30>--<2022-05-25 Wed 11:30>

[[https://emacs-berlin.org/]] 

New to Emacs? Longtime elisp expert? Just want to know what this is all
about? Come join us!

Location

Room open from 18:30 CET, if there are talks they'll start at 19:00 CET.
The video link will be posted on the day of the meetup to the mailing
list. Check the archive
([[https://mailb.org/pipermail/emacs-berlin/2021/thread.html]]) if you
are not subscribed.

About Emacs Berlin
We are Emacs enthusiasts in Berlin, meeting every last Wednesday of the
month.
The best way to stay posted is through our mailing list. Sign up
([[https://mailb.org/mailman/listinfo/emacs-berlin]]) and meet your
fellow Emacsers, or have a look at the mailing list archives
([[https://mailb.org/pipermail/emacs-berlin/]]) (gmane).
Feel free to send an email introducing yourself after subscribing!
You can also chat with us on irc: #emacs-berlin (connection instructions
([[https://mailb.org/pipermail/emacs-berlin/2020/000583.html]]))
Or on Twitter: @emacsberlin ([[https://twitter.com/emacsberlin]])
And there's a YouTube Channel
([[https://www.youtube.com/channel/UC1O8700SW-wuC4fvDEoGzOw]])  
And
on [[http://meetup.com/Emacs-Berlin-Meetup][meetup.com/Emacs-Berlin-Meetup]]
([[https://www.meetup.com/Emacs-Berlin-Meetup/]])
Non-public contact via email: organizers email
(mailto:[[mailto:emacs-berlin-owner@emacs-berlin.org][emacs-berlin-owner@emacs-berlin.org]])


* Emacs APAC (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-apac.gitlab.io/
:END:
<2022-05-28 Sat 01:30>--<2022-05-28 Sat 03:30>

We are Emacs enthusiasts who live in the Asia-Pacific (APAC) time-zone.
We meet every fourth Saturday of the month.

** Where
   :PROPERTIES:
   :CUSTOM_ID: where
   :END:

The event is scheduled virtually using Jitsi Meet at 1400 Indian
Standard Time (IST). The meeting URL is posted on Freenode IRC
channels =#emacs=, =#ilugc= and =#emacsconf=, 30 minutes prior to the
meeting, and also on the [[https://www.freelists.org/list/ilugc][ILUGC
mailing list]] on the day of the meetup. If you are not subscribed, you
can also check
the [[https://www.freelists.org/archive/ilugc/][archive]].

Checkout the upcoming
meetings [[https://emacs-apac.gitlab.io/#upcoming][here]].

** Talks
   :PROPERTIES:
   :CUSTOM_ID: talks
   :END:

We usually have free flowing discussions around new Emacs packages /
features discovered, issues faced, experiences, usage tips, resources
for further learning etc. These are related to GNU Emacs and its
variants. Sometimes people also share their screens and give demos of
their Emacs setup and use.

If you would like to give a talk (20 minutes maximum), please send an
email to TODO with the details.

** Frequently Asked Questions
   :PROPERTIES:
   :CUSTOM_ID: frequently-asked-questions
   :END:

- *I'm new to Emacs, can / should I join?*
  Yes! You are always welcome. We have participants from different walks
  of life with varied experiences in Emacs. You can ask your questions
  and the attendees will be able to help, at least point you in the
  right direction.

- *Which language is used for communication?*
  English.

- *I'm not from APAC, can I join?*
  Definitely! If the timing is suitable for you, please join.




* M-x Research (contact them for password): TBA
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-06-03 Fri 07:00>--<2022-06-03 Fri 08:00>




* Emacs Paris (virtual, in French)
:PROPERTIES:
:LOCATION: https://www.emacs-doctor.com/emacs-paris-user-group/
:END:
<2022-06-07 Tue 08:30>--<2022-06-07 Tue 10:00>

[[https://www.emacs-doctor.com/emacs-paris-user-group/]] 


Nous sommes quelques utilisateurs
de [[https://www.gnu.org/software/emacs/][GNU Emacs]] à nous réunir
à *Paris* et à *Montpellier* pour apprendre les uns des autres : c'est
ouvert aux non-emacsiens, aux débutants, aux utilisateurs avancés et aux
vimistes !

** Liste de discussion et forum
   :PROPERTIES:
   :CUSTOM_ID: liste-de-discussion-et-forum
   :END:

Vous pouvez vous inscrire
sur [[https://emacs-doctor.com/lists/listinfo/ateliers-paris][la liste
de discussion]].

Nous avons aussi un [[https://emacs-doctor.com/forum/][forum]],
n'hésitez pas à échanger.

** Comment je m'inscris à un atelier ?
   :PROPERTIES:
   :CUSTOM_ID: comment-je-minscris-à-un-atelier
   :END:

*** Pour Paris
    :PROPERTIES:
    :CUSTOM_ID: pour-paris
    :END:

Nous faisons des rencontres en ligne. Il y a parfois des rencontres
physiques chez [[http://inno3.fr/][inno3.fr]] au 137 Boulevard de
Magenta 75010 Paris
([[http://www.openstreetmap.org/#map=16/48.8818/2.3514][plan]]) de 19h à
22h.

Si vous venez pour la première fois à un atelier IRL, envoyez un mot
à =bzg@bzg.fr=. Pour la visio, vous pouvez simplement débarquer.

*** Pour Montpellier
    :PROPERTIES:
    :CUSTOM_ID: pour-montpellier
    :END:

Envoyez un petit mot à =emacsem-owner@movoscope.org= et vous serez
inscrit.

** Rencontres passées
   :PROPERTIES:
   :CUSTOM_ID: rencontres-passées
   :END:

Nous gardons parfois des notes des soirées passées
sur [[https://gitlab.com/bzg2/emacsparis/blob/master/README.org][ce
dépôt]].


* M-x Research (contact them for password): TBA
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-06-17 Fri 07:00>--<2022-06-17 Fri 08:00>




* Emacs APAC (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-apac.gitlab.io/
:END:
<2022-06-25 Sat 01:30>--<2022-06-25 Sat 03:30>

We are Emacs enthusiasts who live in the Asia-Pacific (APAC) time-zone.
We meet every fourth Saturday of the month.

** Where
   :PROPERTIES:
   :CUSTOM_ID: where
   :END:

The event is scheduled virtually using Jitsi Meet at 1400 Indian
Standard Time (IST). The meeting URL is posted on Freenode IRC
channels =#emacs=, =#ilugc= and =#emacsconf=, 30 minutes prior to the
meeting, and also on the [[https://www.freelists.org/list/ilugc][ILUGC
mailing list]] on the day of the meetup. If you are not subscribed, you
can also check
the [[https://www.freelists.org/archive/ilugc/][archive]].

Checkout the upcoming
meetings [[https://emacs-apac.gitlab.io/#upcoming][here]].

** Talks
   :PROPERTIES:
   :CUSTOM_ID: talks
   :END:

We usually have free flowing discussions around new Emacs packages /
features discovered, issues faced, experiences, usage tips, resources
for further learning etc. These are related to GNU Emacs and its
variants. Sometimes people also share their screens and give demos of
their Emacs setup and use.

If you would like to give a talk (20 minutes maximum), please send an
email to TODO with the details.

** Frequently Asked Questions
   :PROPERTIES:
   :CUSTOM_ID: frequently-asked-questions
   :END:

- *I'm new to Emacs, can / should I join?*
  Yes! You are always welcome. We have participants from different walks
  of life with varied experiences in Emacs. You can ask your questions
  and the attendees will be able to help, at least point you in the
  right direction.

- *Which language is used for communication?*
  English.

- *I'm not from APAC, can I join?*
  Definitely! If the timing is suitable for you, please join.




* Emacs Berlin (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-berlin.org/
:END:
<2022-06-29 Wed 09:30>--<2022-06-29 Wed 11:30>

[[https://emacs-berlin.org/]] 

New to Emacs? Longtime elisp expert? Just want to know what this is all
about? Come join us!

Location

Room open from 18:30 CET, if there are talks they'll start at 19:00 CET.
The video link will be posted on the day of the meetup to the mailing
list. Check the archive
([[https://mailb.org/pipermail/emacs-berlin/2021/thread.html]]) if you
are not subscribed.

About Emacs Berlin
We are Emacs enthusiasts in Berlin, meeting every last Wednesday of the
month.
The best way to stay posted is through our mailing list. Sign up
([[https://mailb.org/mailman/listinfo/emacs-berlin]]) and meet your
fellow Emacsers, or have a look at the mailing list archives
([[https://mailb.org/pipermail/emacs-berlin/]]) (gmane).
Feel free to send an email introducing yourself after subscribing!
You can also chat with us on irc: #emacs-berlin (connection instructions
([[https://mailb.org/pipermail/emacs-berlin/2020/000583.html]]))
Or on Twitter: @emacsberlin ([[https://twitter.com/emacsberlin]])
And there's a YouTube Channel
([[https://www.youtube.com/channel/UC1O8700SW-wuC4fvDEoGzOw]])  
And
on [[http://meetup.com/Emacs-Berlin-Meetup][meetup.com/Emacs-Berlin-Meetup]]
([[https://www.meetup.com/Emacs-Berlin-Meetup/]])
Non-public contact via email: organizers email
(mailto:[[mailto:emacs-berlin-owner@emacs-berlin.org][emacs-berlin-owner@emacs-berlin.org]])


* M-x Research (contact them for password): TBA
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-07-01 Fri 07:00>--<2022-07-01 Fri 08:00>




* Emacs Paris (virtual, in French)
:PROPERTIES:
:LOCATION: https://www.emacs-doctor.com/emacs-paris-user-group/
:END:
<2022-07-07 Thu 08:30>--<2022-07-07 Thu 10:00>

[[https://www.emacs-doctor.com/emacs-paris-user-group/]] 


Nous sommes quelques utilisateurs
de [[https://www.gnu.org/software/emacs/][GNU Emacs]] à nous réunir
à *Paris* et à *Montpellier* pour apprendre les uns des autres : c'est
ouvert aux non-emacsiens, aux débutants, aux utilisateurs avancés et aux
vimistes !

** Liste de discussion et forum
   :PROPERTIES:
   :CUSTOM_ID: liste-de-discussion-et-forum
   :END:

Vous pouvez vous inscrire
sur [[https://emacs-doctor.com/lists/listinfo/ateliers-paris][la liste
de discussion]].

Nous avons aussi un [[https://emacs-doctor.com/forum/][forum]],
n'hésitez pas à échanger.

** Comment je m'inscris à un atelier ?
   :PROPERTIES:
   :CUSTOM_ID: comment-je-minscris-à-un-atelier
   :END:

*** Pour Paris
    :PROPERTIES:
    :CUSTOM_ID: pour-paris
    :END:

Nous faisons des rencontres en ligne. Il y a parfois des rencontres
physiques chez [[http://inno3.fr/][inno3.fr]] au 137 Boulevard de
Magenta 75010 Paris
([[http://www.openstreetmap.org/#map=16/48.8818/2.3514][plan]]) de 19h à
22h.

Si vous venez pour la première fois à un atelier IRL, envoyez un mot
à =bzg@bzg.fr=. Pour la visio, vous pouvez simplement débarquer.

*** Pour Montpellier
    :PROPERTIES:
    :CUSTOM_ID: pour-montpellier
    :END:

Envoyez un petit mot à =emacsem-owner@movoscope.org= et vous serez
inscrit.

** Rencontres passées
   :PROPERTIES:
   :CUSTOM_ID: rencontres-passées
   :END:

Nous gardons parfois des notes des soirées passées
sur [[https://gitlab.com/bzg2/emacsparis/blob/master/README.org][ce
dépôt]].


* M-x Research (contact them for password): TBA
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-07-15 Fri 07:00>--<2022-07-15 Fri 08:00>




* Emacs APAC (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-apac.gitlab.io/
:END:
<2022-07-23 Sat 01:30>--<2022-07-23 Sat 03:30>

We are Emacs enthusiasts who live in the Asia-Pacific (APAC) time-zone.
We meet every fourth Saturday of the month.

** Where
   :PROPERTIES:
   :CUSTOM_ID: where
   :END:

The event is scheduled virtually using Jitsi Meet at 1400 Indian
Standard Time (IST). The meeting URL is posted on Freenode IRC
channels =#emacs=, =#ilugc= and =#emacsconf=, 30 minutes prior to the
meeting, and also on the [[https://www.freelists.org/list/ilugc][ILUGC
mailing list]] on the day of the meetup. If you are not subscribed, you
can also check
the [[https://www.freelists.org/archive/ilugc/][archive]].

Checkout the upcoming
meetings [[https://emacs-apac.gitlab.io/#upcoming][here]].

** Talks
   :PROPERTIES:
   :CUSTOM_ID: talks
   :END:

We usually have free flowing discussions around new Emacs packages /
features discovered, issues faced, experiences, usage tips, resources
for further learning etc. These are related to GNU Emacs and its
variants. Sometimes people also share their screens and give demos of
their Emacs setup and use.

If you would like to give a talk (20 minutes maximum), please send an
email to TODO with the details.

** Frequently Asked Questions
   :PROPERTIES:
   :CUSTOM_ID: frequently-asked-questions
   :END:

- *I'm new to Emacs, can / should I join?*
  Yes! You are always welcome. We have participants from different walks
  of life with varied experiences in Emacs. You can ask your questions
  and the attendees will be able to help, at least point you in the
  right direction.

- *Which language is used for communication?*
  English.

- *I'm not from APAC, can I join?*
  Definitely! If the timing is suitable for you, please join.




* Emacs Berlin (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-berlin.org/
:END:
<2022-07-27 Wed 09:30>--<2022-07-27 Wed 11:30>

[[https://emacs-berlin.org/]] 

New to Emacs? Longtime elisp expert? Just want to know what this is all
about? Come join us!

Location

Room open from 18:30 CET, if there are talks they'll start at 19:00 CET.
The video link will be posted on the day of the meetup to the mailing
list. Check the archive
([[https://mailb.org/pipermail/emacs-berlin/2021/thread.html]]) if you
are not subscribed.

About Emacs Berlin
We are Emacs enthusiasts in Berlin, meeting every last Wednesday of the
month.
The best way to stay posted is through our mailing list. Sign up
([[https://mailb.org/mailman/listinfo/emacs-berlin]]) and meet your
fellow Emacsers, or have a look at the mailing list archives
([[https://mailb.org/pipermail/emacs-berlin/]]) (gmane).
Feel free to send an email introducing yourself after subscribing!
You can also chat with us on irc: #emacs-berlin (connection instructions
([[https://mailb.org/pipermail/emacs-berlin/2020/000583.html]]))
Or on Twitter: @emacsberlin ([[https://twitter.com/emacsberlin]])
And there's a YouTube Channel
([[https://www.youtube.com/channel/UC1O8700SW-wuC4fvDEoGzOw]])  
And
on [[http://meetup.com/Emacs-Berlin-Meetup][meetup.com/Emacs-Berlin-Meetup]]
([[https://www.meetup.com/Emacs-Berlin-Meetup/]])
Non-public contact via email: organizers email
(mailto:[[mailto:emacs-berlin-owner@emacs-berlin.org][emacs-berlin-owner@emacs-berlin.org]])


* Emacs Paris (virtual, in French)
:PROPERTIES:
:LOCATION: https://www.emacs-doctor.com/emacs-paris-user-group/
:END:
<2022-08-02 Tue 08:30>--<2022-08-02 Tue 10:00>

[[https://www.emacs-doctor.com/emacs-paris-user-group/]] 


Nous sommes quelques utilisateurs
de [[https://www.gnu.org/software/emacs/][GNU Emacs]] à nous réunir
à *Paris* et à *Montpellier* pour apprendre les uns des autres : c'est
ouvert aux non-emacsiens, aux débutants, aux utilisateurs avancés et aux
vimistes !

** Liste de discussion et forum
   :PROPERTIES:
   :CUSTOM_ID: liste-de-discussion-et-forum
   :END:

Vous pouvez vous inscrire
sur [[https://emacs-doctor.com/lists/listinfo/ateliers-paris][la liste
de discussion]].

Nous avons aussi un [[https://emacs-doctor.com/forum/][forum]],
n'hésitez pas à échanger.

** Comment je m'inscris à un atelier ?
   :PROPERTIES:
   :CUSTOM_ID: comment-je-minscris-à-un-atelier
   :END:

*** Pour Paris
    :PROPERTIES:
    :CUSTOM_ID: pour-paris
    :END:

Nous faisons des rencontres en ligne. Il y a parfois des rencontres
physiques chez [[http://inno3.fr/][inno3.fr]] au 137 Boulevard de
Magenta 75010 Paris
([[http://www.openstreetmap.org/#map=16/48.8818/2.3514][plan]]) de 19h à
22h.

Si vous venez pour la première fois à un atelier IRL, envoyez un mot
à =bzg@bzg.fr=. Pour la visio, vous pouvez simplement débarquer.

*** Pour Montpellier
    :PROPERTIES:
    :CUSTOM_ID: pour-montpellier
    :END:

Envoyez un petit mot à =emacsem-owner@movoscope.org= et vous serez
inscrit.

** Rencontres passées
   :PROPERTIES:
   :CUSTOM_ID: rencontres-passées
   :END:

Nous gardons parfois des notes des soirées passées
sur [[https://gitlab.com/bzg2/emacsparis/blob/master/README.org][ce
dépôt]].


* M-x Research (contact them for password): TBA
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-08-05 Fri 07:00>--<2022-08-05 Fri 08:00>




* M-x Research (contact them for password): TBA
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-08-19 Fri 07:00>--<2022-08-19 Fri 08:00>




* Emacs APAC (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-apac.gitlab.io/
:END:
<2022-08-27 Sat 01:30>--<2022-08-27 Sat 03:30>

We are Emacs enthusiasts who live in the Asia-Pacific (APAC) time-zone.
We meet every fourth Saturday of the month.

** Where
   :PROPERTIES:
   :CUSTOM_ID: where
   :END:

The event is scheduled virtually using Jitsi Meet at 1400 Indian
Standard Time (IST). The meeting URL is posted on Freenode IRC
channels =#emacs=, =#ilugc= and =#emacsconf=, 30 minutes prior to the
meeting, and also on the [[https://www.freelists.org/list/ilugc][ILUGC
mailing list]] on the day of the meetup. If you are not subscribed, you
can also check
the [[https://www.freelists.org/archive/ilugc/][archive]].

Checkout the upcoming
meetings [[https://emacs-apac.gitlab.io/#upcoming][here]].

** Talks
   :PROPERTIES:
   :CUSTOM_ID: talks
   :END:

We usually have free flowing discussions around new Emacs packages /
features discovered, issues faced, experiences, usage tips, resources
for further learning etc. These are related to GNU Emacs and its
variants. Sometimes people also share their screens and give demos of
their Emacs setup and use.

If you would like to give a talk (20 minutes maximum), please send an
email to TODO with the details.

** Frequently Asked Questions
   :PROPERTIES:
   :CUSTOM_ID: frequently-asked-questions
   :END:

- *I'm new to Emacs, can / should I join?*
  Yes! You are always welcome. We have participants from different walks
  of life with varied experiences in Emacs. You can ask your questions
  and the attendees will be able to help, at least point you in the
  right direction.

- *Which language is used for communication?*
  English.

- *I'm not from APAC, can I join?*
  Definitely! If the timing is suitable for you, please join.




* Emacs Berlin (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-berlin.org/
:END:
<2022-08-31 Wed 09:30>--<2022-08-31 Wed 11:30>

[[https://emacs-berlin.org/]] 

New to Emacs? Longtime elisp expert? Just want to know what this is all
about? Come join us!

Location

Room open from 18:30 CET, if there are talks they'll start at 19:00 CET.
The video link will be posted on the day of the meetup to the mailing
list. Check the archive
([[https://mailb.org/pipermail/emacs-berlin/2021/thread.html]]) if you
are not subscribed.

About Emacs Berlin
We are Emacs enthusiasts in Berlin, meeting every last Wednesday of the
month.
The best way to stay posted is through our mailing list. Sign up
([[https://mailb.org/mailman/listinfo/emacs-berlin]]) and meet your
fellow Emacsers, or have a look at the mailing list archives
([[https://mailb.org/pipermail/emacs-berlin/]]) (gmane).
Feel free to send an email introducing yourself after subscribing!
You can also chat with us on irc: #emacs-berlin (connection instructions
([[https://mailb.org/pipermail/emacs-berlin/2020/000583.html]]))
Or on Twitter: @emacsberlin ([[https://twitter.com/emacsberlin]])
And there's a YouTube Channel
([[https://www.youtube.com/channel/UC1O8700SW-wuC4fvDEoGzOw]])  
And
on [[http://meetup.com/Emacs-Berlin-Meetup][meetup.com/Emacs-Berlin-Meetup]]
([[https://www.meetup.com/Emacs-Berlin-Meetup/]])
Non-public contact via email: organizers email
(mailto:[[mailto:emacs-berlin-owner@emacs-berlin.org][emacs-berlin-owner@emacs-berlin.org]])


* Emacs Paris (virtual, in French)
:PROPERTIES:
:LOCATION: https://www.emacs-doctor.com/emacs-paris-user-group/
:END:
<2022-09-01 Thu 08:30>--<2022-09-01 Thu 10:00>

[[https://www.emacs-doctor.com/emacs-paris-user-group/]] 


Nous sommes quelques utilisateurs
de [[https://www.gnu.org/software/emacs/][GNU Emacs]] à nous réunir
à *Paris* et à *Montpellier* pour apprendre les uns des autres : c'est
ouvert aux non-emacsiens, aux débutants, aux utilisateurs avancés et aux
vimistes !

** Liste de discussion et forum
   :PROPERTIES:
   :CUSTOM_ID: liste-de-discussion-et-forum
   :END:

Vous pouvez vous inscrire
sur [[https://emacs-doctor.com/lists/listinfo/ateliers-paris][la liste
de discussion]].

Nous avons aussi un [[https://emacs-doctor.com/forum/][forum]],
n'hésitez pas à échanger.

** Comment je m'inscris à un atelier ?
   :PROPERTIES:
   :CUSTOM_ID: comment-je-minscris-à-un-atelier
   :END:

*** Pour Paris
    :PROPERTIES:
    :CUSTOM_ID: pour-paris
    :END:

Nous faisons des rencontres en ligne. Il y a parfois des rencontres
physiques chez [[http://inno3.fr/][inno3.fr]] au 137 Boulevard de
Magenta 75010 Paris
([[http://www.openstreetmap.org/#map=16/48.8818/2.3514][plan]]) de 19h à
22h.

Si vous venez pour la première fois à un atelier IRL, envoyez un mot
à =bzg@bzg.fr=. Pour la visio, vous pouvez simplement débarquer.

*** Pour Montpellier
    :PROPERTIES:
    :CUSTOM_ID: pour-montpellier
    :END:

Envoyez un petit mot à =emacsem-owner@movoscope.org= et vous serez
inscrit.

** Rencontres passées
   :PROPERTIES:
   :CUSTOM_ID: rencontres-passées
   :END:

Nous gardons parfois des notes des soirées passées
sur [[https://gitlab.com/bzg2/emacsparis/blob/master/README.org][ce
dépôt]].


* M-x Research (contact them for password): TBA
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-09-02 Fri 07:00>--<2022-09-02 Fri 08:00>




* M-x Research (contact them for password): TBA
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-09-16 Fri 07:00>--<2022-09-16 Fri 08:00>




* Emacs APAC (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-apac.gitlab.io/
:END:
<2022-09-24 Sat 01:30>--<2022-09-24 Sat 03:30>

We are Emacs enthusiasts who live in the Asia-Pacific (APAC) time-zone.
We meet every fourth Saturday of the month.

** Where
   :PROPERTIES:
   :CUSTOM_ID: where
   :END:

The event is scheduled virtually using Jitsi Meet at 1400 Indian
Standard Time (IST). The meeting URL is posted on Freenode IRC
channels =#emacs=, =#ilugc= and =#emacsconf=, 30 minutes prior to the
meeting, and also on the [[https://www.freelists.org/list/ilugc][ILUGC
mailing list]] on the day of the meetup. If you are not subscribed, you
can also check
the [[https://www.freelists.org/archive/ilugc/][archive]].

Checkout the upcoming
meetings [[https://emacs-apac.gitlab.io/#upcoming][here]].

** Talks
   :PROPERTIES:
   :CUSTOM_ID: talks
   :END:

We usually have free flowing discussions around new Emacs packages /
features discovered, issues faced, experiences, usage tips, resources
for further learning etc. These are related to GNU Emacs and its
variants. Sometimes people also share their screens and give demos of
their Emacs setup and use.

If you would like to give a talk (20 minutes maximum), please send an
email to TODO with the details.

** Frequently Asked Questions
   :PROPERTIES:
   :CUSTOM_ID: frequently-asked-questions
   :END:

- *I'm new to Emacs, can / should I join?*
  Yes! You are always welcome. We have participants from different walks
  of life with varied experiences in Emacs. You can ask your questions
  and the attendees will be able to help, at least point you in the
  right direction.

- *Which language is used for communication?*
  English.

- *I'm not from APAC, can I join?*
  Definitely! If the timing is suitable for you, please join.




* Emacs Berlin (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-berlin.org/
:END:
<2022-09-28 Wed 09:30>--<2022-09-28 Wed 11:30>

[[https://emacs-berlin.org/]] 

New to Emacs? Longtime elisp expert? Just want to know what this is all
about? Come join us!

Location

Room open from 18:30 CET, if there are talks they'll start at 19:00 CET.
The video link will be posted on the day of the meetup to the mailing
list. Check the archive
([[https://mailb.org/pipermail/emacs-berlin/2021/thread.html]]) if you
are not subscribed.

About Emacs Berlin
We are Emacs enthusiasts in Berlin, meeting every last Wednesday of the
month.
The best way to stay posted is through our mailing list. Sign up
([[https://mailb.org/mailman/listinfo/emacs-berlin]]) and meet your
fellow Emacsers, or have a look at the mailing list archives
([[https://mailb.org/pipermail/emacs-berlin/]]) (gmane).
Feel free to send an email introducing yourself after subscribing!
You can also chat with us on irc: #emacs-berlin (connection instructions
([[https://mailb.org/pipermail/emacs-berlin/2020/000583.html]]))
Or on Twitter: @emacsberlin ([[https://twitter.com/emacsberlin]])
And there's a YouTube Channel
([[https://www.youtube.com/channel/UC1O8700SW-wuC4fvDEoGzOw]])  
And
on [[http://meetup.com/Emacs-Berlin-Meetup][meetup.com/Emacs-Berlin-Meetup]]
([[https://www.meetup.com/Emacs-Berlin-Meetup/]])
Non-public contact via email: organizers email
(mailto:[[mailto:emacs-berlin-owner@emacs-berlin.org][emacs-berlin-owner@emacs-berlin.org]])


* Emacs Paris (virtual, in French)
:PROPERTIES:
:LOCATION: https://www.emacs-doctor.com/emacs-paris-user-group/
:END:
<2022-10-04 Tue 08:30>--<2022-10-04 Tue 10:00>

[[https://www.emacs-doctor.com/emacs-paris-user-group/]] 


Nous sommes quelques utilisateurs
de [[https://www.gnu.org/software/emacs/][GNU Emacs]] à nous réunir
à *Paris* et à *Montpellier* pour apprendre les uns des autres : c'est
ouvert aux non-emacsiens, aux débutants, aux utilisateurs avancés et aux
vimistes !

** Liste de discussion et forum
   :PROPERTIES:
   :CUSTOM_ID: liste-de-discussion-et-forum
   :END:

Vous pouvez vous inscrire
sur [[https://emacs-doctor.com/lists/listinfo/ateliers-paris][la liste
de discussion]].

Nous avons aussi un [[https://emacs-doctor.com/forum/][forum]],
n'hésitez pas à échanger.

** Comment je m'inscris à un atelier ?
   :PROPERTIES:
   :CUSTOM_ID: comment-je-minscris-à-un-atelier
   :END:

*** Pour Paris
    :PROPERTIES:
    :CUSTOM_ID: pour-paris
    :END:

Nous faisons des rencontres en ligne. Il y a parfois des rencontres
physiques chez [[http://inno3.fr/][inno3.fr]] au 137 Boulevard de
Magenta 75010 Paris
([[http://www.openstreetmap.org/#map=16/48.8818/2.3514][plan]]) de 19h à
22h.

Si vous venez pour la première fois à un atelier IRL, envoyez un mot
à =bzg@bzg.fr=. Pour la visio, vous pouvez simplement débarquer.

*** Pour Montpellier
    :PROPERTIES:
    :CUSTOM_ID: pour-montpellier
    :END:

Envoyez un petit mot à =emacsem-owner@movoscope.org= et vous serez
inscrit.

** Rencontres passées
   :PROPERTIES:
   :CUSTOM_ID: rencontres-passées
   :END:

Nous gardons parfois des notes des soirées passées
sur [[https://gitlab.com/bzg2/emacsparis/blob/master/README.org][ce
dépôt]].


* M-x Research (contact them for password): TBA
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-10-07 Fri 07:00>--<2022-10-07 Fri 08:00>




* M-x Research (contact them for password): TBA
:PROPERTIES:
:LOCATION: https://m-x-research.github.io/
:END:
<2022-10-21 Fri 07:00>--<2022-10-21 Fri 08:00>




* Emacs APAC (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-apac.gitlab.io/
:END:
<2022-10-22 Sat 01:30>--<2022-10-22 Sat 03:30>

We are Emacs enthusiasts who live in the Asia-Pacific (APAC) time-zone.
We meet every fourth Saturday of the month.

** Where
   :PROPERTIES:
   :CUSTOM_ID: where
   :END:

The event is scheduled virtually using Jitsi Meet at 1400 Indian
Standard Time (IST). The meeting URL is posted on Freenode IRC
channels =#emacs=, =#ilugc= and =#emacsconf=, 30 minutes prior to the
meeting, and also on the [[https://www.freelists.org/list/ilugc][ILUGC
mailing list]] on the day of the meetup. If you are not subscribed, you
can also check
the [[https://www.freelists.org/archive/ilugc/][archive]].

Checkout the upcoming
meetings [[https://emacs-apac.gitlab.io/#upcoming][here]].

** Talks
   :PROPERTIES:
   :CUSTOM_ID: talks
   :END:

We usually have free flowing discussions around new Emacs packages /
features discovered, issues faced, experiences, usage tips, resources
for further learning etc. These are related to GNU Emacs and its
variants. Sometimes people also share their screens and give demos of
their Emacs setup and use.

If you would like to give a talk (20 minutes maximum), please send an
email to TODO with the details.

** Frequently Asked Questions
   :PROPERTIES:
   :CUSTOM_ID: frequently-asked-questions
   :END:

- *I'm new to Emacs, can / should I join?*
  Yes! You are always welcome. We have participants from different walks
  of life with varied experiences in Emacs. You can ask your questions
  and the attendees will be able to help, at least point you in the
  right direction.

- *Which language is used for communication?*
  English.

- *I'm not from APAC, can I join?*
  Definitely! If the timing is suitable for you, please join.




