* EmacsATX: Eshell and Emacs Social
:PROPERTIES:
:LOCATION: https://www.meetup.com/EmacsATX/events/276034038/
:END:
<2021-02-04 Thu 08:30>--<2021-02-04 Thu 10:30>

https://www.meetup.com/EmacsATX/events/276034038/ About Emacs ATX is a
meetup devoted to exploring the vast and ever expanding universe of the
extensible, customizable, free/libre editor Emacs. We are also a support
group for people with Emacs-related issues. Our goal is to make everyone
more productive. Come practice your Emacs Fu with us! Infosession Shad
will demonstrate eshell, a shell-like command interpreter implemented in
Emacs Lisp We'll have time available for discussion and other topics if
anyone would like to present. Hosting Many thanks to Webex for providing
a space for our meeting.


* Emacs Berlin (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-berlin.org/
:END:
<2021-02-25 Thu 01:30>--<2021-02-25 Thu 03:30>

[[https://emacs-berlin.org/]] \\
\\
New to Emacs? Longtime elisp expert? Just want to know what this is all
about? Come join us!\\
\\
Location\\
\\
Room open from 18:30 CET, if there are talks they'll start at 19:00 CET.
The video link will be posted on the day of the meetup to the mailing
list. Check the archive
([[https://mailb.org/pipermail/emacs-berlin/2021/thread.html]]) if you
are not subscribed.\\
\\
About Emacs Berlin\\
We are Emacs enthusiasts in Berlin, meeting every last Wednesday of the
month (<%%(diary-float t 3 -1)> in org-mode).\\
The best way to stay posted is through our mailing list. Sign up
([[https://mailb.org/mailman/listinfo/emacs-berlin]]) and meet your
fellow Emacsers, or have a look at the mailing list archives
([[https://mailb.org/pipermail/emacs-berlin/]]) (gmane).\\
Feel free to send an email introducing yourself after subscribing!\\
You can also chat with us on irc: #emacs-berlin (connection instructions
([[https://mailb.org/pipermail/emacs-berlin/2020/000583.html]]))\\
Or on Twitter: @emacsberlin ([[https://twitter.com/emacsberlin]])\\
And there's a YouTube Channel
([[https://www.youtube.com/channel/UC1O8700SW-wuC4fvDEoGzOw]])  \\
And
on [[http://meetup.com/Emacs-Berlin-Meetup][meetup.com/Emacs-Berlin-Meetup]]
([[https://www.meetup.com/Emacs-Berlin-Meetup/]])\\
Non-public contact via email: organizers email
(mailto:[[mailto:emacs-berlin-owner@emacs-berlin.org][emacs-berlin-owner@emacs-berlin.org]])


* EmacsFFM: Creating our own major mode (virtual)
:PROPERTIES:
:LOCATION: https://www.meetup.com/emacs-ffm/events/275881281/
:END:
<2021-02-18 Thu 03:00>--<2021-02-18 Thu 05:00>

https://www.meetup.com/emacs-ffm/events/275881281/\\
\\

\\
\\
This time, we will try out Discord as our video conference platform.
Stay tuned!\\
\\
You can join the Discord chat **right now** and say hi! No need to wait
until the next meetup :)\\
\\
------\\
\\
About\\
\\
This is a meetup for all people working with and interested in Emacs.\\
\\
We want to meet up in a friendly atmosphere to talk about the famous
text editor.

\\
\\



* EmacsSF: discussion of emacs, org-mode, org-roam and similar packages
:PROPERTIES:
:LOCATION: https://www.meetup.com/Emacs-SF/events/275889079/
:END:
<2021-01-28 Thu 10:30>--<2021-01-28 Thu 12:30>

[[https://www.meetup.com/Emacs-SF/events/275889079/]]\\
\\
Let's get together virtually to discuss emacs, org-mode, org-roam, etc.
If you have something to demo related to any of the above, please let me
know. Hopefully people who cannot attend weekend meetups can attend this
weekday evening meetup.\\
\\
Join the meetup
via [[https://www.meetup.com/Emacs-SF/events/275889079/]] in order to
get the link to the online meeting.


* EmacsNYC: Lightning Talks
:PROPERTIES:
:LOCATION: https://emacsnyc.org/2021/01/23/monthly-online-meetup-lightning-talks.html
:END:
<2021-02-02 Tue 08:00>--<2021-02-02 Tue 10:00>

https://emacsnyc.org/2021/01/23/monthly-online-meetup-lightning-talks.html\\
\\

*** Monthly Online Meetup---Lightning Talks
    :PROPERTIES:
    :CUSTOM_ID: monthly-online-meetuplightning-talks
    :END:

Monday, Feb 1, 2021\\
7:00 PM

Join us online: [[https://meet.jit.si/EmacsNYC][meet.jit.si/EmacsNYC]]\\
Please join us using your favorite IRC client at #emacsnyc or
use [[https://webchat.freenode.net/][webchat.freenode.net]] to join us
online.

This month we are doing lightning talks!

We look forward to any talk you want to give that is Emacs or Emacs
adjacent.

We do want to hear everything you have to say, but we will be limiting
each talk to 5 minutes and we will be strict about this. If you have
more to say please consider talking to us about doing a longer talk next
month.

Please sign
up [[https://etherpad.wikimedia.org/p/Emacs_NYC_February_2021_Lightning_Talks][here]].

If there is additional room and you are interested in speaking we will
try to accommodate you as best as possible.

If you would like to speak then or on any other occasion, take a look at
this [[https://emacsnyc.org/giving-a-talk.html][guide]].


* EmacsSG: Emacs and Never Code Alone (tentative?)
:PROPERTIES:
:LOCATION: https://www.meetup.com/Emacs-SG/events/268260076/
:END:
<2021-01-27 Wed 19:00>--<2021-01-27 Wed 22:00>

[[https://www.meetup.com/Emacs-SG/events/268260076/]]\\
\\
There hasn't been much activity here for quite a while but hopefully we
can bring some Nix along to the Never Code Alone SG event when Covid
allows is to meet up in person.\\
\\
The
event: [[https://www.meetup.com/Never-Code-Alone-SG/events/268135071/]]


* Emacs APAC (virtual, in English)
:PROPERTIES:
:LOCATION: https://emacs-apac.gitlab.io/
:END:
<2021-01-23 Sat 16:30>--<2021-01-23 Sat 18:30>

[[https://emacs-apac.gitlab.io/]]\\
\\
================\\
== Emacs APAC ==\\
================Welcome to Emacs Asia-Pacific\\
Start. Upcoming events.\\
About Emacs APAC\\
We are Emacs enthusiasts who live in the Asia-Pacific (APAC) time-zone.
We meet every fourth Saturday of the month (<%%(diary-float t 6 4)> in
Org mode).\\
\\
Where\\
The event is scheduled virtually using Jitsi Meet at 1400 Indian
Standard Time (IST). The meeting URL is posted on Freenode IRC channels
#emacs, #ilugc and #emacsconf, 30 minutes prior to the meeting, and also
on the ILUGC mailing list on the day of the meetup. If you are not
subscribed, you can also check the archive.\\
\\
Checkout the upcoming meetings here.\\
\\
Talks\\
We usually have free flowing discussions around new Emacs packages /
features discovered, issues faced, experiences, usage tips, resources
for further learning etc. These are related to GNU Emacs and its
variants. Sometimes people also share their screens and give demos of
their Emacs setup and use.\\
\\
If you would like to give a talk (20 minutes maximum), please send an
email to TODO with the details.\\
\\
Frequently Asked Questions\\
I'm new to Emacs, can / should I join?\\
Yes! You are always welcome. We have participants from different walks
of life with varied experiences in Emacs. You can ask your questions and
the attendees will be able to help, at least point you in the right
direction.\\
\\
Which language is used for communication?\\
English.\\
\\
I'm not from APAC, can I join?\\
Definitely! If the timing is suitable for you, please join.


* Emacs Paris (virtual)
:PROPERTIES:
:LOCATION: https://www.emacs-doctor.com/emacs-paris-user-group/
:END:
<2021-02-03 Wed 00:30>--<2021-02-03 Wed 02:00>

[[https://www.emacs-doctor.com/emacs-paris-user-group/]] \\
\\

Nous sommes quelques utilisateurs
de [[https://www.gnu.org/software/emacs/][GNU Emacs]] à nous réunir
à *Paris* et à *Montpellier* pour apprendre les uns des autres : c'est
ouvert aux non-emacsiens, aux débutants, aux utilisateurs avancés et aux
vimistes !

** Liste de discussion et forum
   :PROPERTIES:
   :CUSTOM_ID: liste-de-discussion-et-forum
   :END:

Vous pouvez vous inscrire
sur [[https://emacs-doctor.com/lists/listinfo/ateliers-paris][la liste
de discussion]].

Nous avons aussi un [[https://emacs-doctor.com/forum/][forum]],
n'hésitez pas à échanger.

** Prochaines rencontres
   :PROPERTIES:
   :CUSTOM_ID: prochaines-rencontres
   :END:

- Paris : mardi 8 décembre 2020 de 17h30 à 19h en visio
- Paris : jeudi 7 janvier 2021 de 17h30 à 19h en visio
- Paris : mardi 2 février 2021 de 17h30 à 19h en visio
- Paris : jeudi 4 mars 2021 de 17h30 à 19h en visio
- Paris : mardi 6 avril 2021 de 17h30 à 19h en visio
- Paris : jeudi 6 mai 2021 de 17h30 à 19h en visio
- Paris : mardi 1 juin 2021 de 17h30 à 19h en visio
- Montpellier : à définir

\\

** Comment je m'inscris à un atelier ?
   :PROPERTIES:
   :CUSTOM_ID: comment-je-minscris-à-un-atelier
   :END:

*** Pour Paris
    :PROPERTIES:
    :CUSTOM_ID: pour-paris
    :END:

Nous faisons des rencontres en ligne. Il y a parfois des rencontres
physiques chez [[http://inno3.fr/][inno3.fr]] au 137 Boulevard de
Magenta 75010 Paris
([[http://www.openstreetmap.org/#map=16/48.8818/2.3514][plan]]) de 19h à
22h.

Si vous venez pour la première fois à un atelier IRL, envoyez un mot
à =bzg@bzg.fr=. Pour la visio, vous pouvez simplement débarquer.

*** Pour Montpellier
    :PROPERTIES:
    :CUSTOM_ID: pour-montpellier
    :END:

Envoyez un petit mot à =emacsem-owner@movoscope.org= et vous serez
inscrit.

** Rencontres passées
   :PROPERTIES:
   :CUSTOM_ID: rencontres-passées
   :END:

Nous gardons parfois des notes des soirées passées
sur [[https://gitlab.com/bzg2/emacsparis/blob/master/README.org][ce
dépôt]].

\\


* EmacsFFM: Creating our own major mode (virtual)
:PROPERTIES:
:LOCATION: https://www.meetup.com/emacs-ffm/events/275226261/
:END:
<2021-01-21 Thu 03:00>--<2021-01-21 Thu 05:00>

[[https://www.meetup.com/emacs-ffm/events/275226261/]]\\
\\
In this meeting, we shall continue with the creation of our own major
mode. We will be using this repository to create our mode:\\
[[https://github.com/UndeadKernel/refman-mode]]\\
Feel free to clone the repository to start working on it.\\
\\
Let me know if this works for you and feel free to share any ideas how
to make the virtual version of this user group work :)\\
\\
------\\
\\
Right now, we go with jitsi as our video conference platform, but we
might give discord a try as well. Stay tuned!\\
\\
------\\
\\
About\\
\\
This is a meetup for all people working with and interested in Emacs.\\
\\
We want to meet up in a friendly atmosphere to talk about the famous
text editor.


* Livestream: Keeping organized with Emacs and Orgmode, by Henrique Castro
:PROPERTIES:
:LOCATION: https://www.youtube.com/watch?v=RvTuHsMPVLo
:END:
<2021-01-14 Thu 23:30>--<2021-01-15 Fri 00:30>

Watch live: [[https://www.youtube.com/watch?v=RvTuHsMPVLo]]


* Emacs Paris (virtual)
:PROPERTIES:
:LOCATION: https://www.emacs-doctor.com/emacs-paris-user-group/ 
:END:
<2021-01-08 Fri 00:30>--<2021-01-08 Fri 02:00>

[[https://www.emacs-doctor.com/emacs-paris-user-group/]] \\
\\

Nous sommes quelques utilisateurs
de [[https://www.gnu.org/software/emacs/][GNU Emacs]] à nous réunir
à *Paris* et à *Montpellier* pour apprendre les uns des autres : c'est
ouvert aux non-emacsiens, aux débutants, aux utilisateurs avancés et aux
vimistes !

** Liste de discussion et forum
   :PROPERTIES:
   :CUSTOM_ID: liste-de-discussion-et-forum
   :END:

Vous pouvez vous inscrire
sur [[https://emacs-doctor.com/lists/listinfo/ateliers-paris][la liste
de discussion]].

Nous avons aussi un [[https://emacs-doctor.com/forum/][forum]],
n'hésitez pas à échanger.

** Prochaines rencontres
   :PROPERTIES:
   :CUSTOM_ID: prochaines-rencontres
   :END:

- Paris : mardi 8 décembre 2020 de 17h30 à 19h en visio
- Paris : jeudi 7 janvier 2021 de 17h30 à 19h en visio
- Paris : mardi 2 février 2021 de 17h30 à 19h en visio
- Paris : jeudi 4 mars 2021 de 17h30 à 19h en visio
- Paris : mardi 6 avril 2021 de 17h30 à 19h en visio
- Paris : jeudi 6 mai 2021 de 17h30 à 19h en visio
- Paris : mardi 1 juin 2021 de 17h30 à 19h en visio
- Montpellier : à définir

\\

** Comment je m'inscris à un atelier ?
   :PROPERTIES:
   :CUSTOM_ID: comment-je-minscris-à-un-atelier
   :END:

*** Pour Paris
    :PROPERTIES:
    :CUSTOM_ID: pour-paris
    :END:

Nous faisons des rencontres en ligne. Il y a parfois des rencontres
physiques chez [[http://inno3.fr/][inno3.fr]] au 137 Boulevard de
Magenta 75010 Paris
([[http://www.openstreetmap.org/#map=16/48.8818/2.3514][plan]]) de 19h à
22h.

Si vous venez pour la première fois à un atelier IRL, envoyez un mot
à =bzg@bzg.fr=. Pour la visio, vous pouvez simplement débarquer.

*** Pour Montpellier
    :PROPERTIES:
    :CUSTOM_ID: pour-montpellier
    :END:

Envoyez un petit mot à =emacsem-owner@movoscope.org= et vous serez
inscrit.

** Rencontres passées
   :PROPERTIES:
   :CUSTOM_ID: rencontres-passées
   :END:

Nous gardons parfois des notes des soirées passées
sur [[https://gitlab.com/bzg2/emacsparis/blob/master/README.org][ce
dépôt]].

\\


* EmacsNYC: How Do We Improve Emacs? (virtual)
:PROPERTIES:
:LOCATION: https://emacsnyc.org/2020/12/28/online-meetup-discussionhow-do-we-improve-emacs.html
:END:
<2021-01-05 Tue 08:00>--<2021-01-05 Tue 10:00>

[[https://emacsnyc.org/2020/12/28/online-meetup-discussionhow-do-we-improve-emacs.html]]\\
\\
Join us online: [[http://meet.jit.si/EmacsNYC][meet.jit.si/EmacsNYC]]\\
Please join us using your favorite IRC client at #emacsnyc or use
[[http://webchat.freenode.net][webchat.freenode.net]] to join us
online.\\
\\
We're excited to have you join us for EmacsNYC a group of dedicated
lambda enthusiasts that come together once a month to share our mutual
joy of a piece of software that's over 40 years old.\\
\\
Whether you are first time user, long time contributor, software
developer, writer, or just curious what this is all about, you will find
an open and welcome community that is eager for you to be a part.\\
\\
To create an environment that is welcoming, harrassment-free, and
enjoyable to everyone, we have a code-of-conduct that we following for
every get together.\\
\\
Emacs, relative to most software is old and has seen many iterations.
Recently there was a survey that was conducted that helps us understand
the current state of the world for Emacs.\\
\\
Let's talk about how we can take what we know from the past and what we
know now to help develop Emacs to a brighter future. This conversation
can go in any number of directions and we will see where the
conversation runs its course.


* Emacs Paris (virtual)
:PROPERTIES:
:LOCATION: 
:END:
<2021-06-01 Tue 23:30>--<2021-06-02 Wed 01:00>

[[https://www.emacs-doctor.com/emacs-paris-user-group/]] \\
\\

Nous sommes quelques utilisateurs
de [[https://www.gnu.org/software/emacs/][GNU Emacs]] à nous réunir
à *Paris* et à *Montpellier* pour apprendre les uns des autres : c'est
ouvert aux non-emacsiens, aux débutants, aux utilisateurs avancés et aux
vimistes !

** Liste de discussion et forum
   :PROPERTIES:
   :CUSTOM_ID: liste-de-discussion-et-forum
   :END:

Vous pouvez vous inscrire
sur [[https://emacs-doctor.com/lists/listinfo/ateliers-paris][la liste
de discussion]].

Nous avons aussi un [[https://emacs-doctor.com/forum/][forum]],
n'hésitez pas à échanger.

** Prochaines rencontres
   :PROPERTIES:
   :CUSTOM_ID: prochaines-rencontres
   :END:

- Paris : mardi 8 décembre 2020 de 17h30 à 19h en visio
- Paris : jeudi 7 janvier 2021 de 17h30 à 19h en visio
- Paris : mardi 2 février 2021 de 17h30 à 19h en visio
- Paris : jeudi 4 mars 2021 de 17h30 à 19h en visio
- Paris : mardi 6 avril 2021 de 17h30 à 19h en visio
- Paris : jeudi 6 mai 2021 de 17h30 à 19h en visio
- Paris : mardi 1 juin 2021 de 17h30 à 19h en visio
- Montpellier : à définir

\\

** Comment je m'inscris à un atelier ?
   :PROPERTIES:
   :CUSTOM_ID: comment-je-minscris-à-un-atelier
   :END:

*** Pour Paris
    :PROPERTIES:
    :CUSTOM_ID: pour-paris
    :END:

Nous faisons des rencontres en ligne. Il y a parfois des rencontres
physiques chez [[http://inno3.fr/][inno3.fr]] au 137 Boulevard de
Magenta 75010 Paris
([[http://www.openstreetmap.org/#map=16/48.8818/2.3514][plan]]) de 19h à
22h.

Si vous venez pour la première fois à un atelier IRL, envoyez un mot
à =bzg@bzg.fr=. Pour la visio, vous pouvez simplement débarquer.

*** Pour Montpellier
    :PROPERTIES:
    :CUSTOM_ID: pour-montpellier
    :END:

Envoyez un petit mot à =emacsem-owner@movoscope.org= et vous serez
inscrit.

** Rencontres passées
   :PROPERTIES:
   :CUSTOM_ID: rencontres-passées
   :END:

Nous gardons parfois des notes des soirées passées
sur [[https://gitlab.com/bzg2/emacsparis/blob/master/README.org][ce
dépôt]].

\\


* Emacs Paris (virtual)
:PROPERTIES:
:LOCATION: 
:END:
<2021-05-06 Thu 23:30>--<2021-05-07 Fri 01:00>

[[https://www.emacs-doctor.com/emacs-paris-user-group/]] \\
\\

Nous sommes quelques utilisateurs
de [[https://www.gnu.org/software/emacs/][GNU Emacs]] à nous réunir
à *Paris* et à *Montpellier* pour apprendre les uns des autres : c'est
ouvert aux non-emacsiens, aux débutants, aux utilisateurs avancés et aux
vimistes !

** Liste de discussion et forum
   :PROPERTIES:
   :CUSTOM_ID: liste-de-discussion-et-forum
   :END:

Vous pouvez vous inscrire
sur [[https://emacs-doctor.com/lists/listinfo/ateliers-paris][la liste
de discussion]].

Nous avons aussi un [[https://emacs-doctor.com/forum/][forum]],
n'hésitez pas à échanger.

** Prochaines rencontres
   :PROPERTIES:
   :CUSTOM_ID: prochaines-rencontres
   :END:

- Paris : mardi 8 décembre 2020 de 17h30 à 19h en visio
- Paris : jeudi 7 janvier 2021 de 17h30 à 19h en visio
- Paris : mardi 2 février 2021 de 17h30 à 19h en visio
- Paris : jeudi 4 mars 2021 de 17h30 à 19h en visio
- Paris : mardi 6 avril 2021 de 17h30 à 19h en visio
- Paris : jeudi 6 mai 2021 de 17h30 à 19h en visio
- Paris : mardi 1 juin 2021 de 17h30 à 19h en visio
- Montpellier : à définir

\\

** Comment je m'inscris à un atelier ?
   :PROPERTIES:
   :CUSTOM_ID: comment-je-minscris-à-un-atelier
   :END:

*** Pour Paris
    :PROPERTIES:
    :CUSTOM_ID: pour-paris
    :END:

Nous faisons des rencontres en ligne. Il y a parfois des rencontres
physiques chez [[http://inno3.fr/][inno3.fr]] au 137 Boulevard de
Magenta 75010 Paris
([[http://www.openstreetmap.org/#map=16/48.8818/2.3514][plan]]) de 19h à
22h.

Si vous venez pour la première fois à un atelier IRL, envoyez un mot
à =bzg@bzg.fr=. Pour la visio, vous pouvez simplement débarquer.

*** Pour Montpellier
    :PROPERTIES:
    :CUSTOM_ID: pour-montpellier
    :END:

Envoyez un petit mot à =emacsem-owner@movoscope.org= et vous serez
inscrit.

** Rencontres passées
   :PROPERTIES:
   :CUSTOM_ID: rencontres-passées
   :END:

Nous gardons parfois des notes des soirées passées
sur [[https://gitlab.com/bzg2/emacsparis/blob/master/README.org][ce
dépôt]].

\\


* Emacs Paris (virtual)
:PROPERTIES:
:LOCATION: 
:END:
<2021-04-06 Tue 23:30>--<2021-04-07 Wed 01:00>

[[https://www.emacs-doctor.com/emacs-paris-user-group/]] \\
\\

Nous sommes quelques utilisateurs
de [[https://www.gnu.org/software/emacs/][GNU Emacs]] à nous réunir
à *Paris* et à *Montpellier* pour apprendre les uns des autres : c'est
ouvert aux non-emacsiens, aux débutants, aux utilisateurs avancés et aux
vimistes !

** Liste de discussion et forum
   :PROPERTIES:
   :CUSTOM_ID: liste-de-discussion-et-forum
   :END:

Vous pouvez vous inscrire
sur [[https://emacs-doctor.com/lists/listinfo/ateliers-paris][la liste
de discussion]].

Nous avons aussi un [[https://emacs-doctor.com/forum/][forum]],
n'hésitez pas à échanger.

** Prochaines rencontres
   :PROPERTIES:
   :CUSTOM_ID: prochaines-rencontres
   :END:

- Paris : mardi 8 décembre 2020 de 17h30 à 19h en visio
- Paris : jeudi 7 janvier 2021 de 17h30 à 19h en visio
- Paris : mardi 2 février 2021 de 17h30 à 19h en visio
- Paris : jeudi 4 mars 2021 de 17h30 à 19h en visio
- Paris : mardi 6 avril 2021 de 17h30 à 19h en visio
- Paris : jeudi 6 mai 2021 de 17h30 à 19h en visio
- Paris : mardi 1 juin 2021 de 17h30 à 19h en visio
- Montpellier : à définir

\\

** Comment je m'inscris à un atelier ?
   :PROPERTIES:
   :CUSTOM_ID: comment-je-minscris-à-un-atelier
   :END:

*** Pour Paris
    :PROPERTIES:
    :CUSTOM_ID: pour-paris
    :END:

Nous faisons des rencontres en ligne. Il y a parfois des rencontres
physiques chez [[http://inno3.fr/][inno3.fr]] au 137 Boulevard de
Magenta 75010 Paris
([[http://www.openstreetmap.org/#map=16/48.8818/2.3514][plan]]) de 19h à
22h.

Si vous venez pour la première fois à un atelier IRL, envoyez un mot
à =bzg@bzg.fr=. Pour la visio, vous pouvez simplement débarquer.

*** Pour Montpellier
    :PROPERTIES:
    :CUSTOM_ID: pour-montpellier
    :END:

Envoyez un petit mot à =emacsem-owner@movoscope.org= et vous serez
inscrit.

** Rencontres passées
   :PROPERTIES:
   :CUSTOM_ID: rencontres-passées
   :END:

Nous gardons parfois des notes des soirées passées
sur [[https://gitlab.com/bzg2/emacsparis/blob/master/README.org][ce
dépôt]].

\\


* Emacs Paris (virtual)
:PROPERTIES:
:LOCATION: 
:END:
<2021-03-05 Fri 00:30>--<2021-03-05 Fri 02:00>

[[https://www.emacs-doctor.com/emacs-paris-user-group/]] \\
\\

Nous sommes quelques utilisateurs
de [[https://www.gnu.org/software/emacs/][GNU Emacs]] à nous réunir
à *Paris* et à *Montpellier* pour apprendre les uns des autres : c'est
ouvert aux non-emacsiens, aux débutants, aux utilisateurs avancés et aux
vimistes !

** Liste de discussion et forum
   :PROPERTIES:
   :CUSTOM_ID: liste-de-discussion-et-forum
   :END:

Vous pouvez vous inscrire
sur [[https://emacs-doctor.com/lists/listinfo/ateliers-paris][la liste
de discussion]].

Nous avons aussi un [[https://emacs-doctor.com/forum/][forum]],
n'hésitez pas à échanger.

** Prochaines rencontres
   :PROPERTIES:
   :CUSTOM_ID: prochaines-rencontres
   :END:

- Paris : mardi 8 décembre 2020 de 17h30 à 19h en visio
- Paris : jeudi 7 janvier 2021 de 17h30 à 19h en visio
- Paris : mardi 2 février 2021 de 17h30 à 19h en visio
- Paris : jeudi 4 mars 2021 de 17h30 à 19h en visio
- Paris : mardi 6 avril 2021 de 17h30 à 19h en visio
- Paris : jeudi 6 mai 2021 de 17h30 à 19h en visio
- Paris : mardi 1 juin 2021 de 17h30 à 19h en visio
- Montpellier : à définir

\\

** Comment je m'inscris à un atelier ?
   :PROPERTIES:
   :CUSTOM_ID: comment-je-minscris-à-un-atelier
   :END:

*** Pour Paris
    :PROPERTIES:
    :CUSTOM_ID: pour-paris
    :END:

Nous faisons des rencontres en ligne. Il y a parfois des rencontres
physiques chez [[http://inno3.fr/][inno3.fr]] au 137 Boulevard de
Magenta 75010 Paris
([[http://www.openstreetmap.org/#map=16/48.8818/2.3514][plan]]) de 19h à
22h.

Si vous venez pour la première fois à un atelier IRL, envoyez un mot
à =bzg@bzg.fr=. Pour la visio, vous pouvez simplement débarquer.

*** Pour Montpellier
    :PROPERTIES:
    :CUSTOM_ID: pour-montpellier
    :END:

Envoyez un petit mot à =emacsem-owner@movoscope.org= et vous serez
inscrit.

** Rencontres passées
   :PROPERTIES:
   :CUSTOM_ID: rencontres-passées
   :END:

Nous gardons parfois des notes des soirées passées
sur [[https://gitlab.com/bzg2/emacsparis/blob/master/README.org][ce
dépôt]].

\\


