#+TITLE: Emacs calendar

* Actions  :noexport:

#+CALL: sync() :results none :eval never-export

#+begin_src emacs-lisp :noweb yes :results silent
<<announce>>
(defun my/prepare-calendar-for-export ()
  (interactive)
  (goto-char (point-min))
  (re-search-forward "#\\+NAME: event-summary")
  (org-ctrl-c-ctrl-c)
  (org-export-to-file 'html "README.html")
  (when my/laptop-p
    (org-babel-goto-named-result "event-summary")
    (re-search-forward "^- ")
    (goto-char (match-beginning 0))
    (let ((events (org-babel-read-result)))
      (oddmuse-edit "EmacsWiki" "Usergroups")
      (goto-char (point-min))
      (delete-region (progn (re-search-forward "== Upcoming events ==\n\n") (match-end 0))
                     (progn (re-search-forward "^$") (match-beginning 0)))
      (save-excursion (insert (mapconcat (lambda (s) (concat "* " (car s) "\n")) events ""))))))
(my/prepare-calendar-for-export)
(org-export-to-file 'html "README.html")
(unless my/laptop-p (my/schedule-announcements-for-upcoming-emacs-meetups))
#+end_src

(find-file "~/sync/emacs-news/index.org")
[[elisp:(org-export-to-file 'html "README.html")]]
[[elisp:my/schedule-announcements-for-upcoming-emacs-meetups]]

* Upcoming events

#+NAME: event-summary
#+CALL: update() :results output drawer :eval never-export 

#+RESULTS: event-summary
:results:

Error with url: https://www.meetup.com/Chicago-Emacs-User-Group/events/ical/
Error with url: https://www.meetup.com/Princeton-Emacs/events/ical/
- Emacs Berlin (virtual, in English) https://emacs-berlin.org/ Wed Apr 28 0930 Vancouver / 1130 Chicago / 1230 Toronto / 1630 GMT / 1830 Berlin / 2200 Kolkata -- Thu Apr 29 0030 Singapore
- Frankfurt: Emacs FFM Meetup! April 2021 https://www.meetup.com/emacs-ffm/events/277606530/ Wed Apr 28 1000 Vancouver / 1200 Chicago / 1300 Toronto / 1700 GMT / 1900 Berlin / 2230 Kolkata -- Thu Apr 29 0100 Singapore
- EmacsSF: Emacs Lisp: Foundational Utility Packages https://www.meetup.com/Emacs-SF/events/277722919/ Thu Apr 29 1000 Vancouver / 1200 Chicago / 1300 Toronto / 1700 GMT / 1900 Berlin / 2230 Kolkata -- Fri Apr 30 0100 Singapore
- EmacsNYC: Monthly Online Meetup - Lightning Talks https://www.meetup.com/New-York-Emacs-Meetup/events/277390026/ Mon May 3 1600 Vancouver / 1800 Chicago / 1900 Toronto / 2300 GMT -- Tue May 4 0100 Berlin / 0430 Kolkata / 0700 Singapore
- EmacsATX: TBD https://www.meetup.com/EmacsATX/events/hkckgsycchbhb/ Wed May 5 1630 Vancouver / 1830 Chicago / 1930 Toronto / 2330 GMT -- Thu May 6 0130 Berlin / 0500 Kolkata / 0730 Singapore
- M-x Research (virtual, contact them for passcode) https://m-x-research.github.io/ Thu May 6 0700 Vancouver / 0900 Chicago / 1000 Toronto / 1400 GMT / 1600 Berlin / 1930 Kolkata / 2200 Singapore
- Emacs Paris (virtual) https://www.emacs-doctor.com/emacs-paris-user-group/ Thu May 6 0830 Vancouver / 1030 Chicago / 1130 Toronto / 1530 GMT / 1730 Berlin / 2100 Kolkata / 2330 Singapore
- M-x Research (virtual, contact them for passcode) https://m-x-research.github.io/ Thu May 20 0700 Vancouver / 0900 Chicago / 1000 Toronto / 1400 GMT / 1600 Berlin / 1930 Kolkata / 2200 Singapore
- Emacs APAC (virtual, in English) https://emacs-apac.gitlab.io/ Sat May 22 0130 Vancouver / 0330 Chicago / 0430 Toronto / 0830 GMT / 1030 Berlin / 1400 Kolkata / 1630 Singapore
- Singapore: Emacs & Never Code Alone SG https://www.meetup.com/Emacs-SG/events/268260076/ Wed May 26 0400 Vancouver / 0600 Chicago / 0700 Toronto / 1100 GMT / 1300 Berlin / 1630 Kolkata / 1900 Singapore
- Emacs Berlin (virtual, in English) https://emacs-berlin.org/ Wed May 26 0930 Vancouver / 1130 Chicago / 1230 Toronto / 1630 GMT / 1830 Berlin / 2200 Kolkata -- Thu May 27 0030 Singapore
- Emacs Paris (virtual) https://www.emacs-doctor.com/emacs-paris-user-group/ Tue Jun 1 0830 Vancouver / 1030 Chicago / 1130 Toronto / 1530 GMT / 1730 Berlin / 2100 Kolkata / 2330 Singapore
- EmacsATX: TBD https://www.meetup.com/EmacsATX/events/hkckgsyccjbdb/ Wed Jun 2 1630 Vancouver / 1830 Chicago / 1930 Toronto / 2330 GMT -- Thu Jun 3 0130 Berlin / 0500 Kolkata / 0730 Singapore
- M-x Research (virtual, contact them for passcode) https://m-x-research.github.io/ Thu Jun 3 0700 Vancouver / 0900 Chicago / 1000 Toronto / 1400 GMT / 1600 Berlin / 1930 Kolkata / 2200 Singapore
:end:


* Introduction
  
This calendar is maintained by [[mailto:sacha@sachachua.com][sacha@sachachua.com]]. You can find it at https://emacslife.com/calendar/

You can find a list of upcoming events and other meet-ups at
https://www.emacswiki.org/emacs/Usergroups.

Or you can add this iCal to your calendar program:

[[https://emacslife.com/calendar/emacs-calendar.ics]]

Or you view the following HTML calendars:

#+begin_src emacs-lisp :exports results :var timezones=timezones :results list
  (mapcar (lambda (o) (org-link-make-string (format "file:emacs-calendar-%s.html" (downcase (replace-regexp-in-string "^.*?/" "" (car o)))) (car o))) timezones)
#+end_src

#+RESULTS:
- [[file:emacs-calendar-gmt.html][Etc/GMT]]
- [[file:emacs-calendar-vancouver.html][America/Vancouver]]
- [[file:emacs-calendar-chicago.html][America/Chicago]]
- [[file:emacs-calendar-toronto.html][America/Toronto]]
- [[file:emacs-calendar-kolkata.html][Asia/Kolkata]]
- [[file:emacs-calendar-shanghai.html][Asia/Shanghai]]
- [[file:emacs-calendar-singapore.html][Asia/Singapore]]
- [[file:emacs-calendar-berlin.html][Europe/Berlin]]

(Let me know if you want me to add yours! - [[mailto:sacha@sachachua.com]])

Or you periodically download and include one of these files in your Org agenda files:

#+begin_src emacs-lisp :exports results :var timezones=timezones :wrap export html
(concat "<ul>"
   (mapconcat (lambda (o) (let ((file (concat "emacs-calendar-" (downcase (replace-regexp-in-string "^.*?/" "" (car o))) ".org")))
                         (format "<li><a href=\"%s\">%s</a></li>" file file)))
           timezones "\n")
"</ul>")
#+end_src

#+RESULTS:
#+begin_export html
<ul><li><a href="emacs-calendar-gmt.org">emacs-calendar-gmt.org</a></li>
<li><a href="emacs-calendar-vancouver.org">emacs-calendar-vancouver.org</a></li>
<li><a href="emacs-calendar-chicago.org">emacs-calendar-chicago.org</a></li>
<li><a href="emacs-calendar-toronto.org">emacs-calendar-toronto.org</a></li>
<li><a href="emacs-calendar-kolkata.org">emacs-calendar-kolkata.org</a></li>
<li><a href="emacs-calendar-shanghai.org">emacs-calendar-shanghai.org</a></li>
<li><a href="emacs-calendar-singapore.org">emacs-calendar-singapore.org</a></li>
<li><a href="emacs-calendar-berlin.org">emacs-calendar-berlin.org</a></li></ul>
#+end_export

Enjoy!

* Code I use to run it
** Timezones

#+NAME: timezones
- America/Vancouver
- America/Chicago
- America/Toronto
- Etc/GMT
- Europe/Berlin
- Asia/Kolkata
- Asia/Singapore

** Download and parse the iCal file with Python

#+begin_src sh :results silent :eval never-export
pip3 install icalevents recurring_ical_events pypandoc
#+end_src

#+NAME: update
#+begin_src python :session "cal" :results output drawer :var timezones=timezones :tangle "update.py" :eval never-export
from urllib.request import urlopen
from icalendar import Calendar
from datetime import date, datetime
from dateutil.relativedelta import *
import recurring_ical_events
import pytz
import re
import pypandoc
import subprocess
import sys
import csv

other_meetups = {'EmacsNYC': 'New-York-Emacs-Meetup',
                 'EmacsSF': 'Emacs-SF',
                 'EmacsATX': 'EmacsATX',
                 'Boulder': 'Boulder-Emacs-Meetup',
                 'DC': 'NOVA-EMACS',
                 'Pelotas, Brazil': 'Pelotas-Emacs-Meetup',
                 'Sao Paulo': 'Grupo-de-usuarios-de-Emacs-de-Sao-Paulo',
                 'Frankfurt': 'emacs-ffm',
                 'London Emacs Hacking': 'London-Emacs-Hacking',
                 'London Emacs Lisp': 'London-Emacs-Lisp-Meetup',
                 'Stockholm': 'Stockholm-Emacs-Meetup',
                 'Madrid': 'Emacs-Madrid',
                 'Finland': 'Finland-Emacs-User-Group',
                 'Amsterdam': 'Amsterdam-Emacs-Users-Group',
                 'GenEmacs': 'GenEmacs',
                 'Johannesburg': 'Jozi-Emacs-Meetup',
                 'Singapore': 'Emacs-SG',
                 'Delhi': 'Emacs-Delhi',
                 'Pune': 'the-peg'}
# https://www.meetup.com/Emacs-SF/events/ical/',

def summarized_event(e, timezones):
  times = [[e['DTSTART'].dt.astimezone(pytz.timezone(t[0])), t[0], e['DTSTART'].dt.astimezone(pytz.timezone(t[0])).utcoffset()] for t in timezones]
  times.sort(key=lambda x: x[2])
  s = ""
  for i, t in enumerate(times):
    if i == 0 or t[0].day != times[i - 1][0].day:
       if i > 0:
         s += " -- "
       s += t[0].strftime('%a %b %-d %H%M') + " " + re.sub('^.*?/', '', t[1])
    else:
       s += " / " + t[0].strftime('%H%M') + " " + re.sub('^.*?/', '', t[1])
  return "- %s %s %s" % (e['SUMMARY'], e['LOCATION'], s)
                     

link = "https://calendar.google.com/calendar/ical/c_rkq3fc6u8k1nem23qegqc90l6c%40group.calendar.google.com/public/basic.ics"
f = urlopen(link)
cal = Calendar.from_ical(f.read())
start_date = date(date.today().year, date.today().month, 1)
end_date = date(date.today().year + 1, date.today().month + 1, 1)

for event in cal.walk():
  if event.name == 'VEVENT':
    if event.get('location') == '':
      match = re.search(r'href="([^"]+)"', event.get('description'))
      if not match:
        match = re.search('^(http.*?)(&nbsp;|<br>|\n)', event.get('description'))
      if match:                 
        event['location'] = match.group(1)
      else:
        print(event.get('description'))
                        

def merge_meetup_events(cal):
  global other_meetups
  for name, identifier in other_meetups.items():
    url = "https://www.meetup.com/%s/events/ical/" % (identifier)
    try:
      meetup_cal = Calendar.from_ical(urlopen(url).read())
    except:
      print("Error with url: %s" % url)
      continue
    meetup_events = recurring_ical_events.of(meetup_cal).between(start_date, end_date)
    for event in meetup_events:
      event['SUMMARY'] = name + ': ' + event['SUMMARY']
      event['LOCATION'] = event['URL']
      cal.add_component(event)
     
merge_meetup_events(cal)
f = open('emacs-calendar.ics', 'wb')
f.write(cal.to_ical())
f.close()

events = recurring_ical_events.of(cal).between(start_date, end_date)
events.sort(key=lambda x: x['DTSTART'].dt)
files = {}
org_date = "%Y-%m-%d %a %H:%M" # 2006-11-01 Wed 19:15
# Prepare string for copying
highlight_start = datetime.utcnow()
highlight_end = datetime.utcnow() + relativedelta(weeks=+6)

for t in timezones:
  stub = "emacs-calendar-" + re.sub('^.*?/', '', t[0]).lower()
  ical_args = ["ical2html", "-l", "-f", "Times are in " + t[0], "-z", t[0], datetime.today().strftime("%Y%m01"), "P8W", "emacs-calendar.ics"]
  output = subprocess.check_output(ical_args).decode(sys.stdout.encoding)
  changed = re.sub(r'<span class=summary>([^<]+)</span>\n<pre><b class=location>([^<]+)</b></pre>',
                   r'<span class="summary"><a href="\2">\1</a></span>', output)
  f = open(stub + '.html', 'wb')
  f.write(changed.encode(sys.stdout.encoding))
  f.close()
  files[t[0]] = open(stub + '.org', "w")

with open('events.csv', 'w', newline='') as csvfile:
  fieldnames = ['DTSTART', 'DTEND', 'LOCATION', 'SUMMARY', 'TEXT']
  writer = csv.DictWriter(csvfile, fieldnames=fieldnames, extrasaction='ignore')
  writer.writeheader()
  for e in events:
    writer.writerow({**e,
                     'DTSTART': e['DTSTART'].dt.isoformat(),
                     'DTEND': e['DTEND'].dt.isoformat(),
                     'TEXT': summarized_event(e, timezones)
                     })
    
for e in events:
  desc = pypandoc.convert_text(e['DESCRIPTION'], 'org', format='html').replace('\\\\', '')
  utc = datetime.utcfromtimestamp(e['DTSTART'].dt.timestamp())
  if utc >= highlight_start and utc <= highlight_end:
    print(summarized_event(e, timezones))
  for t in timezones:
    zone = pytz.timezone(t[0])
    start = e['DTSTART'].dt.astimezone(zone)
    end = e['DTEND'].dt.astimezone(zone)
    files[t[0]].write("""* %s
:PROPERTIES:
:LOCATION: %s
:END:
<%s>--<%s>

%s

""" % (e['SUMMARY'], e['LOCATION'], start.strftime(org_date), end.strftime(org_date), desc))

#+end_src

#+RESULTS: update
:results:

Error with url: https://www.meetup.com/Chicago-Emacs-User-Group/events/ical/
Error with url: https://www.meetup.com/Princeton-Emacs/events/ical/
- Emacs Berlin (virtual, in English) https://emacs-berlin.org/ Wed Apr 28 0930 Vancouver / 1130 Chicago / 1230 Toronto / 1630 GMT / 1830 Berlin / 2200 Kolkata -- Thu Apr 29 0030 Singapore
- Frankfurt: Emacs FFM Meetup! April 2021 https://www.meetup.com/emacs-ffm/events/277606530/ Wed Apr 28 1000 Vancouver / 1200 Chicago / 1300 Toronto / 1700 GMT / 1900 Berlin / 2230 Kolkata -- Thu Apr 29 0100 Singapore
- EmacsSF: Emacs Lisp: Foundational Utility Packages https://www.meetup.com/Emacs-SF/events/277722919/ Thu Apr 29 1000 Vancouver / 1200 Chicago / 1300 Toronto / 1700 GMT / 1900 Berlin / 2230 Kolkata -- Fri Apr 30 0100 Singapore
- EmacsNYC: Monthly Online Meetup - Lightning Talks https://www.meetup.com/New-York-Emacs-Meetup/events/277390026/ Mon May 3 1600 Vancouver / 1800 Chicago / 1900 Toronto / 2300 GMT -- Tue May 4 0100 Berlin / 0430 Kolkata / 0700 Singapore
- EmacsATX: TBD https://www.meetup.com/EmacsATX/events/hkckgsycchbhb/ Wed May 5 1630 Vancouver / 1830 Chicago / 1930 Toronto / 2330 GMT -- Thu May 6 0130 Berlin / 0500 Kolkata / 0730 Singapore
- M-x Research (virtual, contact them for passcode) https://m-x-research.github.io/ Thu May 6 0700 Vancouver / 0900 Chicago / 1000 Toronto / 1400 GMT / 1600 Berlin / 1930 Kolkata / 2200 Singapore
- Emacs Paris (virtual) https://www.emacs-doctor.com/emacs-paris-user-group/ Thu May 6 0830 Vancouver / 1030 Chicago / 1130 Toronto / 1530 GMT / 1730 Berlin / 2100 Kolkata / 2330 Singapore
- M-x Research (virtual, contact them for passcode) https://m-x-research.github.io/ Thu May 20 0700 Vancouver / 0900 Chicago / 1000 Toronto / 1400 GMT / 1600 Berlin / 1930 Kolkata / 2200 Singapore
- Emacs APAC (virtual, in English) https://emacs-apac.gitlab.io/ Sat May 22 0130 Vancouver / 0330 Chicago / 0430 Toronto / 0830 GMT / 1030 Berlin / 1400 Kolkata / 1630 Singapore
- Singapore: Emacs & Never Code Alone SG https://www.meetup.com/Emacs-SG/events/268260076/ Wed May 26 0400 Vancouver / 0600 Chicago / 0700 Toronto / 1100 GMT / 1300 Berlin / 1630 Kolkata / 1900 Singapore
- Emacs Berlin (virtual, in English) https://emacs-berlin.org/ Wed May 26 0930 Vancouver / 1130 Chicago / 1230 Toronto / 1630 GMT / 1830 Berlin / 2200 Kolkata -- Thu May 27 0030 Singapore
- Emacs Paris (virtual) https://www.emacs-doctor.com/emacs-paris-user-group/ Tue Jun 1 0830 Vancouver / 1030 Chicago / 1130 Toronto / 1530 GMT / 1730 Berlin / 2100 Kolkata / 2330 Singapore
- EmacsATX: TBD https://www.meetup.com/EmacsATX/events/hkckgsyccjbdb/ Wed Jun 2 1630 Vancouver / 1830 Chicago / 1930 Toronto / 2330 GMT -- Thu Jun 3 0130 Berlin / 0500 Kolkata / 0730 Singapore
- M-x Research (virtual, contact them for passcode) https://m-x-research.github.io/ Thu Jun 3 0700 Vancouver / 0900 Chicago / 1000 Toronto / 1400 GMT / 1600 Berlin / 1930 Kolkata / 2200 Singapore
:end:

** Sync

#+NAME: sync
#+begin_src sh :exports code :eval never-export
rsync -avze ssh ./ web:/var/www/emacslife.com/calendar/ --exclude=.git
#+end_src

#+RESULTS: sync
:results:
sending incremental file list
README.org
emacs-calendar-berlin.html
emacs-calendar-berlin.org
emacs-calendar-chicago.html
emacs-calendar-chicago.org
emacs-calendar-gmt.html
emacs-calendar-gmt.org
emacs-calendar-kolkata.html
emacs-calendar-kolkata.org
emacs-calendar-singapore.html
emacs-calendar-singapore.org
emacs-calendar-toronto.html
emacs-calendar-toronto.org
emacs-calendar-vancouver.html
emacs-calendar-vancouver.org
emacs-calendar.ics

sent 8,195 bytes  received 6,729 bytes  29,848.00 bytes/sec
total size is 927,214  speedup is 62.13
:end:

** Convert timezones

#+NAME: convert-timezones
#+begin_src emacs-lisp :tangle yes :var timezones=timezones
(defun my/summarize-times (time timezones)
  (let (prev-day)
    (mapconcat
     (lambda (tz)
       (let ((cur-day (format-time-string "%a %b %-e" time tz))
             (cur-time (format-time-string "%H%MH %Z" time tz)))
         (if (equal prev-day cur-day)
             cur-time
           (setq prev-day cur-day)
           (concat cur-day " " cur-time))))
     timezones
     " / ")))

(defun my/org-summarize-event-in-timezones (timezones)
  (interactive (list (or timezones my/timezones)))
  (save-window-excursion
    (save-excursion
      (when (derived-mode-p 'org-agenda-mode) (org-agenda-goto))
      (when (re-search-forward org-element--timestamp-regexp nil (save-excursion (org-end-of-subtree) (point)))
        (goto-char (match-beginning 0))
        (let* ((times (org-element-timestamp-parser))
               (start-time (org-timestamp-to-time (org-timestamp-split-range times)))
               (msg (format "%s - %s - %s"
                            (org-get-heading t t t t)
                            (my/summarize-times start-time timezones)
                            ;; (cond
                            ;;  ((time-less-p (org-timestamp-to-time (org-timestamp-split-range times t)) (current-time))
                            ;;   "(past)")
                            ;;  ((time-less-p (current-time) start-time)
                            ;;   (concat "in " (format-seconds "%D %H %M%Z" (time-subtract start-time (current-time)))))
                            ;;  (t "(ongoing)"))
                            (org-entry-get (point) "LOCATION"))))
          (if (called-interactively-p 'any)
              (progn
                (message "%s" msg)
                (kill-new msg))
            msg))))))
#+end_src

#+RESULTS: convert-timezones
: my/org-summarize-event-in-timezones

#+RESULTS:
: my/org-summarize-event-in-timezones

** Summarize upcoming ones

#+NAME: upcoming-events
#+begin_src emacs-lisp :tangle yes
(defun my/summarize-upcoming-events (limit timezones)
  (interactive (list (org-read-date nil t) my/timezones))
  (let (result)
    (with-current-buffer (find-file-noselect "~/code/emacs-calendar/emacs-calendar-toronto.org")
      (goto-char (point-min))
      (org-map-entries
       (lambda ()
         (save-excursion
           (when (re-search-forward org-element--timestamp-regexp nil (save-excursion (org-end-of-subtree) (point)))
             (goto-char (match-beginning 0))
             (let ((time (org-timestamp-to-time (org-timestamp-split-range (org-element-timestamp-parser)))))
               (when (and (time-less-p (current-time) time)
                          (time-less-p time limit))
                 (setq result (cons
                               (cons time
                                     (my/org-summarize-event-in-timezones timezones)) result)))))))))
    (setq result (mapconcat
                  (lambda (o) (format "- %s" (cdr  o)))
                  (sort result (lambda (a b)
                                 (time-less-p (car a) (car b))
                                 ))
                  "\n"))
    (if (interactive-p)
        (insert result)
      result)))
#+end_src

#+RESULTS:
: my/summarize-upcoming-events


** Announcing Emacs events

#+NAME: announce
#+begin_src emacs-lisp
(defun my/announce-on-irc (channels message host port)
  (with-temp-buffer
    (insert "PASS " erc-password "\n"
            "USER " erc-nick "\n"
            "NICK " erc-nick "\n"
            (mapconcat (lambda (o)
                         (format "PRIVMSG %s :%s\n" o message))
                       channels "")
            "QUIT\n")
    (call-process-region (point-min) (point-max) "ncat" nil 0 nil
                         "--ssl" host (number-to-string port))))

(defun my/announce-on-irc-and-twitter (time channels message host port)
  (when (< (time-to-seconds (subtract-time (current-time) time)) (* 5 60))
    (shell-command-to-string (format
                              (if my/laptop-p
                                  "zsh -l -c 'rvm use 2.4.1; t update %s'"
                                "bash -l -c 't update %s'")
                              (shell-quote-argument message)))
    (my/announce-on-irc channels message host port)))

(defun my/schedule-announcement (time message)
  (interactive (list (org-read-date t t) (read-string "Message: ")))
  (run-at-time time nil #'my/announce-on-irc-and-twitter time '("#emacs" "#emacsconf") message erc-server erc-port))

(defun my/schedule-announcements-for-upcoming-emacs-meetups ()
  (interactive)
  (cancel-function-timers #'my/announce-on-irc-and-twitter)
  (let ((events (my/org-table-as-alist (pcsv-parse-file "events.csv")))
        (now (current-time))
        (before-limit (time-add (current-time) (seconds-to-time (* 7 24 60 60)))))
    (mapc (lambda (o)
            (let* ((start-time (encode-time (parse-time-string (alist-get 'DTSTART o))))
                   (fifteen-minutes-before (seconds-to-time (- (time-to-seconds start-time) (* 15 60)))))
              (when (and (time-less-p now fifteen-minutes-before)
                         (time-less-p fifteen-minutes-before before-limit))
                (my/schedule-announcement fifteen-minutes-before
                                          (format "In 15 minutes: %s - see %s for details"
                                                  (alist-get 'SUMMARY o)
                                                  (alist-get 'LOCATION o))))
              (when (and (time-less-p now start-time)
                         (time-less-p start-time before-limit))
                (my/schedule-announcement start-time
                                          (format "Starting now: %s - see %s for details"
                                                  (alist-get 'SUMMARY o)
                                                  (alist-get 'LOCATION o))))))
          events)))
  #+end_src

  #+RESULTS: announce
  :results:
  my/schedule-announcements-for-upcoming-emacs-meetups
  :end:
  
** Update EmacsWiki

#+begin_src emacs-lisp  :results nil
(use-package oddmuse
:load-path "~/vendor/oddmuse-el"
:if my/laptop-p
:ensure nil
:config (oddmuse-mode-initialize)
:hook (oddmuse-mode-hook .
          (lambda ()
            (unless (string-match "question" oddmuse-post)
              (when (string-match "EmacsWiki" oddmuse-wiki)
                (setq oddmuse-post (concat "uihnscuskc=1;" oddmuse-post)))
              (when (string-match "OddmuseWiki" oddmuse-wiki)
                (setq oddmuse-post (concat "ham=1;" oddmuse-post)))))))
#+end_src


[[elisp:(oddmuse-edit "EmacsWiki" "Usergroups")]]

** Testing agenda files :noexport:

#+begin_src emacs-lisp :exports results :var timezones=timezones :results list
  (mapcar (lambda (o) (org-link-make-string (format "elisp:(let ((org-agenda-files (list (expand-file-name \"emacs-calendar-%s.org\")))) (org-agenda-list nil nil 31))" (downcase (replace-regexp-in-string "^.*?/" "" (car o)))) (format "View %s agenda" (car o)))) timezones)
#+end_src

#+RESULTS:
- [[elisp:(let ((org-agenda-files (list (expand-file-name "emacs-calendar-gmt.org")))) (org-agenda-list nil nil 31))][View Etc/GMT agenda]]
- [[elisp:(let ((org-agenda-files (list (expand-file-name "emacs-calendar-vancouver.org")))) (org-agenda-list nil nil 31))][View America/Vancouver agenda]]
- [[elisp:(let ((org-agenda-files (list (expand-file-name "emacs-calendar-chicago.org")))) (org-agenda-list nil nil 31))][View America/Chicago agenda]]
- [[elisp:(let ((org-agenda-files (list (expand-file-name "emacs-calendar-toronto.org")))) (org-agenda-list nil nil 31))][View America/Toronto agenda]]
- [[elisp:(let ((org-agenda-files (list (expand-file-name "emacs-calendar-kolkata.org")))) (org-agenda-list nil nil 31))][View Asia/Kolkata agenda]]
- [[elisp:(let ((org-agenda-files (list (expand-file-name "emacs-calendar-shanghai.org")))) (org-agenda-list nil nil 31))][View Asia/Shanghai agenda]]
- [[elisp:(let ((org-agenda-files (list (expand-file-name "emacs-calendar-singapore.org")))) (org-agenda-list nil nil 31))][View Asia/Singapore agenda]]
- [[elisp:(let ((org-agenda-files (list (expand-file-name "emacs-calendar-berlin.org")))) (org-agenda-list nil nil 31))][View Europe/Berlin agenda]]



